import { ConflictException, Injectable, UnauthorizedException } from '@nestjs/common';
import { createHmac, randomBytes, scryptSync, timingSafeEqual } from 'node:crypto';
import { PrismaService } from '../prisma.service';

const ADMIN_ROLES=['ADMIN','ADMINISTRATEUR','DIRECTEUR GENERAL','DIRECTEUR HEBERGEMENT'];
const BASE_ROLES=['direction','reception_manager','reception','commercial','maintenance'] as const;
type BaseRole=(typeof BASE_ROLES)[number];
type ProfileMeta={label:string;description:string;baseRole:BaseRole;custom?:boolean};
const ALL_CAPABILITIES=['dashboard.view','reception.view','reception.operate','group-control.create','group-control.unlock','commercial.view','commercial.edit','commercial.validate-control','maintenance.view','maintenance.create','maintenance.manage','planning.view','meeting-rooms.view','meeting-rooms.edit','tasks.view','tasks.edit','instructions.view','instructions.edit','operations-center.view','operations-center.edit','journal.view','diagnostic.view','administration.view'] as const;
type Capability=(typeof ALL_CAPABILITIES)[number];
const BASE_CAPABILITIES:Record<BaseRole,Capability[]>={
 direction:[...ALL_CAPABILITIES],
 reception_manager:['dashboard.view','reception.view','reception.operate','group-control.create','group-control.unlock','maintenance.view','maintenance.create','planning.view','meeting-rooms.view','meeting-rooms.edit','tasks.view','tasks.edit','instructions.view','operations-center.view','operations-center.edit','journal.view','diagnostic.view'],
 reception:['dashboard.view','reception.view','reception.operate','group-control.create','maintenance.view','maintenance.create','planning.view','meeting-rooms.view','meeting-rooms.edit','tasks.view','tasks.edit','instructions.view','operations-center.view','operations-center.edit','journal.view'],
 commercial:['dashboard.view','commercial.view','commercial.edit','commercial.validate-control','group-control.unlock','maintenance.view','maintenance.create','planning.view','meeting-rooms.view','meeting-rooms.edit','tasks.view','tasks.edit','instructions.view','journal.view'],
 maintenance:['dashboard.view','maintenance.view','maintenance.create','maintenance.manage','planning.view','meeting-rooms.view','tasks.view','tasks.edit','instructions.view'],
};
const MANAGED_ROLES=[
 {name:'ADMIN',label:'Administrateur',description:'Accès complet à HospiCore',baseRole:'direction' as BaseRole},
 {name:'DIRECTEUR GENERAL',label:'Directeur Général',description:'Accès Direction à tous les modules métier',baseRole:'direction' as BaseRole},
 {name:'DIRECTEUR HEBERGEMENT',label:'Directeur Hébergement',description:'Direction Hébergement et supervision opérationnelle',baseRole:'direction' as BaseRole},
 {name:'CHEF DE RECEPTION',label:'Chef de Réception',description:'Pilotage Réception et contrôles Groupe',baseRole:'reception_manager' as BaseRole},
 {name:'RECEPTIONNISTE',label:'Réceptionniste',description:'Exploitation quotidienne de la Réception',baseRole:'reception' as BaseRole},
 {name:'COMMERCIAL',label:'Commercial',description:'Fiches Groupe, validation et suivi de facturation',baseRole:'commercial' as BaseRole},
 {name:'TECHNICIEN',label:'Technicien Maintenance',description:'Interventions et suivi Maintenance',baseRole:'maintenance' as BaseRole},
] as const;
const PREFIX:Record<BaseRole,string>={direction:'DIRECTION',reception_manager:'CHEF DE RECEPTION',reception:'RECEPTION',commercial:'COMMERCIAL',maintenance:'MAINTENANCE'};
const PERMISSIONS_NAMESPACE='user-permissions';

type PermissionMap=Record<string,string[]>;

@Injectable()
export class AuthService{
 constructor(private readonly prisma:PrismaService){}
 async status(){return{setupRequired:(await this.prisma.user.count())===0}}
 async setup(input:{firstName?:string;lastName?:string;email?:string;password?:string}){if((await this.prisma.user.count())>0)throw new UnauthorizedException('La configuration initiale est déjà terminée');const email=input.email?.trim().toLowerCase();if(!email||!input.password||input.password.length<10)throw new UnauthorizedException('Un e-mail et un mot de passe de 10 caractères minimum sont requis');const hotel=await this.prisma.hotel.create({data:{name:'Hôtel Paradis',slug:'hotel-paradis-lourdes'}}),admin=MANAGED_ROLES[0],role=await this.prisma.role.create({data:{name:admin.name,description:this.encodeMeta(admin)}}),user=await this.prisma.user.create({data:{firstName:input.firstName?.trim()||'Administrateur',lastName:input.lastName?.trim()||'HospiCore',email,passwordHash:this.hashPassword(input.password),hotelId:hotel.id,roleId:role.id},include:{role:true,hotel:true}});await this.ensureManagedRoles();return this.session(user)}
 async login(input:{email?:string;password?:string}){const email=input.email?.trim().toLowerCase();if(!email||!input.password)throw new UnauthorizedException('Identifiants invalides');const user=await this.prisma.user.findUnique({where:{email},include:{role:true,hotel:true}});if(!user||user.status!=='ACTIVE'||!this.verifyPassword(input.password,user.passwordHash))throw new UnauthorizedException('Identifiants invalides ou compte suspendu');return this.session(user)}
 async adminUsers(authorization?:string){const actor=await this.requireAdmin(authorization),users=await this.prisma.user.findMany({where:{hotelId:actor.hotelId},include:{role:true},orderBy:[{status:'asc'},{lastName:'asc'},{firstName:'asc'}]}),map=await this.permissionMap(actor.hotelId);return users.map(user=>{const meta=this.roleMeta(user.role),inherited=BASE_CAPABILITIES[meta.baseRole],custom=map[user.id];return{id:user.id,firstName:user.firstName,lastName:user.lastName,email:user.email,status:user.status,role:user.role.name,roleLabel:meta.label,baseRole:meta.baseRole,inheritedPermissions:inherited,permissions:custom||inherited,permissionsCustomized:Boolean(custom),createdAt:user.createdAt,updatedAt:user.updatedAt}})}
 async adminRoles(authorization?:string){await this.requireAdmin(authorization);await this.ensureManagedRoles();const roles=await this.prisma.role.findMany({orderBy:{name:'asc'}});return roles.map(role=>({id:role.id,name:role.name,...this.roleMeta(role)}))}
 async createRole(authorization:string|undefined,input:{label?:string;description?:string;baseRole?:string}){await this.requireAdmin(authorization);const label=String(input.label||'').trim(),description=String(input.description||'').trim(),baseRole=this.validBaseRole(input.baseRole);if(label.length<2)throw new UnauthorizedException('Le nom du profil est requis');const slug=label.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z0-9]+/g,'_').replace(/^_|_$/g,''),name=`${PREFIX[baseRole]} PROFIL ${slug}`;if(await this.prisma.role.findUnique({where:{name}}))throw new ConflictException('Un profil portant ce nom existe déjà');const meta:ProfileMeta={label,description:description||`Profil personnalisé ${label}`,baseRole,custom:true},role=await this.prisma.role.create({data:{name,description:this.encodeMeta(meta)}});return{id:role.id,name:role.name,...meta}}
 async createUser(authorization:string|undefined,input:{firstName?:string;lastName?:string;email?:string;password?:string;role?:string}){const actor=await this.requireAdmin(authorization),firstName=input.firstName?.trim(),lastName=input.lastName?.trim(),email=input.email?.trim().toLowerCase(),password=input.password||'';if(!firstName||!lastName||!email||password.length<10)throw new UnauthorizedException('Prénom, nom, e-mail et mot de passe de 10 caractères minimum sont requis');if(await this.prisma.user.findUnique({where:{email}}))throw new ConflictException('Cette adresse e-mail est déjà utilisée');const role=await this.resolveRole(input.role),user=await this.prisma.user.create({data:{firstName,lastName,email,passwordHash:this.hashPassword(password),hotelId:actor.hotelId,roleId:role.id,status:'ACTIVE'},include:{role:true}});return{id:user.id,firstName:user.firstName,lastName:user.lastName,email:user.email,status:user.status,role:user.role.name,roleLabel:this.roleMeta(user.role).label,createdAt:user.createdAt,updatedAt:user.updatedAt}}
 async updateUser(authorization:string|undefined,id:string,input:{firstName?:string;lastName?:string;email?:string;role?:string;status?:'ACTIVE'|'INACTIVE'}){const actor=await this.requireAdmin(authorization),target=await this.prisma.user.findFirst({where:{id,hotelId:actor.hotelId},include:{role:true}});if(!target)throw new UnauthorizedException('Utilisateur introuvable');if(target.id===actor.id&&input.status==='INACTIVE')throw new UnauthorizedException('Vous ne pouvez pas suspendre votre propre compte');const role=input.role?await this.resolveRole(input.role):target.role,email=input.email?.trim().toLowerCase();if(email&&email!==target.email&&await this.prisma.user.findUnique({where:{email}}))throw new ConflictException('Cette adresse e-mail est déjà utilisée');const user=await this.prisma.user.update({where:{id},data:{firstName:input.firstName?.trim()||target.firstName,lastName:input.lastName?.trim()||target.lastName,email:email||target.email,roleId:role.id,status:input.status||target.status},include:{role:true}});if(input.role)await this.resetUserPermissionOverride(actor.hotelId,id,actor.id);return{id:user.id,firstName:user.firstName,lastName:user.lastName,email:user.email,status:user.status,role:user.role.name,roleLabel:this.roleMeta(user.role).label,createdAt:user.createdAt,updatedAt:user.updatedAt}}
 async updateUserPermissions(authorization:string|undefined,id:string,input:{permissions?:string[];reset?:boolean}){const actor=await this.requireAdmin(authorization),target=await this.prisma.user.findFirst({where:{id,hotelId:actor.hotelId},include:{role:true}});if(!target)throw new UnauthorizedException('Utilisateur introuvable');if(input.reset){await this.resetUserPermissionOverride(actor.hotelId,id,actor.id);return{ok:true,permissions:BASE_CAPABILITIES[this.roleMeta(target.role).baseRole],customized:false}}const requested=Array.from(new Set((input.permissions||[]).filter((p):p is Capability=>ALL_CAPABILITIES.includes(p as Capability))));if(target.id===actor.id&&!requested.includes('administration.view'))throw new UnauthorizedException('Vous ne pouvez pas retirer votre propre accès Administration');const map=await this.permissionMap(actor.hotelId);map[id]=requested;await this.savePermissionMap(actor.hotelId,map,actor.id);return{ok:true,permissions:requested,customized:true}}
 async resetPassword(authorization:string|undefined,id:string,password?:string){const actor=await this.requireAdmin(authorization);if(!password||password.length<10)throw new UnauthorizedException('Le nouveau mot de passe doit comporter au moins 10 caractères');const target=await this.prisma.user.findFirst({where:{id,hotelId:actor.hotelId}});if(!target)throw new UnauthorizedException('Utilisateur introuvable');await this.prisma.user.update({where:{id},data:{passwordHash:this.hashPassword(password)}});return{ok:true}}
 verifyToken(token:string){const[payload,signature]=token.split('.');if(!payload||!signature)throw new UnauthorizedException('Session invalide');const expected=this.sign(payload),a=Buffer.from(signature),b=Buffer.from(expected);if(a.length!==b.length||!timingSafeEqual(a,b))throw new UnauthorizedException('Session invalide');const data=JSON.parse(Buffer.from(payload,'base64url').toString('utf8')) as{sub:string;exp:number;email:string;role:string};if(data.exp<Date.now())throw new UnauthorizedException('Session expirée');return data}
 private async requireAdmin(authorization?:string){const token=authorization?.replace(/^Bearer\s+/i,'').trim();if(!token)throw new UnauthorizedException('Authentification requise');const payload=this.verifyToken(token),user=await this.prisma.user.findUnique({where:{id:payload.sub},include:{role:true}});if(!user||user.status!=='ACTIVE')throw new UnauthorizedException('Accès administrateur requis');const meta=this.roleMeta(user.role),permissions=await this.effectivePermissions(user.hotelId,user.id,meta.baseRole);if(!permissions.includes('administration.view'))throw new UnauthorizedException('Accès administrateur requis');return user}
 private validBaseRole(value?:string):BaseRole{const role=String(value||'').trim() as BaseRole;if(!BASE_ROLES.includes(role))throw new UnauthorizedException('Profil de droits invalide');return role}
 private async resolveRole(value?:string){const name=String(value||'').trim().toUpperCase();if(!name)throw new UnauthorizedException('Profil utilisateur requis');await this.ensureManagedRoles();const role=await this.prisma.role.findUnique({where:{name}});if(!role)throw new UnauthorizedException('Profil HospiCore invalide');return role}
 private async ensureManagedRoles(){for(const role of MANAGED_ROLES)await this.prisma.role.upsert({where:{name:role.name},update:{description:this.encodeMeta(role)},create:{name:role.name,description:this.encodeMeta(role)}})}
 private encodeMeta(meta:{label:string;description:string;baseRole:BaseRole;custom?:boolean}){return JSON.stringify({label:meta.label,description:meta.description,baseRole:meta.baseRole,custom:Boolean(meta.custom)})}
 private roleMeta(role:{name:string;description:string|null}):ProfileMeta{try{const parsed=JSON.parse(role.description||'{}');if(parsed?.label&&BASE_ROLES.includes(parsed.baseRole))return{label:String(parsed.label),description:String(parsed.description||''),baseRole:parsed.baseRole,custom:Boolean(parsed.custom)}}catch{}const preset=MANAGED_ROLES.find(item=>item.name===role.name);return preset?{label:preset.label,description:preset.description,baseRole:preset.baseRole}:{label:role.name,description:role.description||'',baseRole:'reception',custom:true}}
 private async permissionMap(hotelId:string):Promise<PermissionMap>{const store=await this.prisma.operationalStore.findUnique({where:{hotelId_namespace:{hotelId,namespace:PERMISSIONS_NAMESPACE}}});if(!store||!store.payload||Array.isArray(store.payload)||typeof store.payload!=='object')return{};return store.payload as unknown as PermissionMap}
 private async savePermissionMap(hotelId:string,map:PermissionMap,actorId:string){await this.prisma.operationalStore.upsert({where:{hotelId_namespace:{hotelId,namespace:PERMISSIONS_NAMESPACE}},update:{payload:map as any,updatedById:actorId},create:{hotelId,namespace:PERMISSIONS_NAMESPACE,payload:map as any,updatedById:actorId}})}
 private async resetUserPermissionOverride(hotelId:string,userId:string,actorId:string){const map=await this.permissionMap(hotelId);if(!(userId in map))return;delete map[userId];await this.savePermissionMap(hotelId,map,actorId)}
 private async effectivePermissions(hotelId:string,userId:string,baseRole:BaseRole){const map=await this.permissionMap(hotelId);return (map[userId]||BASE_CAPABILITIES[baseRole]) as string[]}
 private async session(user:{id:string;firstName:string;lastName:string;email:string;role:{name:string;description:string|null};hotel:{id:string;name:string}}){const meta=this.roleMeta(user.role),permissions=await this.effectivePermissions(user.hotel.id,user.id,meta.baseRole),payload=Buffer.from(JSON.stringify({sub:user.id,email:user.email,role:user.role.name,exp:Date.now()+12*60*60*1000})).toString('base64url');return{token:`${payload}.${this.sign(payload)}`,user:{id:user.id,firstName:user.firstName,lastName:user.lastName,email:user.email,role:{name:user.role.name,label:meta.label,baseRole:meta.baseRole},permissions,hotelId:user.hotel.id,hotel:user.hotel}}}
 private sign(payload:string){const secret=process.env.JWT_SECRET;if(!secret)throw new Error('JWT_SECRET manquant');return createHmac('sha256',secret).update(payload).digest('base64url')}
 private hashPassword(password:string){const salt=randomBytes(16).toString('hex');return`${salt}:${scryptSync(password,salt,64).toString('hex')}`}
 private verifyPassword(password:string,stored:string){const[salt,hash]=stored.split(':');if(!salt||!hash)return false;const a=Buffer.from(hash,'hex'),b=scryptSync(password,salt,64);return a.length===b.length&&timingSafeEqual(a,b)}
}
