import { useMemo, useState } from 'react';
import { ArrowLeft, BookOpenCheck, CalendarDays, Clock3, Filter, Hotel, Search, UsersRound, Wrench } from 'lucide-react';
import { roleFromValue } from './permissions';
import { useOperationalStore } from './useOperationalStore';

type JournalEntry={id:string;at:string;actorId?:string;actor:string;role:string;service:string;namespace:string;source:string;action:string;reference?:string;priority?:string};
type Audit={id?:string;action?:string;actor?:string;role?:string;at?:string;comment?:string};
type Group={id:string;name?:string;audit?:Audit[]};
type Maintenance={id:string;reference?:string;title?:string;priority?:string;history?:Audit[];audit?:Audit[];createdBy?:string;createdAt?:string};
type Activity={id:string;at:string;timestamp:number;action:string;actor:string;role:string;service:string;source:string;reference?:string;priority?:string};

function isoDate(date=new Date()){return`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`}
function parseDate(value:string){const t=Date.parse(value);if(Number.isFinite(t))return t;const m=value.match(/(\d{2})\/(\d{2})\/(\d{4})[ ,à]*(\d{2}):(\d{2})(?::(\d{2}))?/);return m?new Date(Number(m[3]),Number(m[2])-1,Number(m[1]),Number(m[4]),Number(m[5]),Number(m[6]||0)).getTime():0}
function dayOf(value:string){const t=parseDate(value);return t?isoDate(new Date(t)):''}
function user(){try{return JSON.parse(localStorage.getItem('hospicore.session')||'{}')?.user||{}}catch{return{}}}
function department(){const role=roleFromValue(user().role);return role==='direction'?'Direction':role==='commercial'?'Commercial':role==='maintenance'?'Maintenance':'Réception'}
function isDirection(){return roleFromValue(user().role)==='direction'}
function normalizeService(value?:string){const raw=String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();if(raw.includes('maintenance')||raw.includes('technique'))return'Maintenance';if(raw.includes('commercial')||raw.includes('vente'))return'Commercial';if(raw.includes('direction')||raw.includes('directeur')||raw.includes('admin'))return'Direction';return'Réception'}
const icons:Record<string,typeof Hotel>={Réception:Hotel,Maintenance:Wrench,Commercial:UsersRound,Direction:BookOpenCheck};

export function ActivityJournalPage(){
 const journal=useOperationalStore<JournalEntry[]>('activity-journal',[]),groups=useOperationalStore<Group[]>('group-360',[]),maintenance=useOperationalStore<Maintenance[]>('maintenance-interventions',[]);
 const[selectedDate,setSelectedDate]=useState(isoDate()),[query,setQuery]=useState(''),[service,setService]=useState(()=>isDirection()?'Tous':department());
 const immutable=useMemo<Activity[]>(()=>journal.data.map(e=>({id:`journal-${e.id}`,at:e.at,timestamp:parseDate(e.at),action:e.action||'Mise à jour',actor:e.actor||'HospiCore',role:e.role||e.service,service:normalizeService(e.service),source:e.source||e.namespace,reference:e.reference,priority:e.priority})),[journal.data]);
 const legacy=useMemo<Activity[]>(()=>{const out:Activity[]=[];const push=(prefix:string,entries:Audit[]|undefined,serviceName:string,source:string,reference?:string,priority?:string)=>(entries||[]).forEach((e,i)=>out.push({id:`legacy-${prefix}-${e.id||i}`,at:e.at||'',timestamp:parseDate(e.at||''),action:e.action||'Mise à jour',actor:e.actor||'Utilisateur HospiCore',role:e.role||serviceName,service:serviceName,source,reference,priority}));groups.data.forEach(g=>push(`group-${g.id}`,g.audit,'Réception','Groupe 360°',g.name));maintenance.data.forEach(m=>{const entries=m.history||m.audit;if(entries?.length)push(`maintenance-${m.id}`,entries,'Maintenance','Intervention',m.reference||m.title,m.priority)});return out},[groups.data,maintenance.data]);
 const items=useMemo(()=>{const seen=new Set<string>();return[...immutable,...legacy].filter(item=>{const key=`${item.timestamp}|${item.actor}|${item.action}|${item.source}|${item.reference||''}`;if(seen.has(key))return false;seen.add(key);return true}).sort((a,b)=>b.timestamp-a.timestamp)},[immutable,legacy]);
 const allowedServices=isDirection()?['Tous','Réception','Commercial','Maintenance','Direction']:[department()];
 const filtered=useMemo(()=>items.filter(item=>dayOf(item.at)===selectedDate&&(service==='Tous'||item.service===service)&&`${item.action} ${item.actor} ${item.role} ${item.source} ${item.reference||''}`.toLowerCase().includes(query.toLowerCase())),[items,selectedDate,service,query]);
 const dayItems=items.filter(item=>dayOf(item.at)===selectedDate&&(isDirection()||item.service===department())),uniqueUsers=new Set(dayItems.map(i=>i.actor)).size,critical=dayItems.filter(i=>i.priority==='Critique'||i.priority==='Urgente').length;
 const stores=[journal,groups,maintenance],loading=stores.some(s=>s.state==='loading'||s.state==='saving'),hasError=stores.some(s=>s.state==='error'||s.state==='conflict');
 const refresh=()=>stores.forEach(s=>void s.refresh());
 return <div className="activity-page"><header className="activity-header"><div><button onClick={()=>location.href='/'}><ArrowLeft size={18}/>Centre de Commandement</button><p>HospiCore · Traçabilité</p><h1>Journal Live</h1><span>Historique journalier immuable · consultation en lecture seule.</span></div><button className="activity-refresh" onClick={refresh}><Clock3 size={17}/>{loading?'Synchronisation…':hasError?'Réessayer':'Actualiser'}</button></header>
 <section className="activity-kpis"><article><CalendarDays/><span>Événements du jour sélectionné</span><strong>{dayItems.length}</strong></article><article><UsersRound/><span>Collaborateurs</span><strong>{uniqueUsers}</strong></article><article><BookOpenCheck/><span>Historique total conservé</span><strong>{items.length}</strong></article><article><Wrench/><span>Alertes critiques</span><strong>{critical}</strong></article></section>
 <section className="activity-toolbar"><label><CalendarDays size={17}/><input type="date" value={selectedDate} max={isoDate()} onChange={e=>setSelectedDate(e.target.value)}/></label><label><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher une action, un utilisateur ou une référence…"/></label><div><Filter size={17}/><select value={service} disabled={!isDirection()} onChange={e=>setService(e.target.value)}>{allowedServices.map(s=><option key={s}>{s}</option>)}</select></div></section>
 <section className="activity-readonly-banner"><BookOpenCheck size={17}/><span><strong>Lecture seule.</strong> Les événements sont horodatés automatiquement et ne peuvent pas être modifiés depuis ce journal. {isDirection()?'La Direction consulte tous les départements.':`Vous consultez le journal ${department()}.`}</span></section>
 <section className="activity-feed">{filtered.map(item=>{const Icon=icons[item.service]||BookOpenCheck;const d=new Date(item.timestamp);return <article key={item.id} className="activity-entry"><div className="activity-time"><strong>{d.toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}</strong><span>{d.toLocaleDateString('fr-FR',{day:'2-digit',month:'2-digit',year:'numeric'})}</span></div><div className="activity-line"><i/></div><div className="activity-icon"><Icon size={19}/></div><div className="activity-content"><div><span>{item.service}</span>{item.priority&&<em className={item.priority.toLowerCase()}>{item.priority}</em>}</div><h2>{item.action}</h2><p>{item.source}{item.reference?` · ${item.reference}`:''}</p><small>Horodaté par <strong>{item.actor}</strong> · {item.role}</small></div></article>})}{filtered.length===0&&<div className="activity-empty">Aucun événement enregistré pour cette journée et ce périmètre.</div>}</section></div>;
}
