import { FormEvent, useEffect, useMemo, useState } from 'react';
import { ArrowLeft, Building2, CheckCircle2, KeyRound, Plus, RefreshCw, Settings, ShieldCheck, Tag, UserCog, Users, X } from 'lucide-react';
import { capabilitiesForRole, roleFromValue } from './permissions';
import { useOperationalStore } from './useOperationalStore';

type AccountStatus='ACTIVE'|'INACTIVE'|'INVITED';
type Account={id:string;firstName:string;lastName:string;email:string;role:string;status:AccountStatus;createdAt:string;updatedAt:string};
type ManagedRole={name:string;label:string;description:string};
type MeetingRoom={id:string;name:string;capacity:number;location:string;active:boolean};
type Category={id:string;label:string;department:string;active:boolean};
type AdminSettings={rooms:MeetingRoom[];categories:Category[];users?:unknown[]};
type Tab='utilisateurs'|'autorisations'|'salles'|'categories';
type Modal='user'|'room'|'category'|'password'|null;
const EMPTY:AdminSettings={rooms:[],categories:[]};
const SERVICES=['Direction','Réception','Commercial','Maintenance'];
const capabilityLabels:Record<string,string>={
 'dashboard.view':'Centre de Commandement','reception.view':'Réception · lecture','reception.operate':'Réception · opérations',
 'group-control.create':'Contrôles Groupe','group-control.unlock':'Déverrouillage contrôles','commercial.view':'Commercial · lecture',
 'commercial.edit':'Commercial · modification','commercial.validate-control':'Validation commerciale','maintenance.view':'Maintenance · lecture',
 'maintenance.create':'Créer une intervention','maintenance.manage':'Piloter la maintenance','planning.view':'Planning opérationnel',
 'meeting-rooms.view':'Salles · lecture','meeting-rooms.edit':'Salles · modification','tasks.view':'Tâches · lecture','tasks.edit':'Tâches · modification',
 'instructions.view':'Consignes · lecture','instructions.edit':'Consignes · modification','operations-center.view':'Centre opérations · lecture',
 'operations-center.edit':'Centre opérations · modification','journal.view':'Journal','diagnostic.view':'Diagnostic','administration.view':'Administration',
};
function token(){try{return JSON.parse(localStorage.getItem('hospicore.session')||'{}')?.token||localStorage.getItem('hospicore.token')||''}catch{return localStorage.getItem('hospicore.token')||''}}
async function api<T>(url:string,options:RequestInit={}):Promise<T>{const response=await fetch(url,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token()}`,...(options.headers||{})}});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(Array.isArray(body?.message)?body.message.join(' · '):body?.message||`Erreur HTTP ${response.status}`);return body as T}

export function AdministrationPage(){
 const settings=useOperationalStore<AdminSettings>('administration-settings',EMPTY);
 const rooms=settings.data.rooms||[],categories=settings.data.categories||[];
 const[tab,setTab]=useState<Tab>('utilisateurs'),[modal,setModal]=useState<Modal>(null),[passwordUser,setPasswordUser]=useState<Account|null>(null);
 const[accounts,setAccounts]=useState<Account[]>([]),[roles,setRoles]=useState<ManagedRole[]>([]),[usersLoading,setUsersLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const activeUsers=useMemo(()=>accounts.filter(u=>u.status==='ACTIVE').length,[accounts]);
 async function loadAccounts(){setUsersLoading(true);setError('');try{const [u,r]=await Promise.all([api<Account[]>('/api/auth/admin/users'),api<ManagedRole[]>('/api/auth/admin/roles')]);setAccounts(u);setRoles(r)}catch(e){setError(e instanceof Error?e.message:'Impossible de charger les comptes')}finally{setUsersLoading(false)}}
 useEffect(()=>{void loadAccounts()},[]);
 async function createUser(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');const f=new FormData(e.currentTarget);try{await api('/api/auth/admin/users',{method:'POST',body:JSON.stringify({firstName:f.get('firstName'),lastName:f.get('lastName'),email:f.get('email'),password:f.get('password'),role:f.get('role')})});setModal(null);setNotice('Compte créé. Le collaborateur peut maintenant se connecter avec son e-mail et son mot de passe.');await loadAccounts()}catch(e){setError(e instanceof Error?e.message:'Création impossible')}}
 async function patchUser(id:string,patch:Record<string,unknown>){setError('');try{await api(`/api/auth/admin/users/${id}`,{method:'PATCH',body:JSON.stringify(patch)});await loadAccounts()}catch(e){setError(e instanceof Error?e.message:'Modification impossible')}}
 async function resetPassword(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!passwordUser)return;const f=new FormData(e.currentTarget);const password=String(f.get('password')||''),confirm=String(f.get('confirm')||'');if(password!==confirm){setError('Les deux mots de passe ne correspondent pas.');return}try{await api(`/api/auth/admin/users/${passwordUser.id}/password`,{method:'POST',body:JSON.stringify({password})});setPasswordUser(null);setModal(null);setNotice(`Mot de passe de ${passwordUser.firstName} ${passwordUser.lastName} réinitialisé.`)}catch(e){setError(e instanceof Error?e.message:'Réinitialisation impossible')}}
 async function createRoom(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),value:MeetingRoom={id:crypto.randomUUID(),name:String(f.get('name')||''),capacity:Number(f.get('capacity')||0),location:String(f.get('location')||''),active:true};if(await settings.save({...settings.data,rooms:[value,...rooms]}))setModal(null)}
 async function createCategory(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),value:Category={id:crypto.randomUUID(),label:String(f.get('label')||''),department:String(f.get('department')||''),active:true};if(await settings.save({...settings.data,categories:[value,...categories]}))setModal(null)}
 async function toggleRoom(id:string){await settings.save({...settings.data,rooms:rooms.map(r=>r.id===id?{...r,active:!r.active}:r)})}
 async function toggleCategory(id:string){await settings.save({...settings.data,categories:categories.map(c=>c.id===id?{...c,active:!c.active}:c)})}
 const busy=settings.state==='loading'||settings.state==='saving'||usersLoading;
 return <div className="admin-page"><header className="admin-header"><div><button onClick={()=>location.href='/'}><ArrowLeft size={18}/>Centre de Commandement</button><p>HospiCore · Administration sécurisée</p><h1>Administration</h1><span>Comptes utilisateurs, identifiants de connexion, rôles et autorisations.</span></div><div className="admin-header-actions"><button onClick={()=>{void loadAccounts();void settings.refresh()}} disabled={busy}><RefreshCw size={17}/>{busy?'Actualisation…':'Actualiser'}</button><ShieldCheck size={38}/></div></header>
 {error&&<div className="admin-api-message error">{error}</div>}{notice&&<div className="admin-api-message success"><CheckCircle2 size={17}/>{notice}</div>}
 <section className="admin-kpis"><article><Users/><span>Comptes actifs</span><strong>{activeUsers}</strong></article><article><UserCog/><span>Comptes suspendus</span><strong>{accounts.filter(u=>u.status==='INACTIVE').length}</strong></article><article><ShieldCheck/><span>Rôles disponibles</span><strong>{roles.length}</strong></article><article><Settings/><span>Services métier</span><strong>{SERVICES.length}</strong></article></section>
 <nav className="admin-tabs">{([['utilisateurs','Utilisateurs & accès',UserCog],['autorisations','Autorisations',ShieldCheck],['salles','Référentiel salles',Building2],['categories','Catégories',Tag]] as const).map(([key,label,Icon])=><button className={tab===key?'active':''} onClick={()=>setTab(key)} key={key}><Icon size={17}/>{label}</button>)}</nav>
 {tab==='utilisateurs'&&<section className="admin-panel"><div className="admin-panel-head"><div><h2>Comptes de connexion</h2><p>Les mots de passe sont hashés côté serveur et ne sont jamais affichés ni enregistrés dans le navigateur.</p></div><button onClick={()=>{setError('');setModal('user')}}><Plus size={17}/>Créer un compte</button></div>{usersLoading?<div className="admin-empty">Chargement des comptes…</div>:accounts.length===0?<div className="admin-empty">Aucun compte utilisateur.</div>:<div className="admin-table admin-users-table"><div className="admin-row head"><span>Utilisateur / login</span><span>Rôle</span><span>Statut</span><span>Sécurité</span><span>Dernière modification</span></div>{accounts.map(u=><div className="admin-row" key={u.id}><span><strong>{u.firstName} {u.lastName}</strong><small>{u.email}</small></span><span><select value={u.role} onChange={e=>void patchUser(u.id,{role:e.target.value})}>{roles.map(r=><option value={r.name} key={r.name}>{r.label}</option>)}</select></span><span><button className={`admin-status ${u.status==='ACTIVE'?'actif':'suspendu'}`} onClick={()=>void patchUser(u.id,{status:u.status==='ACTIVE'?'INACTIVE':'ACTIVE'})}>{u.status==='ACTIVE'?'Actif':'Suspendu'}</button></span><span><button className="admin-password-button" onClick={()=>{setPasswordUser(u);setError('');setModal('password')}}><KeyRound size={15}/>Nouveau mot de passe</button></span><span><small>{new Date(u.updatedAt).toLocaleString('fr-FR')}</small></span></div>)}</div>}</section>}
 {tab==='autorisations'&&<section className="admin-panel"><div className="admin-panel-head"><div><h2>Autorisations par rôle</h2><p>Les droits sont appliqués automatiquement dès la prochaine connexion de l’utilisateur.</p></div></div><div className="admin-permission-grid">{roles.map(role=>{const appRole=roleFromValue(role.name),caps=capabilitiesForRole(appRole);return <article key={role.name}><header><div><ShieldCheck size={20}/><strong>{role.label}</strong></div><span>{caps.length} autorisation(s)</span></header><p>{role.description}</p><div className="admin-permission-list">{caps.map(cap=><span key={cap}><CheckCircle2 size={13}/>{capabilityLabels[cap]||cap}</span>)}</div></article>})}</div></section>}
 {tab==='salles'&&<section className="admin-panel"><div className="admin-panel-head"><div><h2>Référentiel salles</h2><p>Référentiel partagé PostgreSQL, sans donnée d’exemple.</p></div><button onClick={()=>setModal('room')}><Plus size={17}/>Ajouter une salle</button></div>{rooms.length===0?<div className="admin-empty">Aucune salle référencée.</div>:<div className="admin-card-grid">{rooms.map(r=><article key={r.id}><div><Building2/><span className={r.active?'enabled':'disabled'}>{r.active?'Active':'Désactivée'}</span></div><h3>{r.name}</h3><p>{r.capacity} personnes · {r.location}</p><button onClick={()=>void toggleRoom(r.id)}>{r.active?'Désactiver':'Réactiver'}</button></article>)}</div>}</section>}
 {tab==='categories'&&<section className="admin-panel"><div className="admin-panel-head"><div><h2>Catégories de consignes</h2><p>Référentiel utilisé pour les consignes générales.</p></div><button onClick={()=>setModal('category')}><Plus size={17}/>Ajouter une catégorie</button></div>{categories.length===0?<div className="admin-empty">Aucune catégorie référencée.</div>:<div className="admin-card-grid">{categories.map(c=><article key={c.id}><div><Tag/><span className={c.active?'enabled':'disabled'}>{c.active?'Active':'Désactivée'}</span></div><h3>{c.label}</h3><p>Service : {c.department}</p><button onClick={()=>void toggleCategory(c.id)}>{c.active?'Désactiver':'Réactiver'}</button></article>)}</div>}</section>}
 {modal&&<div className="admin-modal"><form onSubmit={modal==='user'?createUser:modal==='password'?resetPassword:modal==='room'?createRoom:createCategory}><header><div><p>Administration</p><h2>{modal==='user'?'Créer un compte':modal==='password'?'Réinitialiser le mot de passe':modal==='room'?'Nouvelle salle':'Nouvelle catégorie'}</h2></div><button type="button" onClick={()=>{setModal(null);setPasswordUser(null)}}><X/></button></header>{modal==='user'&&<div className="admin-form"><label>Prénom<input name="firstName" required autoComplete="off"/></label><label>Nom<input name="lastName" required autoComplete="off"/></label><label className="wide">Login / adresse e-mail<input name="email" type="email" required autoComplete="off"/></label><label>Rôle<select name="role" required>{roles.map(r=><option value={r.name} key={r.name}>{r.label}</option>)}</select></label><label className="wide">Mot de passe initial<input name="password" type="password" minLength={10} required autoComplete="new-password"/><small>10 caractères minimum. À transmettre au collaborateur par un canal sécurisé.</small></label></div>}{modal==='password'&&<div className="admin-form"><p className="wide">Compte : <strong>{passwordUser?.firstName} {passwordUser?.lastName}</strong> · {passwordUser?.email}</p><label className="wide">Nouveau mot de passe<input name="password" type="password" minLength={10} required autoComplete="new-password"/></label><label className="wide">Confirmer le mot de passe<input name="confirm" type="password" minLength={10} required autoComplete="new-password"/></label></div>}{modal==='room'&&<div className="admin-form"><label className="wide">Nom de la salle<input name="name" required/></label><label>Capacité<input name="capacity" type="number" min="1" required/></label><label>Emplacement<input name="location" required/></label></div>}{modal==='category'&&<div className="admin-form"><label className="wide">Nom de la catégorie<input name="label" required/></label><label>Service<select name="department">{SERVICES.map(s=><option key={s}>{s}</option>)}</select></label></div>} {error&&<div className="admin-form-error">{error}</div>}<footer><button type="button" onClick={()=>{setModal(null);setPasswordUser(null)}}>Annuler</button><button type="submit" disabled={busy}>{modal==='user'?'Créer le compte':modal==='password'?'Changer le mot de passe':'Enregistrer'}</button></footer></form></div>}
 </div>
}
