import { FormEvent, useMemo, useState } from 'react';
import { ArrowLeft, Building2, CheckCircle2, Plus, RefreshCw, Settings, ShieldCheck, Tag, UserCog, Users, X } from 'lucide-react';
import { useOperationalStore } from './useOperationalStore';

type UserStatus='Actif'|'Suspendu';
type AdminUser={id:string;firstName:string;lastName:string;email:string;role:string;department:string;extension:string;status:UserStatus;updatedAt:string;updatedBy:string};
type MeetingRoom={id:string;name:string;capacity:number;location:string;active:boolean};
type Category={id:string;label:string;department:string;active:boolean};
type AdminSettings={users:AdminUser[];rooms:MeetingRoom[];categories:Category[]};
type Tab='utilisateurs'|'services'|'salles'|'categories';
const EMPTY:AdminSettings={users:[],rooms:[],categories:[]};
const SERVICES=['Direction','Réception','Commercial','Maintenance'];
const ROLES=['Administrateur','Directeur Général','Directeur Hébergement','Chef de Réception','Réceptionniste','Commercial','Technicien'];
function currentUser(){try{const s=JSON.parse(localStorage.getItem('hospicore.session')||'{}');const u=s.user||{};return`${u.firstName||'Utilisateur'} ${u.lastName||'HospiCore'}`.trim()}catch{return'Utilisateur HospiCore'}}
function stamp(){return new Date().toLocaleString('fr-FR')}

export function AdministrationPage(){
 const store=useOperationalStore<AdminSettings>('administration-settings',EMPTY),{users,rooms,categories}=store.data;
 const[tab,setTab]=useState<Tab>('utilisateurs'),[modal,setModal]=useState<'user'|'room'|'category'|null>(null);
 const activeUsers=useMemo(()=>users.filter(u=>u.status==='Actif').length,[users]);
 async function createUser(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),value:AdminUser={id:crypto.randomUUID(),firstName:String(f.get('firstName')||''),lastName:String(f.get('lastName')||''),email:String(f.get('email')||''),role:String(f.get('role')||''),department:String(f.get('department')||''),extension:String(f.get('extension')||''),status:'Actif',updatedAt:stamp(),updatedBy:currentUser()};if(await store.save({...store.data,users:[value,...users]}))setModal(null)}
 async function createRoom(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),value:MeetingRoom={id:crypto.randomUUID(),name:String(f.get('name')||''),capacity:Number(f.get('capacity')||0),location:String(f.get('location')||''),active:true};if(await store.save({...store.data,rooms:[value,...rooms]}))setModal(null)}
 async function createCategory(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),value:Category={id:crypto.randomUUID(),label:String(f.get('label')||''),department:String(f.get('department')||''),active:true};if(await store.save({...store.data,categories:[value,...categories]}))setModal(null)}
 async function toggleUser(id:string){await store.save({...store.data,users:users.map(u=>u.id===id?{...u,status:u.status==='Actif'?'Suspendu' as const:'Actif' as const,updatedAt:stamp(),updatedBy:currentUser()}:u)})}
 async function toggleRoom(id:string){await store.save({...store.data,rooms:rooms.map(r=>r.id===id?{...r,active:!r.active}:r)})}
 async function toggleCategory(id:string){await store.save({...store.data,categories:categories.map(c=>c.id===id?{...c,active:!c.active}:c)})}
 const busy=store.state==='loading'||store.state==='saving';
 return <div className="admin-page"><header className="admin-header"><div><button onClick={()=>location.href='/'}><ArrowLeft size={18}/>Centre de Commandement</button><p>HospiCore · Paramétrage</p><h1>Administration</h1><span>Référentiels partagés de l’établissement · aucune donnée d’exemple préchargée.</span></div><div className="admin-header-actions"><button onClick={()=>void store.refresh()} disabled={busy}><RefreshCw size={17}/>{busy?'Synchronisation…':'Actualiser'}</button><ShieldCheck size={38}/></div></header>
 <section className={`sync-banner ${store.state==='synced'?'shared':store.state}`}><span><strong>{store.message}</strong>{store.updatedAt&&<small> · {new Date(store.updatedAt).toLocaleString('fr-FR')}</small>}</span></section>
 <section className="admin-kpis"><article><Users/><span>Collaborateurs référencés</span><strong>{activeUsers}</strong></article><article><Building2/><span>Salles référencées</span><strong>{rooms.filter(r=>r.active).length}</strong></article><article><Tag/><span>Catégories actives</span><strong>{categories.filter(c=>c.active).length}</strong></article><article><Settings/><span>Services</span><strong>{SERVICES.length}</strong></article></section>
 <nav className="admin-tabs">{([['utilisateurs','Collaborateurs',UserCog],['services','Services & rôles',ShieldCheck],['salles','Référentiel salles',Building2],['categories','Catégories',Tag]] as const).map(([key,label,Icon])=><button className={tab===key?'active':''} onClick={()=>setTab(key)} key={key}><Icon size={17}/>{label}</button>)}</nav>
 {tab==='utilisateurs'&&<section className="admin-panel"><div className="admin-panel-head"><div><h2>Référentiel collaborateurs</h2><p>Référentiel opérationnel partagé ; les comptes de connexion sont gérés par l’authentification HospiCore.</p></div><button onClick={()=>setModal('user')}><Plus size={17}/>Ajouter</button></div>{users.length===0?<div className="admin-empty">Aucun collaborateur référencé.</div>:<div className="admin-table"><div className="admin-row head"><span>Collaborateur</span><span>Rôle</span><span>Service</span><span>Poste</span><span>Statut</span></div>{users.map(u=><div className="admin-row" key={u.id}><span><strong>{u.firstName} {u.lastName}</strong><small>{u.email}</small></span><span>{u.role}</span><span>{u.department}</span><span>{u.extension||'—'}</span><span><button className={`admin-status ${u.status.toLowerCase()}`} onClick={()=>void toggleUser(u.id)}>{u.status}</button><small>{u.updatedBy} · {u.updatedAt}</small></span></div>)}</div>}</section>}
 {tab==='services'&&<section className="admin-panel"><div className="admin-panel-head"><div><h2>Services et rôles disponibles</h2><p>Périmètre HospiCore : Direction, Réception, Commercial et Maintenance.</p></div></div><div className="admin-reference-grid"><article><h3>Services</h3>{SERVICES.map(s=><span key={s}><CheckCircle2 size={15}/>{s}</span>)}</article><article><h3>Rôles</h3>{ROLES.map(r=><span key={r}><CheckCircle2 size={15}/>{r}</span>)}</article></div></section>}
 {tab==='salles'&&<section className="admin-panel"><div className="admin-panel-head"><div><h2>Référentiel salles</h2><p>Ajoutez uniquement les salles réellement utilisées par l’établissement.</p></div><button onClick={()=>setModal('room')}><Plus size={17}/>Ajouter une salle</button></div>{rooms.length===0?<div className="admin-empty">Aucune salle référencée.</div>:<div className="admin-card-grid">{rooms.map(r=><article key={r.id}><div><Building2/><span className={r.active?'enabled':'disabled'}>{r.active?'Active':'Désactivée'}</span></div><h3>{r.name}</h3><p>{r.capacity} personnes · {r.location}</p><button onClick={()=>void toggleRoom(r.id)}>{r.active?'Désactiver':'Réactiver'}</button></article>)}</div>}</section>}
 {tab==='categories'&&<section className="admin-panel"><div className="admin-panel-head"><div><h2>Catégories de consignes</h2><p>Référentiel utilisé pour les consignes générales.</p></div><button onClick={()=>setModal('category')}><Plus size={17}/>Ajouter une catégorie</button></div>{categories.length===0?<div className="admin-empty">Aucune catégorie référencée.</div>:<div className="admin-card-grid">{categories.map(c=><article key={c.id}><div><Tag/><span className={c.active?'enabled':'disabled'}>{c.active?'Active':'Désactivée'}</span></div><h3>{c.label}</h3><p>Service : {c.department}</p><button onClick={()=>void toggleCategory(c.id)}>{c.active?'Désactiver':'Réactiver'}</button></article>)}</div>}</section>}
 {modal&&<div className="admin-modal"><form onSubmit={modal==='user'?createUser:modal==='room'?createRoom:createCategory}><header><div><p>Administration</p><h2>{modal==='user'?'Nouveau collaborateur':modal==='room'?'Nouvelle salle':'Nouvelle catégorie'}</h2></div><button type="button" onClick={()=>setModal(null)}><X/></button></header>{modal==='user'&&<div className="admin-form"><label>Prénom<input name="firstName" required/></label><label>Nom<input name="lastName" required/></label><label className="wide">E-mail<input name="email" type="email" required/></label><label>Rôle<select name="role">{ROLES.map(r=><option key={r}>{r}</option>)}</select></label><label>Service<select name="department">{SERVICES.map(s=><option key={s}>{s}</option>)}</select></label><label>Poste interne<input name="extension"/></label></div>}{modal==='room'&&<div className="admin-form"><label className="wide">Nom de la salle<input name="name" required/></label><label>Capacité<input name="capacity" type="number" min="1" required/></label><label>Emplacement<input name="location" required/></label></div>}{modal==='category'&&<div className="admin-form"><label className="wide">Nom de la catégorie<input name="label" required/></label><label>Service<select name="department">{SERVICES.map(s=><option key={s}>{s}</option>)}</select></label></div>}<footer><button type="button" onClick={()=>setModal(null)}>Annuler</button><button type="submit" disabled={busy}>Enregistrer et synchroniser</button></footer></form></div>}
 </div>
}
