import { AlertTriangle, ArrowLeft, BellRing, CalendarDays, CheckCircle2, ChevronRight, ClipboardCheck, FileCheck2, FileSignature, ReceiptText, Send, UsersRound } from 'lucide-react';
import { OperationalGroupBuckets, type OperationalBooking, type OperationalGroup } from './OperationalGroupBuckets';
import { can, currentRole } from './permissions';
import { useOperationalStore } from './useOperationalStore';
import './commercial-hub.css';
import './operational-group-buckets.css';

type Audit={id:string;action:string;actor:string;role:string;at:string};
type Group=OperationalGroup&{audit?:Audit[];vegaInvoiceSentAt?:string;vegaInvoiceSentBy?:string;roomingPending?:boolean;arrivalTimePending?:boolean;departureTimePending?:boolean};
const items=[{title:'Fiches Groupe 360°',description:'Créer, compléter et valider les dossiers groupes, les prestations, les repas et les informations financières.',href:'/commercial/groupes',icon:UsersRound},{title:'Contrats groupes',description:'Créer les contrats à partir des Fiches Groupe 360°, saisir les conditions commerciales, enregistrer et imprimer le document A4.',href:'/commercial/contrats',icon:FileSignature},{title:'Fiche de fonction hebdomadaire',description:'Consulter et imprimer à volonté la synthèse opérationnelle issue des groupes validés.',href:'/commercial/planning-hebdomadaire',icon:CalendarDays}];
function sessionUser(){try{const s=JSON.parse(localStorage.getItem('hospicore.session')||'{}');const u=s.user||{};return{name:`${u.firstName||'Utilisateur'} ${u.lastName||'HospiCore'}`.trim(),role:String(u.role?.name||u.role||'Commercial')}}catch{return{name:'Utilisateur HospiCore',role:'Commercial'}}}
function stamp(){return new Date().toLocaleString('fr-FR')}
function todayIso(){const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function daysUntil(value?:string){if(!value)return 999;const start=new Date(`${todayIso()}T12:00:00`).getTime(),end=new Date(`${value}T12:00:00`).getTime();return Math.ceil((end-start)/86400000)}
function knownOrPending(value:unknown,pending?:boolean){return Boolean(String(value||'').trim())||Boolean(pending)}
function receptionMissing(group:Group){if(group.commercialValidated)return[];const missing:string[]=[];if(!(group.directAgency||group.agency)?.trim())missing.push('Agence directe');if(!group.rooming&&!group.roomingPending)missing.push('Rooming List');missing.push('Fiche 360° à valider / revalider');if(!knownOrPending(group.arrivalTime,group.arrivalTimePending))missing.push('Heure arrivée');if(!knownOrPending(group.departureTime,group.departureTimePending))missing.push('Heure départ');if(!Number(group.pax||0))missing.push('Effectif');if(!Number(group.rooms||0))missing.push('Chambres');if(!String(group.leaderPhone||'').trim())missing.push('Téléphone Tour Leader');if(!group.stayType)missing.push('Type de séjour');if(!group.paymentStatus)missing.push('Statut paiement');return missing;}
function controlSentToCommercial(group:Group){const c=group.groupControl;return group.status==='Parti'&&Boolean(c?.validatedAt)&&(c?.commercialValidation==='À valider'||c?.commercialValidation==null);}
export function CommercialHubPage(){
 const store=useOperationalStore<Group[]>('group-360',[]),meetingStore=useOperationalStore<OperationalBooking[]>('meeting-rooms',[]),user=sessionUser(),role=currentRole(),canValidate=can('commercial.validate-control',role);
 const pending=store.data.filter(controlSentToCommercial).sort((a,b)=>String(b.departure).localeCompare(String(a.departure)));
 const readyToInvoice=store.data.filter(g=>g.status==='Parti'&&g.groupControl?.commercialValidation==='Validé'&&!g.vegaInvoiceSentAt).sort((a,b)=>String(b.departure).localeCompare(String(a.departure)));
 const invoiced=store.data.filter(g=>Boolean(g.vegaInvoiceSentAt)).sort((a,b)=>String(b.vegaInvoiceSentAt).localeCompare(String(a.vegaInvoiceSentAt))).slice(0,8);
 const active=store.data.filter(g=>g.status!=='Parti'),readiness=active.map(group=>({group,missing:receptionMissing(group)})),ready=readiness.filter(i=>!i.missing.length),incomplete=readiness.filter(i=>i.missing.length).sort((a,b)=>{const da=daysUntil(a.group.arrival),db=daysUntil(b.group.arrival);return da-db||b.missing.length-a.missing.length});
 async function validate(group:Group){if(!canValidate)return;const at=stamp(),control={...group.groupControl,commercialValidation:'Validé' as const,commercialValidatedBy:user.name,commercialValidatedAt:at},audit={id:crypto.randomUUID(),action:'Contrôle Groupe validé par le Commercial · Prêt pour facturation VEGA',actor:user.name,role:user.role,at};await store.save(store.data.map(g=>g.id===group.id?{...g,groupControl:control,audit:[...(g.audit||[]),audit]}:g))}
 async function markInvoiceSent(group:Group){if(!canValidate)return;const at=stamp(),audit={id:crypto.randomUUID(),action:'Facture finale marquée comme envoyée depuis VEGA',actor:user.name,role:user.role,at};await store.save(store.data.map(g=>g.id===group.id?{...g,vegaInvoiceSentAt:at,vegaInvoiceSentBy:user.name,audit:[...(g.audit||[]),audit]}:g))}
 return <main className="commercial-hub"><header className="commercial-hub-header"><button onClick={()=>window.location.href='/'}><ArrowLeft size={18}/>Tableau de bord</button><p>HospiCore · Espace Commercial</p><h1><ClipboardCheck size={32}/>Pilotage des groupes</h1><span>Vue chronologique des groupes et suivi des actions commerciales.</span></header>
 <section className="commercial-kpi-grid"><article><span>Dossiers actifs</span><strong>{active.length}</strong><small>{ready.length} prêt(s) Réception</small></article><article className={incomplete.length?'warning':''}><span>À compléter</span><strong>{incomplete.length}</strong><small>avant transmission Réception</small></article><article className={pending.length?'warning':''} onClick={()=>document.getElementById('commercial-pending-controls')?.scrollIntoView({behavior:'smooth',block:'start'})}><span>Contrôles à valider</span><strong>{pending.length}</strong><small>après départ · contrôle Réception terminé</small></article><article className={readyToInvoice.length?'action':''}><span>À facturer VEGA</span><strong>{readyToInvoice.length}</strong><small>contrôle commercial validé</small></article></section>
 <OperationalGroupBuckets groups={store.data} bookings={meetingStore.data} context="commercial"/>
 <section className="commercial-control-notices"><header><div>{incomplete.length?<AlertTriangle size={22}/>:<CheckCircle2 size={22}/>}<div><p>Préparation avant arrivée</p><h2>Dossiers à compléter</h2></div></div><b>{ready.length}/{active.length}</b></header>{active.length===0?<div className="commercial-control-empty"><FileCheck2 size={22}/><div><strong>Aucun groupe actif</strong><span>Les dossiers en préparation apparaîtront ici automatiquement.</span></div></div>:incomplete.length===0?<div className="commercial-control-empty"><CheckCircle2 size={22}/><div><strong>Tous les dossiers actifs sont prêts</strong><span>Les fiches Groupe 360° validées ou revalidées sont considérées comme prêtes pour la Réception.</span></div></div>:<div>{incomplete.map(({group,missing})=><article key={group.id}><div><strong>{group.name||'Groupe sans nom'}</strong><span>{group.directAgency||group.agency||'Agence non renseignée'} · arrivée {group.arrival||'à confirmer'}</span><small>{missing.length} élément(s) à traiter : {missing.join(' · ')}</small></div><div><button onClick={()=>window.location.href='/commercial/groupes'}>Compléter / revalider</button></div></article>)}</div>}</section>
 {pending.length>0&&<section id="commercial-pending-controls" className="commercial-control-notices"><header><div><BellRing size={22}/><div><p>Notification Réception</p><h2>Contrôles Groupe à valider</h2></div></div><b>{pending.length}</b></header><div>{pending.map(group=><article key={group.id}><div><strong>{group.name||'Groupe sans nom'}</strong><span>{group.directAgency||group.agency||'Agence non renseignée'} · départ confirmé · {group.groupControl?.totalPax||group.pax||0} personnes</span><small>Contrôle Réception validé le {group.groupControl?.validatedAt||'—'}{group.groupControl?.printedAt?` · imprimé le ${group.groupControl.printedAt}`:''}{group.groupControl?.printedBy?` par ${group.groupControl.printedBy}`:''} · {group.groupControl?.taxableAdults||0} taxes de séjour</small></div><div><button onClick={()=>window.location.href='/reception/controles'}>Voir le contrôle</button>{canValidate?<button className="validate" onClick={()=>void validate(group)}><CheckCircle2 size={16}/>Valider le contrôle</button>:<span>Validation réservée au Commercial / Direction</span>}</div></article>)}</div></section>}
 {readyToInvoice.length>0&&<section className="commercial-control-notices"><header><div><ReceiptText size={22}/><div><p>Après validation du contrôle</p><h2>Prêts pour facturation VEGA</h2></div></div><b>{readyToInvoice.length}</b></header><div>{readyToInvoice.map(group=><article key={group.id}><div><strong>{group.name||'Groupe sans nom'}</strong><span>{group.directAgency||group.agency||'Agence non renseignée'} · départ {group.departure||'—'} · {group.groupControl?.totalPax||0} personnes</span><small>Contrôle validé le {group.groupControl?.commercialValidatedAt||'—'} par {group.groupControl?.commercialValidatedBy||'—'} · dossier prêt à être facturé dans VEGA</small></div><div>{canValidate?<button className="validate" onClick={()=>void markInvoiceSent(group)}><Send size={16}/>Facture envoyée depuis VEGA</button>:<span>Suivi réservé au Commercial / Direction</span>}</div></article>)}</div></section>}
 <section className="commercial-hub-grid">{items.map(({title,description,href,icon:Icon})=><button key={href} onClick={()=>window.location.href=href}><span className="commercial-hub-icon"><Icon size={30}/></span><div><h2>{title}</h2><p>{description}</p><strong>Ouvrir le module <ChevronRight size={17}/></strong></div></button>)}</section>{pending.length===0&&readyToInvoice.length===0&&<section className="commercial-control-empty"><FileCheck2 size={22}/><div><strong>Aucune action après départ</strong><span>Aucun contrôle n’attend de validation ou de facturation VEGA.</span></div></section>}{invoiced.length>0&&<section className="commercial-control-notices"><header><div><CheckCircle2 size={22}/><div><p>Traçabilité</p><h2>Dernières factures envoyées</h2></div></div><b>{invoiced.length}</b></header><div>{invoiced.map(group=><article key={group.id}><div><strong>{group.name||'Groupe sans nom'}</strong><span>{group.directAgency||group.agency||'Agence non renseignée'}</span><small>Facture marquée envoyée le {group.vegaInvoiceSentAt} par {group.vegaInvoiceSentBy||'—'}</small></div></article>)}</div></section>}</main>;
}
