import { FormEvent, useMemo, useState } from 'react';
import { AlertCircle, ArrowLeft, CheckCircle2, MessageSquareWarning, Plus, Search, X } from 'lucide-react';
import { useOperationalStore } from './useOperationalStore';

type Complaint={id:string;client:string;room:string;category:string;description:string;status:'Ouverte'|'Traitée';createdAt:string;createdBy:string;resolvedAt?:string;resolvedBy?:string};
const categories=['Accueil / Réception','Chambre','Propreté','Bruit','Restauration','Facturation','Équipement','Service','Autre'];
function actor(){try{const u=JSON.parse(localStorage.getItem('hospicore.session')||'{}')?.user||{};return`${u.firstName||'Utilisateur'} ${u.lastName||'HospiCore'}`.trim()}catch{return'Utilisateur HospiCore'}}
export function ComplaintsPage(){
 const store=useOperationalStore<Complaint[]>('client-complaints',[],5000),[open,setOpen]=useState(false),[query,setQuery]=useState('');
 const complaints=useMemo(()=>[...store.data].sort((a,b)=>b.createdAt.localeCompare(a.createdAt)),[store.data]);
 const filtered=complaints.filter(c=>`${c.client} ${c.room} ${c.category} ${c.description} ${c.createdBy} ${c.status}`.toLowerCase().includes(query.toLowerCase()));
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),item:Complaint={id:crypto.randomUUID(),client:String(f.get('client')||''),room:String(f.get('room')||''),category:String(f.get('category')||'Autre'),description:String(f.get('description')||''),status:'Ouverte',createdAt:new Date().toISOString(),createdBy:actor()};if(await store.save([item,...store.data]))setOpen(false)}
 async function closeComplaint(item:Complaint){if(item.status==='Traitée')return;await store.save(store.data.map(c=>c.id===item.id?{...c,status:'Traitée',resolvedAt:new Date().toISOString(),resolvedBy:actor()}:c))}
 return <main className="complaints-page"><header className="complaints-header"><div><button onClick={()=>location.href='/reception'}><ArrowLeft size={18}/>Réception</button><p>HospiCore · Réception</p><h1><MessageSquareWarning size={30}/>Plaintes clients</h1><span>Enregistrez les plaintes reçues et conservez une trace claire de leur traitement.</span></div><button className="complaints-primary" onClick={()=>setOpen(true)}><Plus size={18}/>Nouvelle plainte</button></header>
 <section className="complaints-summary"><article><AlertCircle/><div><strong>{complaints.filter(c=>c.status==='Ouverte').length}</strong><span>plaintes ouvertes</span></div></article><article><CheckCircle2/><div><strong>{complaints.filter(c=>c.status==='Traitée').length}</strong><span>plaintes traitées</span></div></article></section>
 <label className="complaints-search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher un client, une chambre, une catégorie…"/></label>
 <section className="complaints-list">{filtered.length?filtered.map(c=><article key={c.id} className={c.status==='Traitée'?'resolved':''}><header><div><strong>{c.client||'Client non renseigné'}</strong><span>{c.room?`Chambre ${c.room} · `:''}{c.category}</span></div><b>{c.status}</b></header><p>{c.description}</p><footer><span>Créée le {new Date(c.createdAt).toLocaleString('fr-FR')} par {c.createdBy}</span>{c.status==='Ouverte'?<button onClick={()=>void closeComplaint(c)}><CheckCircle2 size={16}/>Marquer traitée</button>:<small>Traitée {c.resolvedAt?`le ${new Date(c.resolvedAt).toLocaleString('fr-FR')}`:''}{c.resolvedBy?` par ${c.resolvedBy}`:''}</small>}</footer></article>):<div className="complaints-empty"><CheckCircle2 size={26}/><h2>Aucune plainte enregistrée</h2><p>Les nouvelles plaintes clients apparaîtront ici.</p></div>}</section>
 {open&&<div className="complaints-backdrop" onMouseDown={()=>setOpen(false)}><form className="complaints-modal" onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><header><div><p>Réception</p><h2>Nouvelle plainte client</h2></div><button type="button" onClick={()=>setOpen(false)}><X size={19}/></button></header><label>Client<input name="client" placeholder="Nom du client" required/></label><label>Chambre<input name="room" placeholder="N° de chambre, si applicable"/></label><label>Catégorie<select name="category" defaultValue={categories[0]}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label className="complaints-wide">Description<textarea name="description" rows={6} placeholder="Décrivez précisément la plainte, les faits rapportés et le contexte…" required/></label><footer><button type="button" className="secondary" onClick={()=>setOpen(false)}>Annuler</button><button className="complaints-primary" type="submit">Enregistrer la plainte</button></footer></form></div>}
 </main>;
}
