import { FormEvent, useMemo, useState } from 'react';
import { AlertCircle, Archive, ArrowLeft, CalendarDays, CheckCircle2, ChevronDown, ChevronRight, MessageSquareWarning, Plus, Printer, Search, X } from 'lucide-react';
import { can, currentRole } from './permissions';
import { useOperationalStore } from './useOperationalStore';
import './complaints.css';

type Complaint={id:string;client:string;room:string;category:string;description:string;status:'Ouverte'|'Traitée';createdAt:string;createdBy:string;resolvedAt?:string;resolvedBy?:string};
type ArchiveTree=Record<string,Record<string,Record<string,Complaint[]>>>;
const categories=['Accueil / Réception','Chambre','Propreté','Bruit','Restauration','Facturation','Équipement','Service','Autre'];
const MONTHS=['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août','Septembre','Octobre','Novembre','Décembre'];
function actor(){try{const u=JSON.parse(localStorage.getItem('hospicore.session')||'{}')?.user||{};return`${u.firstName||'Utilisateur'} ${u.lastName||'HospiCore'}`.trim()}catch{return'Utilisateur HospiCore'}}
function localDateKey(value?:string){const d=value?new Date(value):new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function longDate(key:string){return new Date(`${key}T12:00:00`).toLocaleDateString('fr-FR',{weekday:'long',day:'2-digit',month:'long',year:'numeric'})}
function shortTime(value:string){return new Date(value).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}
function buildArchive(items:Complaint[],today:string){return items.filter(c=>localDateKey(c.createdAt)<today).reduce<ArchiveTree>((tree,c)=>{const d=new Date(c.createdAt),year=String(d.getFullYear()),month=`${String(d.getMonth()+1).padStart(2,'0')} · ${MONTHS[d.getMonth()]}`,day=localDateKey(c.createdAt);tree[year]??={};tree[year][month]??={};tree[year][month][day]??=[];tree[year][month][day].push(c);return tree},{})}
export function ComplaintsPage(){
 const store=useOperationalStore<Complaint[]>('client-complaints',[],5000),[open,setOpen]=useState(false),[query,setQuery]=useState(''),[archivesOpen,setArchivesOpen]=useState(false),[expanded,setExpanded]=useState<Record<string,boolean>>({}),[reportDate,setReportDate]=useState(localDateKey()),canEdit=currentRole()==='night_auditor'||can('reception.operate');
 const today=localDateKey();
 const complaints=useMemo(()=>[...store.data].sort((a,b)=>b.createdAt.localeCompare(a.createdAt)),[store.data]);
 const todayComplaints=useMemo(()=>complaints.filter(c=>localDateKey(c.createdAt)===today),[complaints,today]);
 const archiveTree=useMemo(()=>buildArchive(complaints,today),[complaints,today]);
 const filtered=todayComplaints.filter(c=>`${c.client} ${c.room} ${c.category} ${c.description} ${c.createdBy} ${c.status}`.toLowerCase().includes(query.toLowerCase()));
 const reportComplaints=useMemo(()=>complaints.filter(c=>localDateKey(c.createdAt)===reportDate).sort((a,b)=>a.createdAt.localeCompare(b.createdAt)),[complaints,reportDate]);
 const reportZoom=reportComplaints.length<=6?1:Math.max(.54,Math.min(.96,6/reportComplaints.length+.18));
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!canEdit)return;const f=new FormData(e.currentTarget),item:Complaint={id:crypto.randomUUID(),client:String(f.get('client')||''),room:String(f.get('room')||''),category:String(f.get('category')||'Autre'),description:String(f.get('description')||''),status:'Ouverte',createdAt:new Date().toISOString(),createdBy:actor()};if(await store.save([item,...store.data]))setOpen(false)}
 async function closeComplaint(item:Complaint){if(!canEdit||item.status==='Traitée')return;await store.save(store.data.map(c=>c.id===item.id?{...c,status:'Traitée',resolvedAt:new Date().toISOString(),resolvedBy:actor()}:c))}
 function toggle(key:string){setExpanded(v=>({...v,[key]:!v[key]}))}
 function printReport(date=today){setReportDate(date);setTimeout(()=>window.print(),80)}
 return <main className="complaints-page"><header className="complaints-header no-print"><div><button onClick={()=>location.href='/'}><ArrowLeft size={18}/>Centre de Commandement</button><p>HospiCore · Réception</p><h1><MessageSquareWarning size={30}/>Plaintes clients</h1><span>Les plaintes du jour restent opérationnelles puis sont archivées automatiquement par date.</span></div><div className="complaints-head-actions"><button className="complaints-report-button" onClick={()=>printReport(today)} disabled={!todayComplaints.length}><Printer size={18}/>Imprimer le rapport du jour</button>{canEdit&&<button className="complaints-primary" onClick={()=>setOpen(true)}><Plus size={18}/>Nouvelle plainte</button>}</div></header>
 <section className="complaints-summary no-print"><article><AlertCircle/><div><strong>{todayComplaints.filter(c=>c.status==='Ouverte').length}</strong><span>ouvertes aujourd'hui</span></div></article><article><CheckCircle2/><div><strong>{todayComplaints.filter(c=>c.status==='Traitée').length}</strong><span>traitées aujourd'hui</span></div></article><article><Archive/><div><strong>{complaints.length-todayComplaints.length}</strong><span>plaintes archivées</span></div></article></section>
 <label className="complaints-search no-print"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher dans les plaintes du jour…"/></label>
 <section className="complaints-list no-print"><header className="complaints-day-heading"><div><CalendarDays size={18}/><div><b>Aujourd'hui</b><span>{longDate(today)}</span></div></div><strong>{todayComplaints.length} plainte(s)</strong></header>{filtered.length?filtered.map(c=><article key={c.id} className={c.status==='Traitée'?'resolved':''}><header><div><strong>{c.client||'Client non renseigné'}</strong><span>{c.room?`Chambre ${c.room} · `:''}{c.category}</span></div><b>{c.status}</b></header><p>{c.description}</p><footer><span>Créée à {shortTime(c.createdAt)} par {c.createdBy}</span>{c.status==='Ouverte'&&canEdit?<button onClick={()=>void closeComplaint(c)}><CheckCircle2 size={16}/>Marquer traitée</button>:c.status==='Traitée'?<small>Traitée {c.resolvedAt?`à ${shortTime(c.resolvedAt)}`:''}{c.resolvedBy?` par ${c.resolvedBy}`:''}</small>:null}</footer></article>):<div className="complaints-empty"><CheckCircle2 size={26}/><h2>Aucune plainte aujourd'hui</h2><p>Les nouvelles plaintes clients apparaîtront ici.</p></div>}</section>
 <section className="complaints-archives no-print"><button className="complaints-archive-toggle" onClick={()=>setArchivesOpen(v=>!v)}><div><Archive size={19}/><span><b>Archives des plaintes</b><small>Classement automatique par année, mois, date et jour</small></span></div>{archivesOpen?<ChevronDown/>:<ChevronRight/>}</button>{archivesOpen&&<div className="complaints-archive-tree">{Object.keys(archiveTree).sort().reverse().map(year=><div key={year} className="archive-level"><button onClick={()=>toggle(year)}>{expanded[year]?<ChevronDown size={17}/>:<ChevronRight size={17}/>}<b>{year}</b><span>{Object.values(archiveTree[year]).flatMap(m=>Object.values(m)).reduce((n,a)=>n+a.length,0)} plainte(s)</span></button>{expanded[year]&&Object.keys(archiveTree[year]).sort().reverse().map(month=>{const mk=`${year}-${month}`;return <div key={mk} className="archive-month"><button onClick={()=>toggle(mk)}>{expanded[mk]?<ChevronDown size={16}/>:<ChevronRight size={16}/>}<b>{month}</b></button>{expanded[mk]&&Object.keys(archiveTree[year][month]).sort().reverse().map(day=>{const dk=`${mk}-${day}`,items=archiveTree[year][month][day];return <div key={dk} className="archive-day"><button onClick={()=>toggle(dk)}>{expanded[dk]?<ChevronDown size={15}/>:<ChevronRight size={15}/>}<span>{longDate(day)}</span><b>{items.length}</b><span className="archive-day-actions" onClick={e=>e.stopPropagation()}><button onClick={()=>printReport(day)} title="Imprimer le rapport de cette journée"><Printer size={15}/></button></span></button>{expanded[dk]&&<div className="archive-day-list">{items.sort((a,b)=>a.createdAt.localeCompare(b.createdAt)).map(c=><article key={c.id}><time>{shortTime(c.createdAt)}</time><div><b>{c.client||'Client non renseigné'}{c.room?` · Ch. ${c.room}`:''}</b><span>{c.category} · {c.status}</span><p>{c.description}</p></div></article>)}</div>}</div>})}</div>})}</div>)}{!Object.keys(archiveTree).length&&<div className="complaints-archive-empty">Aucune journée archivée pour le moment.</div>}</div>}</section>
 {canEdit&&open&&<div className="complaints-backdrop no-print" onMouseDown={()=>setOpen(false)}><form className="complaints-modal" onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><header><div><p>Réception</p><h2>Nouvelle plainte client</h2></div><button type="button" onClick={()=>setOpen(false)}><X size={19}/></button></header><label>Client<input name="client" placeholder="Nom du client" required/></label><label>Chambre<input name="room" placeholder="N° de chambre, si applicable"/></label><label>Catégorie<select name="category" defaultValue={categories[0]}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label className="complaints-wide">Description<textarea name="description" rows={6} placeholder="Décrivez précisément la plainte, les faits rapportés et le contexte…" required/></label><footer><button type="button" className="secondary" onClick={()=>setOpen(false)}>Annuler</button><button className="complaints-primary" type="submit">Enregistrer la plainte</button></footer></form></div>}
 <div className="complaints-print-root"><section className="complaints-report-sheet" style={{'--report-zoom':reportZoom} as React.CSSProperties}><header><div><p>HÔTEL PARADIS · LOURDES</p><h1>RAPPORT JOURNALIER DES PLAINTES</h1><span>{longDate(reportDate)}</span></div><div className="report-total"><strong>{reportComplaints.length}</strong><span>plainte(s)</span></div></header><div className="report-kpis"><span><b>{reportComplaints.filter(c=>c.status==='Ouverte').length}</b> ouverte(s)</span><span><b>{reportComplaints.filter(c=>c.status==='Traitée').length}</b> traitée(s)</span></div><div className="report-table"><div className="report-row report-head"><span>Heure</span><span>Client / chambre</span><span>Catégorie</span><span>Plainte / traitement</span><span>Statut</span></div>{reportComplaints.map(c=><div className="report-row" key={c.id}><span>{shortTime(c.createdAt)}</span><span><b>{c.client||'—'}</b>{c.room&&<small>Ch. {c.room}</small>}</span><span>{c.category}</span><span>{c.description}<small>Signalée par {c.createdBy}{c.resolvedBy?` · Traitée par ${c.resolvedBy}`:''}</small></span><span><b>{c.status}</b>{c.resolvedAt&&<small>{shortTime(c.resolvedAt)}</small>}</span></div>)}</div><footer><span>Rapport généré par HospiCore · {new Date().toLocaleString('fr-FR')}</span><span>Hôtel Paradis · Lourdes</span></footer></section></div>
 </main>;
}
