import { useMemo, useState } from 'react';
import { BellRing, CheckCircle2, ChevronLeft, ChevronRight, CircleAlert, Clock3, CreditCard, KeyRound, LogIn, LogOut, Save, UsersRound, X } from 'lucide-react';
import { useOperationalStore } from './useOperationalStore';

type MealKey='breakfast'|'lunch'|'packedLunch'|'dinner'|'packedDinner';
type MealCell={pax?:number;time?:string};
type MealDay={date:string;breakfast?:MealCell;lunch?:MealCell;packedLunch?:MealCell;dinner?:MealCell;packedDinner?:MealCell};
type WakeUp={date:string;time:string;note?:string};
type AuditEntry={id:string;action:string;actor:string;role:string;at:string};
type DepartureChecklist={
 settlementStatus:'pending'|'paid'|'debtor';paymentMethod:string;debtorName:string;settlementAt:string;settlementBy:string;
 keysRecovered:boolean;keysRecoveredAt:string;keysRecoveredBy:string;
};
type GroupControl={validatedAt?:string;locked?:boolean;commercialValidation?:'À valider'|'Validé';[key:string]:unknown};
type Group={id:string;name?:string;pax?:number;arrival?:string;departure?:string;arrivalTime?:string;departureTime?:string;status?:string;mealDays?:MealDay[];wakeUps?:WakeUp[];audit?:AuditEntry[];departureChecklist?:DepartureChecklist;groupControl?:GroupControl};
type Booking={id:string;groupId?:string;title:string;date:string;start:string;end:string;room:string;attendees:number;updatedBy?:string;updatedAt?:string;[key:string]:unknown};
type SheetLine={groupId:string;groupStatus?:string;arrivalTime?:string;departureTime?:string;departureConfirmed?:boolean};
type Sheet={id?:string;status?:string;lockedBy?:string;lockedAt?:string;lines?:SheetLine[]};
type SessionUser={name:string;role:string;authenticated:boolean};
type Draft={group:Group;rooms:Booking[];dirty:boolean};

const emptyDeparture:DepartureChecklist={settlementStatus:'pending',paymentMethod:'',debtorName:'',settlementAt:'',settlementBy:'',keysRecovered:false,keysRecoveredAt:'',keysRecoveredBy:''};
const todayIso=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const addDays=(value:string,n:number)=>{const d=new Date(`${value}T12:00:00`);d.setDate(d.getDate()+n);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const label=(value:string)=>new Date(`${value}T12:00:00`).toLocaleDateString('fr-FR',{weekday:'long',day:'numeric',month:'long',year:'numeric'});
const clone=<T,>(value:T):T=>structuredClone(value);
function currentUser():SessionUser{try{const s=JSON.parse(localStorage.getItem('hospicore.session')||'{}');const u=s.user||{};const roleValue=u.role?.name||u.role||u.department?.name||u.department||u.service?.name||u.service||'';return{name:`${u.firstName||'Utilisateur'} ${u.lastName||'HospiCore'}`.trim(),role:String(roleValue||'Collaborateur'),authenticated:Boolean(s.token||s.accessToken||u.id||u.email||u.firstName)}}catch{return{name:'Utilisateur HospiCore',role:'Collaborateur',authenticated:false}}}
function stamp(){return new Date().toLocaleString('fr-FR')}
function receptionRole(user:SessionUser){const r=user.role.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');return user.authenticated&&(r.includes('reception')||r.includes('front')||r.includes('direction')||r.includes('directeur')||r.includes('hebergement')||r.includes('admin')||r.includes('manager')||r.includes('chef')||r.includes('responsable'))}
function serviceLabel(group:Group,date:string){const d=group.mealDays?.find(x=>x.date===date);const parts:string[]=[];if(d?.breakfast?.pax)parts.push(`PDJ ${d.breakfast.time||''}`.trim());if(d?.lunch?.pax)parts.push(`Déjeuner ${d.lunch.time||''}`.trim());if(d?.packedLunch?.pax)parts.push(`Panier midi ${d.packedLunch.time||''}`.trim());if(d?.dinner?.pax)parts.push(`Dîner ${d.dinner.time||''}`.trim());if(d?.packedDinner?.pax)parts.push(`Panier soir ${d.packedDinner.time||''}`.trim());return parts.join(' · ')||'Aucun repas prévu'}
function checklist(group:Group){return{...emptyDeparture,...group.departureChecklist}}
function departureState(group:Group){const c=checklist(group);return{settled:c.settlementStatus==='paid'||c.settlementStatus==='debtor',keys:c.keysRecovered,control:Boolean(group.groupControl?.validatedAt)}}
function departureReady(group:Group){const state=departureState(group);return state.settled&&state.keys&&state.control}

export function DailyGroupBoard({compact=false}:{compact?:boolean}){
 const groupsStore=useOperationalStore<Group[]>('group-360',[]);
 const roomsStore=useOperationalStore<Booking[]>('meeting-rooms',[]);
 const sheetsStore=useOperationalStore<Sheet[]>('function-sheets',[]);
 const [date,setDate]=useState(todayIso());
 const [draft,setDraft]=useState<Draft|null>(null);
 const [saving,setSaving]=useState(false);
 const user=currentUser();
 const today=todayIso(),past=date<today,isReception=receptionRole(user),canOperate=isReception&&!past;
 const publishedIds=useMemo(()=>new Set(sheetsStore.data.filter(s=>s.status==='Diffusée'||s.status==='Clôturée'||s.status==='Prête à imprimer').flatMap(s=>s.lines?.map(l=>l.groupId)||[])),[sheetsStore.data]);
 const visible=useMemo(()=>groupsStore.data.filter(g=>publishedIds.has(g.id)),[groupsStore.data,publishedIds]);
 const arrivals=visible.filter(g=>g.arrival===date).sort((a,b)=>(a.arrivalTime||'99:99').localeCompare(b.arrivalTime||'99:99'));
 const departures=visible.filter(g=>g.departure===date).sort((a,b)=>(a.departureTime||'99:99').localeCompare(b.departureTime||'99:99'));
 const stayovers=visible.filter(g=>String(g.arrival)<date&&String(g.departure)>date);
 const editing=draft?.group||null;

 function openDraft(group:Group){setDraft({group:clone({...group,departureChecklist:checklist(group)}),rooms:clone(roomsStore.data.filter(b=>b.groupId===group.id)),dirty:false})}
 function patchDraft(patch:Partial<Group>){setDraft(current=>current?{...current,group:{...current.group,...patch},dirty:true}:current)}
 function patchDeparture(patch:Partial<DepartureChecklist>){setDraft(current=>current?{...current,group:{...current.group,departureChecklist:{...checklist(current.group),...patch}},dirty:true}:current)}
 function chooseSettlement(status:'paid'|'debtor'){const current=checklist(editing||{} as Group);patchDeparture({settlementStatus:status,paymentMethod:status==='paid'?current.paymentMethod:'',debtorName:status==='debtor'?current.debtorName:'',settlementAt:stamp(),settlementBy:user.name})}
 function toggleKeys(value:boolean){patchDeparture({keysRecovered:value,keysRecoveredAt:value?stamp():'',keysRecoveredBy:value?user.name:''})}
 function patchMeal(dayDate:string,key:MealKey,time:string){setDraft(current=>{if(!current)return current;const mealDays=(current.group.mealDays||[]).map(day=>day.date===dayDate?{...day,[key]:{...day[key],time}}:day);return{...current,group:{...current.group,mealDays},dirty:true}})}
 function patchWake(index:number,patch:Partial<WakeUp>){setDraft(current=>{if(!current)return current;const wakeUps=[...(current.group.wakeUps||[])];wakeUps[index]={...wakeUps[index],...patch};return{...current,group:{...current.group,wakeUps},dirty:true}})}
 function addWake(){setDraft(current=>{if(!current)return current;const g=current.group;const wakeDate=date<(g.arrival||date)?g.arrival||date:date>(g.departure||date)?g.departure||date:date;return{...current,group:{...g,wakeUps:[...(g.wakeUps||[]),{date:wakeDate,time:'06:30'}]},dirty:true}})}
 function removeWake(index:number){setDraft(current=>current?{...current,group:{...current.group,wakeUps:(current.group.wakeUps||[]).filter((_,i)=>i!==index)},dirty:true}:current)}
 function patchRoom(id:string,key:'start'|'end',value:string){setDraft(current=>current?{...current,rooms:current.rooms.map(room=>room.id===id?{...room,[key]:value}:room),dirty:true}:current)}

 async function syncFunctionSheets(groupId:string,patch:Partial<SheetLine>){const next=sheetsStore.data.map(sheet=>{if(!sheet.lines?.some(line=>line.groupId===groupId))return sheet;const lines=sheet.lines.map(line=>line.groupId===groupId?{...line,...patch}:line);const allDeparted=lines.length>0&&lines.every(line=>line.groupStatus==='Parti');return{...sheet,lines,status:allDeparted?'Clôturée':sheet.status,lockedBy:allDeparted?user.name:sheet.lockedBy,lockedAt:allDeparted?stamp():sheet.lockedAt}});await sheetsStore.save(next)}
 async function persistGroup(updated:Group,action:string,sheetPatch?:Partial<SheetLine>){const audit=[...(updated.audit||[]),{id:crypto.randomUUID(),action,actor:user.name,role:user.role,at:stamp()}];const saved={...updated,audit};await groupsStore.save(groupsStore.data.map(g=>g.id===saved.id?saved:g));if(sheetPatch)await syncFunctionSheets(saved.id,sheetPatch);return saved}
 async function saveDraft(){if(!draft||!canOperate||saving)return;const c=checklist(draft.group);if(c.settlementStatus==='paid'&&!c.paymentMethod.trim())return;if(c.settlementStatus==='debtor'&&!c.debtorName.trim())return;setSaving(true);try{const saved=await persistGroup(draft.group,'Suivi opérationnel et checklist de départ mis à jour par la Réception',{arrivalTime:draft.group.arrivalTime,departureTime:draft.group.departureTime});const roomIds=new Set(draft.rooms.map(r=>r.id));const nextRooms=roomsStore.data.map(room=>roomIds.has(room.id)?{...draft.rooms.find(r=>r.id===room.id)!,updatedBy:user.name,updatedAt:new Date().toISOString()}:room);await roomsStore.save(nextRooms);setDraft({group:saved,rooms:draft.rooms,dirty:false})}finally{setSaving(false)}}
 async function setOperationalStatus(group:Group,status:'Arrivé'|'Parti'){if(!canOperate)return;if(status==='Parti'&&!departureReady(group))return;const updated=status==='Parti'?{...group,status,groupControl:{...(group.groupControl||{}),commercialValidation:'À valider' as const}}:{...group,status};const saved=await persistGroup(updated,status==='Arrivé'?'Arrivée confirmée par la Réception':'Départ confirmé par la Réception · checklist complète · contrôle envoyé au Commercial',{groupStatus:status,departureConfirmed:status==='Parti'});if(draft?.group.id===group.id)setDraft({...draft,group:saved,dirty:false})}

 const task=(done:boolean,label:string,detail?:string)=><span className={`departure-task ${done?'done':'missing'}`}>{done?<CheckCircle2 size={14}/>:<CircleAlert size={14}/>}<b>{label}</b><em>{done?'Fait':'Manquant'}</em>{detail&&<small>{detail}</small>}</span>;
 const card=(group:Group,kind:'arrival'|'departure'|'stay')=>{const state=departureState(group),c=checklist(group),ready=departureReady(group);return <article className="daily-group-card" key={`${kind}-${group.id}`}><div><strong>{group.name||'Groupe sans nom'}</strong><span><UsersRound size={14}/>{group.pax||0} pax · {serviceLabel(group,date)}</span></div><time>{kind==='arrival'?(group.arrivalTime||'À confirmer'):kind==='departure'?(group.departureTime||'À confirmer'):'En séjour'}</time>{kind==='departure'&&<div className="departure-card-checklist">{task(state.settled,c.settlementStatus==='debtor'?'Débiteur':'Solde',state.settled?(c.settlementStatus==='paid'?c.paymentMethod:c.debtorName):undefined)}{task(state.keys,'Clés récupérées')}{task(state.control,'Contrôle groupe validé')}</div>}<div className="daily-group-actions"><button onClick={()=>openDraft(group)}>Modifier le suivi</button>{kind==='arrival'&&!['Arrivé','En séjour','Parti'].includes(group.status||'')&&<button className="confirm" disabled={!canOperate} onClick={()=>void setOperationalStatus(group,'Arrivé')}><LogIn size={15}/>Mettre en arrivée</button>}{kind==='arrival'&&['Arrivé','En séjour'].includes(group.status||'')&&<span className="daily-status-confirmed">✓ Groupe arrivé</span>}{kind==='departure'&&group.status!=='Parti'&&<button className="confirm" title={ready?'Confirmer le départ':'Complétez les trois étapes obligatoires'} disabled={!canOperate||!ready} onClick={()=>void setOperationalStatus(group,'Parti')}><LogOut size={15}/>{ready?'Mettre en départ':'Départ bloqué'}</button>}{kind==='departure'&&group.status==='Parti'&&<span className="daily-status-confirmed">✓ Groupe parti</span>}</div></article>};

 return <section className={`daily-board${compact?' compact':''}`}><header><div><p>Exploitation quotidienne</p><h2>Pilotage quotidien des groupes</h2><span className="daily-role-indicator">Connecté : {user.name} · {user.role}{isReception?' · Commandes Réception actives':' · Lecture seule'}</span></div><div className="daily-date-nav"><button onClick={()=>setDate(addDays(date,-1))}><ChevronLeft/></button><strong>{label(date)}</strong><button onClick={()=>setDate(addDays(date,1))}><ChevronRight/></button><button onClick={()=>setDate(today)}>Aujourd’hui</button></div></header>{past&&<div className="daily-closed">Journée clôturée · consultation en lecture seule</div>}{!isReception&&<div className="daily-closed">Votre rôle actuel ne dispose pas des commandes Réception.</div>}<div className="daily-columns"><div><h3><LogIn/>Arrivées <b>{arrivals.length}</b></h3>{arrivals.length?arrivals.map(g=>card(g,'arrival')):<p className="daily-empty">Aucune arrivée.</p>}</div><div><h3><LogOut/>Départs <b>{departures.length}</b></h3>{departures.length?departures.map(g=>card(g,'departure')):<p className="daily-empty">Aucun départ.</p>}</div>{!compact&&<div><h3><Clock3/>En séjour <b>{stayovers.length}</b></h3>{stayovers.length?stayovers.map(g=>card(g,'stay')):<p className="daily-empty">Aucun groupe en séjour.</p>}</div>}</div>
 {editing&&draft&&(()=>{const c=checklist(editing),state=departureState(editing),ready=departureReady(editing);return <div className="daily-modal-backdrop" onMouseDown={()=>setDraft(null)}><div className="daily-modal" onMouseDown={e=>e.stopPropagation()}><header><div><p>Fiche opérationnelle Réception</p><h2>{editing.name}</h2><span>{draft.dirty?'Modifications non enregistrées':'Données à jour'}</span></div><button onClick={()=>setDraft(null)}><X/></button></header><div className="daily-modal-primary-actions">{editing.arrival===date&&!['Arrivé','En séjour','Parti'].includes(editing.status||'')&&<button className="confirm" disabled={!canOperate} onClick={()=>void setOperationalStatus(editing,'Arrivé')}><LogIn size={16}/>Mettre le groupe en arrivée</button>}{editing.departure===date&&editing.status!=='Parti'&&<button className="confirm" title={ready?'Confirmer le départ':'Checklist incomplète'} disabled={!canOperate||!ready} onClick={()=>void setOperationalStatus(editing,'Parti')}><LogOut size={16}/>{ready?'Mettre le groupe en départ':'Départ bloqué'}</button>}<button className="confirm" disabled={!canOperate||!draft.dirty||saving||(c.settlementStatus==='paid'&&!c.paymentMethod.trim())||(c.settlementStatus==='debtor'&&!c.debtorName.trim())} onClick={()=>void saveDraft()}><Save size={16}/>{saving?'Enregistrement…':'Enregistrer les modifications'}</button></div>
 <section className="departure-checklist-editor"><header><div><p>Préparation du départ</p><h3>Checklist obligatoire</h3></div><b>{[state.settled,state.keys,state.control].filter(Boolean).length}/3</b></header><div className="departure-checklist-grid"><article className={state.settled?'complete':'incomplete'}><CreditCard size={19}/><div><strong>Solde ou débiteur</strong><span>{state.settled?'Fait':'Manquant'}</span></div><div className="settlement-options"><label><input type="radio" name="settlement" disabled={!canOperate} checked={c.settlementStatus==='paid'} onChange={()=>chooseSettlement('paid')}/>Solde payé sur place</label><label><input type="radio" name="settlement" disabled={!canOperate} checked={c.settlementStatus==='debtor'} onChange={()=>chooseSettlement('debtor')}/>Débiteur</label></div>{c.settlementStatus==='paid'&&<label>Mode de paiement<input disabled={!canOperate} placeholder="CB, espèces, virement…" value={c.paymentMethod} onChange={e=>patchDeparture({paymentMethod:e.target.value})}/></label>}{c.settlementStatus==='debtor'&&<label>Nom du débiteur<input disabled={!canOperate} placeholder="Agence ou société débitrice" value={c.debtorName} onChange={e=>patchDeparture({debtorName:e.target.value})}/></label>}{state.settled&&<small>{c.settlementAt} · {c.settlementBy}</small>}</article><article className={state.keys?'complete':'incomplete'}><KeyRound size={19}/><div><strong>Clés récupérées</strong><span>{state.keys?'Fait':'Manquant'}</span></div><label className="keys-check"><input type="checkbox" disabled={!canOperate} checked={c.keysRecovered} onChange={e=>toggleKeys(e.target.checked)}/>Toutes les clés du groupe ont été récupérées</label>{state.keys&&<small>{c.keysRecoveredAt} · {c.keysRecoveredBy}</small>}</article><article className={state.control?'complete':'incomplete'}><CheckCircle2 size={19}/><div><strong>Contrôle Groupe</strong><span>{state.control?'Validé':'Manquant'}</span></div><p>{state.control?'Le contrôle des effectifs est validé.':'Ouvrez le Contrôle Groupe depuis la fiche 360° pour le compléter et le valider.'}</p></article></div></section>
 <div className="daily-edit-grid"><label>Heure d’arrivée<input disabled={!canOperate} type="time" value={editing.arrivalTime||''} onChange={e=>patchDraft({arrivalTime:e.target.value})}/></label><label>Heure de départ<input disabled={!canOperate} type="time" value={editing.departureTime||''} onChange={e=>patchDraft({departureTime:e.target.value})}/></label></div><h3>Horaires des repas</h3><div className="daily-meals">{(editing.mealDays||[]).filter(d=>d.date>=today).map(day=><div key={day.date}><strong>{new Date(`${day.date}T12:00:00`).toLocaleDateString('fr-FR',{day:'2-digit',month:'2-digit'})}</strong>{(['breakfast','lunch','packedLunch','dinner','packedDinner'] as MealKey[]).map(key=>day[key]?.pax?<label key={key}>{key==='breakfast'?'PDJ':key==='lunch'?'Déjeuner':key==='packedLunch'?'Panier midi':key==='dinner'?'Dîner':'Panier soir'}<input disabled={!canOperate} type="time" value={day[key]?.time||''} onChange={e=>patchMeal(day.date,key,e.target.value)}/></label>:null)}</div>)}</div><h3><BellRing size={17}/>Réveils pendant le séjour</h3><div className="wake-list">{(editing.wakeUps||[]).map((w,index)=><div key={`${w.date}-${index}`}><input disabled={!canOperate} type="date" min={editing.arrival} max={editing.departure} value={w.date} onChange={e=>patchWake(index,{date:e.target.value})}/><input disabled={!canOperate} type="time" value={w.time} onChange={e=>patchWake(index,{time:e.target.value})}/><button disabled={!canOperate} onClick={()=>removeWake(index)}>Supprimer</button></div>)}<button disabled={!canOperate} onClick={addWake}>+ Ajouter un réveil</button></div><h3>Salles de réunion</h3><div className="daily-room-list">{draft.rooms.sort((a,b)=>`${a.date}${a.start}`.localeCompare(`${b.date}${b.start}`)).map(room=><div key={room.id}><strong>{room.date} · {room.room}</strong><label>Début<input disabled={!canOperate} type="time" value={room.start} onChange={e=>patchRoom(room.id,'start',e.target.value)}/></label><label>Fin<input disabled={!canOperate} type="time" value={room.end} onChange={e=>patchRoom(room.id,'end',e.target.value)}/></label></div>)}</div><p className="daily-readonly-note">Les modifications sont synchronisées avec PostgreSQL après enregistrement.</p></div></div>})()}
 </section>;
}
