import { useMemo, useState } from 'react';
import { ArrowLeft, CalendarDays, ChevronDown, ChevronRight, FileText, Printer, ShieldCheck } from 'lucide-react';
import { useOperationalStore } from './useOperationalStore';

type Report={id:string;date:string;generatedAt:string;recipientIds:string[];recipientNames:string[];metrics:Record<string,number>;important:string[];tomorrow:string[];complaints:Array<{client:string;room?:string;category:string;description:string;status:string}>};
function monthName(value:string){return new Date(`${value}-01T12:00:00`).toLocaleDateString('fr-FR',{month:'long'}).replace(/^./,c=>c.toUpperCase())}
function dateLabel(value:string){return new Date(`${value}T12:00:00`).toLocaleDateString('fr-FR',{weekday:'long',day:'2-digit',month:'long',year:'numeric'})}
function esc(value:unknown){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]||c))}
function printReport(report:Report){
 const popup=window.open('','_blank','width=980,height=900');if(!popup)return;
 const metric=(key:string)=>Number(report.metrics[key]||0);
 const list=(items:string[])=>items.length?items.map(item=>`<li>${esc(item)}</li>`).join(''):'<li class="muted">Aucun élément.</li>';
 const complaints=report.complaints.length?report.complaints.map(c=>`<article class="complaint"><div class="complaint-head"><strong>${esc(c.client)}${c.room?` · Chambre ${esc(c.room)}`:''}</strong><span>${esc(c.status)}</span></div><div class="complaint-category">${esc(c.category)}</div><p>${esc(c.description)||'Aucun détail complémentaire.'}</p></article>`).join(''):'<p class="empty">Aucune plainte client enregistrée.</p>';
 popup.document.write(`<!doctype html><html lang="fr"><head><meta charset="utf-8"><title>Rapport Direction ${esc(report.date)}</title><style>
 @page{size:A4 portrait;margin:12mm 12mm 14mm}*{box-sizing:border-box}body{font-family:Arial,Helvetica,sans-serif;color:#2a2020;margin:0;background:#fff;font-size:10.5pt;line-height:1.35}.page{width:100%}.header{display:flex;justify-content:space-between;gap:20px;border-bottom:3px solid #7f1731;padding-bottom:10px;margin-bottom:14px}.brand small{display:block;letter-spacing:.12em;font-size:8pt;color:#8a7075;font-weight:700}.brand h1{font-size:22pt;margin:3px 0 2px;color:#7f1731}.brand p,.meta p{margin:2px 0}.meta{text-align:right;font-size:9pt;color:#6f5b60}.section{margin:0 0 13px;break-inside:avoid}.section h2{font-size:11.5pt;letter-spacing:.04em;text-transform:uppercase;color:#7f1731;margin:0 0 7px;padding-bottom:5px;border-bottom:1px solid #d8c8cb}.kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:7px;margin-bottom:14px}.kpi{border:1px solid #dfd2d4;border-radius:8px;padding:9px;text-align:center;background:#fbf8f6}.kpi strong{display:block;font-size:18pt;color:#7f1731;line-height:1}.kpi span{display:block;margin-top:5px;font-size:8.2pt;color:#715c61}.attention{display:grid;grid-template-columns:1fr 1fr;gap:10px}.box{border:1px solid #dfd2d4;border-radius:8px;padding:10px;break-inside:avoid}.box h3{font-size:10pt;margin:0 0 6px;color:#7f1731}.box ul{margin:0;padding-left:17px}.box li{margin:0 0 5px}.muted,.empty{color:#8b777a}.complaint{border:1px solid #dfd2d4;border-radius:8px;padding:9px;margin-bottom:7px;break-inside:avoid}.complaint-head{display:flex;justify-content:space-between;gap:12px}.complaint-head span{font-size:8pt;padding:2px 7px;border-radius:99px;background:#f2e6e9;color:#7f1731;font-weight:700}.complaint-category{font-size:8.5pt;color:#7a676b;margin-top:3px}.complaint p{margin:5px 0 0}.footer{margin-top:14px;padding-top:8px;border-top:1px solid #d8c8cb;display:flex;justify-content:space-between;font-size:7.5pt;color:#917e82}.print-note{display:none}@media print{body{-webkit-print-color-adjust:exact;print-color-adjust:exact}.page{page-break-after:auto}}@media(max-width:700px){.kpis{grid-template-columns:1fr 1fr}.attention{grid-template-columns:1fr}}
 </style></head><body><main class="page"><header class="header"><div class="brand"><small>HÔTEL PARADIS · LOURDES</small><h1>Rapport Direction</h1><p>${esc(dateLabel(report.date))}</p></div><div class="meta"><p><strong>Généré automatiquement à 20h00</strong></p><p>${esc(new Date(report.generatedAt).toLocaleString('fr-FR'))}</p><p>${report.recipientNames.length} destinataire(s) Direction</p></div></header>
 <section class="kpis"><div class="kpi"><strong>${metric('events')}</strong><span>Événements</span></div><div class="kpi"><strong>${metric('complaints')}</strong><span>Plaintes</span></div><div class="kpi"><strong>${metric('maintenanceOpen')}</strong><span>Maintenance ouverte</span></div><div class="kpi"><strong>${metric('tasksOpen')}</strong><span>Tâches ouvertes</span></div></section>
 <section class="section attention"><div class="box"><h3>Informations importantes de la journée</h3><ul>${list(report.important)}</ul></div><div class="box"><h3>Points d’attention pour demain</h3><ul>${list(report.tomorrow)}</ul></div></section>
 <section class="section"><h2>Plaintes clients du jour</h2>${complaints}</section>
 <section class="section"><h2>Indicateurs complémentaires</h2><div class="kpis"><div class="kpi"><strong>${metric('urgentMaintenance')}</strong><span>Maintenance urgente / bloquée</span></div><div class="kpi"><strong>${metric('arrivalsTomorrow')}</strong><span>Arrivées demain</span></div><div class="kpi"><strong>${metric('departuresTomorrow')}</strong><span>Départs demain</span></div><div class="kpi"><strong>${report.recipientNames.length}</strong><span>Destinataires</span></div></div></section>
 <footer class="footer"><span>Document interne · Hôtel Paradis Lourdes</span><span>HospiCore · Rapport figé du ${esc(report.date)}</span></footer></main><script>window.onload=()=>{setTimeout(()=>window.print(),180)};<\/script></body></html>`);
 popup.document.close();
}
export function DirectionReportsPage(){
 const store=useOperationalStore<Report[]>('direction-daily-reports',[],5000),[selected,setSelected]=useState<string>(''),[openYears,setOpenYears]=useState<Record<string,boolean>>({}),[openMonths,setOpenMonths]=useState<Record<string,boolean>>({});
 const reports=useMemo(()=>[...store.data].sort((a,b)=>b.date.localeCompare(a.date)),[store.data]),current=reports.find(r=>r.id===selected)||reports[0];
 const years=Array.from(new Set(reports.map(r=>r.date.slice(0,4))));
 return <main className="direction-reports-page"><header className="direction-reports-header"><div><button onClick={()=>location.href='/' }><ArrowLeft size={18}/>Centre de Commandement</button><p>HospiCore · Direction</p><h1><ShieldCheck size={30}/>Rapports journaliers Direction</h1><span>Rapport automatique généré chaque jour à 20h00 · accès réservé à la Direction.</span></div><div className="direction-report-sync">{store.message}</div></header>
 <div className="direction-reports-layout"><aside className="direction-report-archive"><header><FileText size={19}/><strong>Archives</strong><span>{reports.length}</span></header>{years.length?years.map(year=>{const yearReports=reports.filter(r=>r.date.startsWith(year)),months=Array.from(new Set(yearReports.map(r=>r.date.slice(0,7))));return <section key={year}><button className="archive-year" onClick={()=>setOpenYears(v=>({...v,[year]:!v[year]}))}>{openYears[year]?<ChevronDown/>:<ChevronRight/>}<strong>{year}</strong><span>{yearReports.length}</span></button>{openYears[year]&&months.map(month=><div className="archive-month" key={month}><button onClick={()=>setOpenMonths(v=>({...v,[month]:!v[month]}))}>{openMonths[month]?<ChevronDown/>:<ChevronRight/>}<span>{monthName(month)}</span><b>{yearReports.filter(r=>r.date.startsWith(month)).length}</b></button>{openMonths[month]&&<div>{yearReports.filter(r=>r.date.startsWith(month)).map(r=><button className={current?.id===r.id?'active':''} key={r.id} onClick={()=>setSelected(r.id)}><CalendarDays size={15}/><span>{new Date(`${r.date}T12:00:00`).toLocaleDateString('fr-FR')}</span></button>)}</div>}</div>)}</section>}):<p className="direction-report-empty">Aucun rapport archivé.</p>}</aside>
 <section className="direction-report-view">{current?<><header><div><p>Rapport du</p><h2>{dateLabel(current.date)}</h2><span>Généré le {new Date(current.generatedAt).toLocaleString('fr-FR')}</span></div><div className="direction-report-view-actions"><button type="button" onClick={()=>printReport(current)}><Printer size={17}/>Imprimer le rapport</button><div><strong>{current.recipientNames.length}</strong><span>destinataire(s) Direction</span></div></div></header><section className="direction-report-kpis"><article><strong>{current.metrics.events||0}</strong><span>événements</span></article><article><strong>{current.metrics.complaints||0}</strong><span>plaintes</span></article><article><strong>{current.metrics.maintenanceOpen||0}</strong><span>maintenance ouverte</span></article><article><strong>{current.metrics.tasksOpen||0}</strong><span>tâches ouvertes</span></article></section><section className="direction-report-block important"><h3>Informations importantes de la journée</h3>{current.important.map((item,i)=><p key={i}>{item}</p>)}</section><section className="direction-report-block tomorrow"><h3>Points d’attention pour demain</h3>{current.tomorrow.map((item,i)=><p key={i}>{item}</p>)}</section>{current.complaints.length>0&&<section className="direction-report-block complaints"><h3>Plaintes clients du jour</h3>{current.complaints.map((c,i)=><article key={i}><strong>{c.client}{c.room?` · chambre ${c.room}`:''}</strong><span>{c.category} · {c.status}</span><p>{c.description}</p></article>)}</section>}</>:<div className="direction-report-empty"><ShieldCheck size={30}/><h2>Aucun rapport disponible</h2><p>Le premier rapport sera généré automatiquement à 20h00.</p></div>}</section></div>
 </main>;
}
