import { useMemo, useState } from 'react';
import { ArrowLeft, CalendarDays, ChevronDown, ChevronRight, FileText, ShieldCheck } from 'lucide-react';
import { useOperationalStore } from './useOperationalStore';

type Report={id:string;date:string;generatedAt:string;recipientIds:string[];recipientNames:string[];metrics:Record<string,number>;important:string[];tomorrow:string[];complaints:Array<{client:string;room?:string;category:string;description:string;status:string}>};
function monthName(value:string){return new Date(`${value}-01T12:00:00`).toLocaleDateString('fr-FR',{month:'long'}).replace(/^./,c=>c.toUpperCase())}
function dateLabel(value:string){return new Date(`${value}T12:00:00`).toLocaleDateString('fr-FR',{weekday:'long',day:'2-digit',month:'long',year:'numeric'})}
export function DirectionReportsPage(){
 const store=useOperationalStore<Report[]>('direction-daily-reports',[],5000),[selected,setSelected]=useState<string>(''),[openYears,setOpenYears]=useState<Record<string,boolean>>({}),[openMonths,setOpenMonths]=useState<Record<string,boolean>>({});
 const reports=useMemo(()=>[...store.data].sort((a,b)=>b.date.localeCompare(a.date)),[store.data]),current=reports.find(r=>r.id===selected)||reports[0];
 const years=Array.from(new Set(reports.map(r=>r.date.slice(0,4))));
 return <main className="direction-reports-page"><header className="direction-reports-header"><div><button onClick={()=>location.href='/' }><ArrowLeft size={18}/>Centre de Commandement</button><p>HospiCore · Direction</p><h1><ShieldCheck size={30}/>Rapports journaliers Direction</h1><span>Rapport automatique généré chaque jour à 23h45 · accès réservé à la Direction.</span></div><div className="direction-report-sync">{store.message}</div></header>
 <div className="direction-reports-layout"><aside className="direction-report-archive"><header><FileText size={19}/><strong>Archives</strong><span>{reports.length}</span></header>{years.length?years.map(year=>{const yearReports=reports.filter(r=>r.date.startsWith(year)),months=Array.from(new Set(yearReports.map(r=>r.date.slice(0,7))));return <section key={year}><button className="archive-year" onClick={()=>setOpenYears(v=>({...v,[year]:!v[year]}))}>{openYears[year]?<ChevronDown/>:<ChevronRight/>}<strong>{year}</strong><span>{yearReports.length}</span></button>{openYears[year]&&months.map(month=><div className="archive-month" key={month}><button onClick={()=>setOpenMonths(v=>({...v,[month]:!v[month]}))}>{openMonths[month]?<ChevronDown/>:<ChevronRight/>}<span>{monthName(month)}</span><b>{yearReports.filter(r=>r.date.startsWith(month)).length}</b></button>{openMonths[month]&&<div>{yearReports.filter(r=>r.date.startsWith(month)).map(r=><button className={current?.id===r.id?'active':''} key={r.id} onClick={()=>setSelected(r.id)}><CalendarDays size={15}/><span>{new Date(`${r.date}T12:00:00`).toLocaleDateString('fr-FR')}</span></button>)}</div>}</div>)}</section>}):<p className="direction-report-empty">Aucun rapport archivé.</p>}</aside>
 <section className="direction-report-view">{current?<><header><div><p>Rapport du</p><h2>{dateLabel(current.date)}</h2><span>Généré le {new Date(current.generatedAt).toLocaleString('fr-FR')}</span></div><div><strong>{current.recipientNames.length}</strong><span>destinataire(s) Direction</span></div></header><section className="direction-report-kpis"><article><strong>{current.metrics.events||0}</strong><span>événements</span></article><article><strong>{current.metrics.complaints||0}</strong><span>plaintes</span></article><article><strong>{current.metrics.maintenanceOpen||0}</strong><span>maintenance ouverte</span></article><article><strong>{current.metrics.tasksOpen||0}</strong><span>tâches ouvertes</span></article></section><section className="direction-report-block important"><h3>Informations importantes de la journée</h3>{current.important.map((item,i)=><p key={i}>{item}</p>)}</section><section className="direction-report-block tomorrow"><h3>Points d’attention pour demain</h3>{current.tomorrow.map((item,i)=><p key={i}>{item}</p>)}</section>{current.complaints.length>0&&<section className="direction-report-block complaints"><h3>Plaintes clients du jour</h3>{current.complaints.map((c,i)=><article key={i}><strong>{c.client}{c.room?` · chambre ${c.room}`:''}</strong><span>{c.category} · {c.status}</span><p>{c.description}</p></article>)}</section>}</>:<div className="direction-report-empty"><ShieldCheck size={30}/><h2>Aucun rapport disponible</h2><p>Le premier rapport sera généré automatiquement à 23h45.</p></div>}</section></div>
 </main>;
}
