import { FormEvent, useEffect, useMemo, useState } from 'react';
import { ArrowLeft, BellRing, Check, CheckCircle2, ChevronDown, ChevronRight, Eye, Plus, RefreshCw, Search, ShieldAlert, UsersRound, X } from 'lucide-react';
import { useOperationalStore } from './useOperationalStore';

type Service='Réception'|'Commercial'|'Maintenance'|'Direction';
type DirectoryUser={id:string;firstName:string;lastName:string;role:string;roleLabel?:string;baseRole?:string;service?:Service;status?:string};
type Recipient={userId:string;name:string;service:Service};
type ReadReceipt={userId:string;name:string;service:Service;readAt:string};
type HandrailEntry={id:string;reference:string;message:string;targetServices:Service[];createdAt:string;authorId:string;authorName:string;authorRole:string;authorService:Service;directionPriority:boolean;recipients:Recipient[];readBy:ReadReceipt[]};
const SERVICES:Service[]=['Réception','Commercial','Maintenance','Direction'];
function session(){try{return JSON.parse(localStorage.getItem('hospicore.session')||'{}')}catch{return{}}}
function token(){return session()?.token||localStorage.getItem('hospicore.token')||''}
function serviceForRole(value:string):Service{const r=value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();if(r.includes('direction')||r.includes('directeur')||r.includes('admin'))return'Direction';if(r.includes('commercial')||r.includes('vente'))return'Commercial';if(r.includes('maintenance')||r.includes('tech'))return'Maintenance';return'Réception'}
function currentUser(){const u=session()?.user||{};return{id:String(u.id||''),name:`${u.firstName||'Utilisateur'} ${u.lastName||'HospiCore'}`.trim(),role:String(u.role?.name||u.role||'Collaborateur'),service:serviceForRole(String(u.role?.baseRole||u.role?.name||u.role||''))};}
async function loadDirectory():Promise<DirectoryUser[]>{try{const r=await fetch('/api/auth/directory',{headers:{Authorization:`Bearer ${token()}`}});if(!r.ok)return[];return await r.json() as DirectoryUser[]}catch{return[]}}
function readState(entry:HandrailEntry){const expected=entry.recipients.length,read=new Set(entry.readBy.map(r=>r.userId)).size;if(expected>0&&read>=expected)return{label:'Lue par tous',key:'done'};if(read>0)return{label:`Lecture en cours · ${read}/${expected}`,key:'progress'};return{label:`À lire · 0/${expected}`,key:'unread'};}

export function GeneralInstructionsPage(){
 const store=useOperationalStore<HandrailEntry[]>('general-instructions',[]),me=currentUser();
 const[open,setOpen]=useState(false),[query,setQuery]=useState(''),[directory,setDirectory]=useState<DirectoryUser[]>([]),[targets,setTargets]=useState<Service[]>([me.service]),[detailId,setDetailId]=useState<string|null>(null);
 useEffect(()=>{void loadDirectory().then(setDirectory)},[]);
 const items=useMemo(()=>store.data.filter(i=>Array.isArray(i.targetServices)&&typeof i.message==='string'),[store.data]);
 const visible=useMemo(()=>items.filter(i=>me.service==='Direction'||i.authorId===me.id||i.targetServices.includes(me.service)).filter(i=>`${i.reference} ${i.message} ${i.authorName} ${i.targetServices.join(' ')}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)),[items,me.id,me.service,query]);
 const unread=visible.filter(i=>i.recipients.some(r=>r.userId===me.id)&&!i.readBy.some(r=>r.userId===me.id)).length;
 const complete=visible.filter(i=>readState(i).key==='done').length;
 async function persist(next:HandrailEntry[]){return store.save(next)}
 function toggleTarget(service:Service){setTargets(current=>current.includes(service)?current.filter(s=>s!==service):[...current,service])}
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!targets.length)return;const f=new FormData(e.currentTarget),u=currentUser(),recipientUsers=directory.filter(d=>targets.includes((d.service||serviceForRole(d.baseRole||d.role)) as Service));const recipients:Recipient[]=recipientUsers.map(d=>({userId:d.id,name:`${d.firstName} ${d.lastName}`.trim(),service:(d.service||serviceForRole(d.baseRole||d.role)) as Service}));const entry:HandrailEntry={id:crypto.randomUUID(),reference:`MC-${new Date().getFullYear()}-${String(items.length+1).padStart(6,'0')}`,message:String(f.get('message')||'').trim(),targetServices:[...targets],createdAt:new Date().toISOString(),authorId:u.id,authorName:u.name,authorRole:u.role,authorService:u.service,directionPriority:u.service==='Direction',recipients,readBy:[]};if(await persist([entry,...items])){setOpen(false);setTargets([u.service])}}
 async function markRead(entry:HandrailEntry){if(!entry.recipients.some(r=>r.userId===me.id)||entry.readBy.some(r=>r.userId===me.id))return;const receipt:ReadReceipt={userId:me.id,name:me.name,service:me.service,readAt:new Date().toISOString()};await persist(items.map(i=>i.id===entry.id?{...i,readBy:[...(i.readBy||[]),receipt]}:i))}
 return <div className="instructions-page handrail-page"><header><div><button onClick={()=>location.href='/centre-operations'}><ArrowLeft size={18}/>Centre des opérations</button><p>HospiCore · Main courante</p><h1>Main courante interservices</h1><span>Informations générales diffusées à un ou plusieurs services, avec accusé de lecture nominatif.</span></div><button className="instructions-primary" disabled={store.rawState==='saving'} onClick={()=>setOpen(true)}><Plus size={18}/>Nouvelle information</button></header>
 <div className={`sync-banner ${store.rawState}`}><span><RefreshCw size={17}/>{store.message}</span><button onClick={()=>void store.refresh()} disabled={store.rawState==='loading'||store.rawState==='saving'}><RefreshCw size={15}/>Actualiser</button></div>
 <section className="instructions-kpis"><article><BellRing/><span>À lire pour moi</span><strong>{unread}</strong></article><article><UsersRound/><span>Informations visibles</span><strong>{visible.length}</strong></article><article><CheckCircle2/><span>Lues par tous</span><strong>{complete}</strong></article></section>
 <label className="instructions-search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher une information, un auteur ou un service…"/></label>
 <section className="handrail-list">{visible.map(entry=>{const status=readState(entry),read=entry.readBy.some(r=>r.userId===me.id),recipient=entry.recipients.some(r=>r.userId===me.id),detailOpen=detailId===entry.id;return <article key={entry.id} className={`handrail-card${entry.directionPriority?' direction-info':''}${read?' read':''}`}><header><div className="handrail-author">{entry.directionPriority?<ShieldAlert size={19}/>:<UsersRound size={19}/>}<div><strong>{entry.authorName}</strong><span>{entry.authorRole} · {new Date(entry.createdAt).toLocaleString('fr-FR')}</span></div></div><span className={`handrail-status ${status.key}`}>{status.label}</span></header><div className="handrail-services">{entry.targetServices.map(service=><span key={service}>{service}</span>)}</div><p className="handrail-message">{entry.message}</p><footer><small>{entry.reference}</small><div>{recipient&&!read&&<button className="handrail-read-button" disabled={store.rawState==='saving'} onClick={()=>void markRead(entry)}><Check size={16}/>Lu</button>}{recipient&&read&&<span className="handrail-read-confirm"><CheckCircle2 size={15}/>Vous avez lu</span>}{me.service==='Direction'&&<button className="handrail-detail-button" onClick={()=>setDetailId(detailOpen?null:entry.id)}><Eye size={16}/>Lectures {detailOpen?<ChevronDown size={15}/>:<ChevronRight size={15}/>}</button>}</div></footer>{me.service==='Direction'&&detailOpen&&<div className="handrail-readers"><h3>Suivi des lectures</h3>{entry.recipients.length?entry.recipients.map(rec=>{const receipt=entry.readBy.find(r=>r.userId===rec.userId);return <div key={rec.userId} className={receipt?'has-read':'not-read'}><span><strong>{rec.name}</strong><small>{rec.service}</small></span><b>{receipt?`Lu · ${new Date(receipt.readAt).toLocaleString('fr-FR')}`:'Non lu'}</b></div>}):<p>Aucun utilisateur actif dans les services ciblés au moment de la publication.</p>}</div>}</article>})}{!visible.length&&<div className="handrail-empty">Aucune information de main courante pour votre périmètre.</div>}</section>
 {open&&<div className="instructions-modal"><form onSubmit={e=>void create(e)}><header><div><p>Main courante</p><h2>Publier une information</h2></div><button type="button" onClick={()=>setOpen(false)}><X/></button></header><div className="handrail-compose"><label>Services destinataires</label><div className="handrail-targets">{SERVICES.map(service=><button type="button" key={service} className={targets.includes(service)?'selected':''} onClick={()=>toggleTarget(service)}>{targets.includes(service)&&<Check size={15}/>} {service}</button>)}</div><label>Information<textarea name="message" required autoFocus placeholder="Renseignez ici l'information à transmettre aux services concernés…"/></label>{me.service==='Direction'&&<div className="handrail-direction-note"><ShieldAlert size={17}/><span>Cette information sera publiée comme message Direction prioritaire, affichée en rouge et notifiera les services sélectionnés.</span></div>}</div><footer><button type="button" onClick={()=>setOpen(false)}>Annuler</button><button className="instructions-primary" disabled={!targets.length||store.rawState==='saving'} type="submit">Publier l’information</button></footer></form></div>}
 </div>;
}
