import { useEffect, useMemo, useState } from 'react';
import { createPortal } from 'react-dom';
import { FileArchive, LockKeyhole, Printer } from 'lucide-react';
import { useOperationalStore } from './useOperationalStore';

type ActualMeal={date:string;service:string;planned:number;actual:number;time:string;water:boolean;wine:boolean};
type GroupControl={single?:number;double?:number;twin?:number;triple?:number;quadruple?:number;totalRooms?:number;totalPax?:number;adults?:number;taxableAdults?:number;leaderRoom?:string;leaderPhone?:string;directAgency?:string;dmc?:string;actualMeals?:ActualMeal[];validatedBy?:string;validatedAt?:string;printedBy?:string;printedAt?:string;locked?:boolean;commercialValidation?:'À valider'|'Validé';commercialValidatedAt?:string;commercialValidatedBy?:string};
type Group={id:string;name?:string;arrival?:string;departure?:string;arrivalTime?:string;departureTime?:string;status?:string;groupControl?:GroupControl};

function esc(v:unknown){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]||c))}
function fmt(v?:string){return v?new Date(`${v}T12:00:00`).toLocaleDateString('fr-FR'):'—'}
function fold(v?:string){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim()}
function mealLabel(v:string){const x=v.toLowerCase();if(x==='breakfast')return'Petit-déjeuner';if(x==='lunch')return'Déjeuner';if(x==='packedlunch')return'Panier midi';if(x==='dinner')return'Dîner';if(x==='packeddinner')return'Panier soir';if(x==='lodging')return'Logement';return v}

function reprint(g:Group){
 const c=g.groupControl;if(!c?.validatedAt)return;
 const rooms=[['Individuelle',c.single||0],['Double',c.double||0],['Twin',c.twin||0],['Triple',c.triple||0],['Quadruple',c.quadruple||0]].filter(([,n])=>Number(n)>0).map(([l,n])=>`<tr><td>${l}</td><td>${n}</td></tr>`).join('')||'<tr><td colspan="2">Aucune chambre renseignée</td></tr>';
 const meals=(c.actualMeals||[]).map(m=>`<tr><td>${esc(fmt(m.date))}</td><td>${esc(mealLabel(m.service))}</td><td>${esc(m.time||'—')}</td><td>${m.planned}</td><td><b>${m.actual}</b></td><td>${esc([m.water&&'Eau',m.wine&&'Vin'].filter(Boolean).join(' + ')||'—')}</td></tr>`).join('')||'<tr><td colspan="6">Aucun service renseigné</td></tr>';
 const w=window.open('','_blank','noopener,noreferrer,width=900,height=1100');if(!w)return;
 w.document.open();w.document.write(`<!doctype html><html lang="fr"><head><meta charset="utf-8"><title>Contrôle Groupe - ${esc(g.name||'Groupe')}</title><style>
 @page{size:A4 portrait;margin:9mm}*{box-sizing:border-box}body{font-family:Arial,Helvetica,sans-serif;color:#26191d;font-size:9.5px;margin:0}.head{display:flex;justify-content:space-between;border-bottom:2px solid #741a31;padding-bottom:8px}.head h1{margin:3px 0;color:#741a31;font-size:21px}.muted{color:#8c747b}.archive{font-weight:700;color:#741a31}.group{margin:9px 0;padding:10px;background:#f6f0eb;display:grid;grid-template-columns:2fr 1fr 1fr;gap:8px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.box{border:1px solid #ddd0c8;padding:8px;margin-bottom:8px}.box h2{margin:0 0 6px;color:#741a31;font-size:10px;text-transform:uppercase}.totals{display:grid;grid-template-columns:repeat(4,1fr);gap:6px;margin:0 0 8px}.totals div{border:1px solid #ddd0c8;padding:8px;text-align:center}.totals b{display:block;color:#741a31;font-size:16px}table{width:100%;border-collapse:collapse}th,td{border:1px solid #ddd0c8;padding:4px}th{background:#f6f0eb;color:#741a31;text-transform:uppercase;font-size:7.5px}.footer{margin-top:10px;border-top:1px solid #cdbab3;padding-top:8px;display:grid;grid-template-columns:1fr 1fr 1fr;gap:12px}.stamp{text-align:center;color:#741a31;font-size:14px;font-weight:900;letter-spacing:.12em;margin-top:10px}@media print{body{-webkit-print-color-adjust:exact;print-color-adjust:exact}}
 </style></head><body><header class="head"><div><small class="muted">HÔTEL PARADIS · LOURDES · RÉCEPTION</small><h1>CONTRÔLE GROUPE</h1><span class="archive">ARCHIVE · LECTURE SEULE</span></div><div class="muted">Réimpression<br>${esc(new Date().toLocaleString('fr-FR'))}</div></header><section class="group"><div><small class="muted">GROUPE</small><br><strong>${esc(g.name||'Groupe sans nom')}</strong><br>${Number(c.totalPax||0)} pers. · ${Number(c.totalRooms||0)} chambres</div><div><small class="muted">ARRIVÉE</small><br><b>${esc(fmt(g.arrival))} · ${esc(g.arrivalTime||'—')}</b></div><div><small class="muted">DÉPART</small><br><b>${esc(fmt(g.departure))} · ${esc(g.departureTime||'—')}</b></div></section><div class="grid"><section class="box"><h2>Identité commerciale</h2><p><b>Agence :</b> ${esc(c.directAgency||'—')}</p><p><b>DMC :</b> ${esc(c.dmc||'—')}</p><p><b>Tour leader :</b> ${esc(c.leaderRoom||'—')} · ${esc(c.leaderPhone||'—')}</p></section><section class="box"><h2>Chambres réelles</h2><table><tbody>${rooms}</tbody></table></section></div><section class="totals"><div><span>Chambres</span><b>${Number(c.totalRooms||0)}</b></div><div><span>Personnes</span><b>${Number(c.totalPax||0)}</b></div><div><span>Adultes</span><b>${Number(c.adults||0)}</b></div><div><span>Taxes</span><b>${Number(c.taxableAdults||0)}</b></div></section><section class="box"><h2>Effectifs repas prévus / réels</h2><table><thead><tr><th>Date</th><th>Service</th><th>Heure</th><th>Prévu</th><th>Réel</th><th>Inclus</th></tr></thead><tbody>${meals}</tbody></table></section><footer class="footer"><div><small class="muted">Contrôle réalisé par</small><br><b>${esc(c.validatedBy||'—')}</b></div><div><small class="muted">Validation</small><br><b>${esc(c.validatedAt||'—')}</b></div><div><small class="muted">Première impression</small><br><b>${esc(c.printedAt||'—')}</b></div></footer><div class="stamp">BON POUR PAIEMENT</div><script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close();
}

export function GroupControlReprintArchive(){
 const store=useOperationalStore<Group[]>('group-360',[],5000),[target,setTarget]=useState<Element|null>(null);
 useEffect(()=>{
  const apply=()=>{
   const page=document.querySelector('.reception-archives-page');setTarget(page);
   document.querySelectorAll<HTMLElement>('.archive-type-folder').forEach(folder=>{
    const summary=folder.querySelector(':scope > summary');
    if(fold(summary?.textContent).includes('controles groupe'))folder.style.display='none';
   });
  };
  const frame=requestAnimationFrame(apply),timer=window.setTimeout(apply,200);return()=>{cancelAnimationFrame(frame);window.clearTimeout(timer)};
 },[store.data]);
 const archived=useMemo(()=>store.data.filter(g=>fold(g.status)==='parti'&&Boolean(g.groupControl?.validatedAt)).sort((a,b)=>(b.departure||'').localeCompare(a.departure||'')||(b.groupControl?.printedAt||b.groupControl?.validatedAt||'').localeCompare(a.groupControl?.printedAt||a.groupControl?.validatedAt||'')),[store.data]);
 if(!target||archived.length===0)return null;
 return createPortal(<section className="archive-type-folder" style={{display:'block',marginTop:18,padding:0,overflow:'hidden'}}><div style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:14,padding:'16px 18px',borderBottom:'1px solid #e6d9d2',background:'#fbf8f5'}}><div style={{display:'flex',alignItems:'center',gap:12}}><span className="archive-folder-icon"><FileArchive size={22}/></span><div><strong style={{fontSize:17}}>Contrôles Groupe archivés</strong><small style={{display:'block',marginTop:3,color:'#806a70'}}>Groupes partis · lecture seule · réimpression autorisée</small></div></div><b>{archived.length}</b></div><div className="archive-documents" style={{padding:12}}>{archived.map(g=><article key={g.id} style={{display:'grid',gridTemplateColumns:'1fr auto',alignItems:'center',gap:16,padding:'13px 14px',border:'1px solid #e4d8d1',borderRadius:10,marginBottom:8,background:'#fff'}}><div><strong style={{display:'block',fontSize:14}}>{g.name||'Groupe sans nom'}</strong><span style={{display:'block',marginTop:3,color:'#725f65',fontSize:12}}>Départ {fmt(g.departure)} {g.departureTime||''} · {Number(g.groupControl?.totalPax||0)} pers. · {Number(g.groupControl?.totalRooms||0)} chambres</span><small style={{display:'flex',alignItems:'center',gap:5,marginTop:5,color:'#8c777d'}}><LockKeyhole size={13}/>Archivé en lecture seule · validé le {g.groupControl?.validatedAt||'—'}</small></div><button type="button" onClick={()=>reprint(g)} style={{display:'inline-flex',alignItems:'center',gap:7,padding:'10px 13px',border:0,borderRadius:8,background:'#7d1730',color:'#fff',fontWeight:800,cursor:'pointer'}}><Printer size={16}/>Réimprimer</button></article>)}</div></section>,target);
}
