import { FormEvent, useMemo, useState } from 'react';
import { ArrowLeft, Bus, CalendarDays, CheckCircle2, Clock3, CreditCard, FileSpreadsheet, LockKeyhole, Plus, RefreshCw, Search, UsersRound, X } from 'lucide-react';
import { useOperationalStore } from './useOperationalStore';

type GroupStatus='Préparation'|'Confirmé'|'Arrivé'|'En séjour'|'Parti';
type PaymentStatus='Payé'|'Reste à payer';
type StayType='Logement'|'B&B'|'1/2 midi'|'1/2 Soir'|'Pension complète';
type BreakfastType='Standard'|'PDJ Chaud'|'Indiv';
type HousekeepingType='Standard'|'Prestation express';
type ServiceState='À préparer'|'En cours'|'Validé';
type MealRow='breakfast'|'lunch'|'packedLunch'|'dinner'|'packedDinner'|'lodging';
type MealCell={pax:number;time:string;water:boolean;wine:boolean};
type MealDay={date:string;breakfast:MealCell;lunch:MealCell;packedLunch:MealCell;dinner:MealCell;packedDinner:MealCell;lodging:MealCell};
type Audit={id:string;action:string;actor:string;role:string;at:string};
type Group={
 id:string;name:string;agency:string;arrival:string;departure:string;pax:number;rooms:number;status:GroupStatus;
 paymentStatus:PaymentStatus;amountDue:number;debtor:string;rooming:boolean;arrivalTime:string;departureTime:string;
 leader:string;phone:string;language:string;buses:number;parking:boolean;stayType:StayType;breakfastType:BreakfastType;
 housekeepingType:HousekeepingType;mealDays:MealDay[];commercialValidated:boolean;validatedAt:string;validatedBy:string;
 receptionState:ServiceState;restaurantState:ServiceState;housekeepingState:ServiceState;kitchenState:ServiceState;commercialState:ServiceState;
 receptionNotes:string;restaurantNotes:string;housekeepingNotes:string;kitchenNotes:string;commercialNotes:string;audit:Audit[];
};

type SessionUser={name:string;role:string};
const initial:Group[]=[];
const rowLabels:Record<MealRow,string>={breakfast:'PDJ',lunch:'Déjeuner',packedLunch:'Panier repas midi',dinner:'Dîner',packedDinner:'Panier repas soir',lodging:'Logement'};
const rows:MealRow[]=['breakfast','lunch','packedLunch','dinner','packedDinner','lodging'];
const defaultTimes:Record<MealRow,string>={breakfast:'07:30',lunch:'12:00',packedLunch:'07:00',dinner:'19:00',packedDinner:'18:00',lodging:''};

function sessionUser():SessionUser{try{const s=JSON.parse(localStorage.getItem('hospicore.session')||'{}');const u=s.user||{};const role=String(u.role?.name||u.role||'Collaborateur');return{name:`${u.firstName||'Utilisateur'} ${u.lastName||'HospiCore'}`.trim(),role}}catch{return{name:'Utilisateur HospiCore',role:'Collaborateur'}}}
function stamp(){return new Date().toLocaleString('fr-FR',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit'})}
function isoDate(d:Date){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function parseDate(value:string){const [y,m,d]=value.split('-').map(Number);return new Date(y,m-1,d)}
function dateRange(start:string,end:string){if(!start||!end)return[];const cursor=parseDate(start),last=parseDate(end),result:string[]=[];while(cursor<=last){result.push(isoDate(cursor));cursor.setDate(cursor.getDate()+1)}return result}
function cell(row:MealRow,pax=0):MealCell{return{pax,time:defaultTimes[row],water:false,wine:false}}
function buildMealDays(arrival:string,departure:string,pax:number,stayType:StayType,previous:MealDay[]=[]):MealDay[]{
 const old=new Map(previous.map(day=>[day.date,day]));
 return dateRange(arrival,departure).map((date,index,dates)=>{
  const first=index===0,last=index===dates.length-1;
  const day:MealDay={date,breakfast:cell('breakfast'),lunch:cell('lunch'),packedLunch:cell('packedLunch'),dinner:cell('dinner'),packedDinner:cell('packedDinner'),lodging:cell('lodging')};
  if(first&&!last){day.dinner.pax=pax;day.lodging.pax=pax}
  if(last){day.breakfast.pax=pax}
  if(!first&&!last){
   day.lodging.pax=pax;
   if(stayType!=='Logement')day.breakfast.pax=pax;
   if(stayType==='1/2 midi'||stayType==='Pension complète')day.lunch.pax=pax;
   if(stayType==='1/2 Soir'||stayType==='Pension complète')day.dinner.pax=pax;
  }
  const prior=old.get(date);
  if(prior) rows.forEach(row=>{day[row]={...day[row],time:prior[row]?.time||day[row].time,water:Boolean(prior[row]?.water),wine:Boolean(prior[row]?.wine)}});
  return day;
 })
}
function normalize(g:Partial<Group>&{id:string}):Group{
 const legacyPayment=String((g as unknown as {payment?:string}).payment||'');
 const paymentStatus:PaymentStatus=g.paymentStatus||(legacyPayment==='Soldé'?'Payé':'Reste à payer');
 const stayType:StayType=g.stayType||'B&B';
 return{
  id:g.id,name:g.name||'',agency:g.agency||'',arrival:g.arrival||'',departure:g.departure||'',pax:Number(g.pax||0),rooms:Number(g.rooms||0),status:g.status||'Préparation',
  paymentStatus,amountDue:Number(g.amountDue||0),debtor:g.debtor||'',rooming:Boolean(g.rooming),arrivalTime:g.arrivalTime||'',departureTime:g.departureTime||'',leader:g.leader||'',phone:g.phone||'',language:g.language||'',buses:Number(g.buses||0),parking:Boolean(g.parking),stayType,breakfastType:g.breakfastType||'Standard',housekeepingType:g.housekeepingType||'Standard',
  mealDays:Array.isArray(g.mealDays)&&g.mealDays.length?g.mealDays:buildMealDays(g.arrival||'',g.departure||'',Number(g.pax||0),stayType),commercialValidated:Boolean(g.commercialValidated),validatedAt:g.validatedAt||'',validatedBy:g.validatedBy||'',
  receptionState:g.receptionState||'À préparer',restaurantState:g.restaurantState||'À préparer',housekeepingState:g.housekeepingState||'À préparer',kitchenState:g.kitchenState||'À préparer',commercialState:g.commercialState||'En cours',receptionNotes:g.receptionNotes||'',restaurantNotes:g.restaurantNotes||'',housekeepingNotes:g.housekeepingNotes||'',kitchenNotes:g.kitchenNotes||'',commercialNotes:g.commercialNotes||'',audit:Array.isArray(g.audit)?g.audit:[]
 }
}
function rolePermissions(role:string){const r=role.toLowerCase();return{commercial:r.includes('commercial')||r.includes('admin')||r.includes('direction'),reception:r.includes('réception')||r.includes('reception')||r.includes('admin')||r.includes('direction')}}

export function GroupsPage(){
 const store=useOperationalStore<Group[]>('group-360',initial);const groups=useMemo(()=>store.data.map(normalize),[store.data]);
 const [selectedId,setSelectedId]=useState('');const [search,setSearch]=useState('');const [status,setStatus]=useState<'Tous'|GroupStatus>('Tous');const [createOpen,setCreateOpen]=useState(false);
 const selected=groups.find(g=>g.id===selectedId)||groups[0];const user=sessionUser();const permissions=rolePermissions(user.role);
 const canEditAll=permissions.commercial;const canEditTimes=permissions.commercial||permissions.reception;
 const filtered=useMemo(()=>groups.filter(g=>(status==='Tous'||g.status===status)&&`${g.name} ${g.agency} ${g.leader}`.toLowerCase().includes(search.toLowerCase())),[groups,search,status]);
 async function saveGroup(updated:Group,action:string){const next=groups.map(g=>g.id===updated.id?{...updated,audit:[...updated.audit,{id:crypto.randomUUID(),action,actor:user.name,role:user.role,at:stamp()}]}:g);await store.save(next)}
 async function patch(update:Partial<Group>,action:string){if(!selected)return;await saveGroup({...selected,...update},action)}
 async function regenerate(update:Partial<Pick<Group,'arrival'|'departure'|'pax'|'stayType'>>={}){if(!selected||!canEditAll)return;const merged={...selected,...update};await saveGroup({...merged,mealDays:buildMealDays(merged.arrival,merged.departure,merged.pax,merged.stayType,selected.mealDays)},'Planning repas recalculé automatiquement')}
 async function updateMeal(date:string,row:MealRow,update:Partial<MealCell>,action:string){if(!selected)return;const allowed=canEditAll||(canEditTimes&&Object.keys(update).every(key=>key==='time'));if(!allowed)return;const mealDays=selected.mealDays.map(day=>day.date===date?{...day,[row]:{...day[row],...update}}:day);await saveGroup({...selected,mealDays},action)}
 async function swapMeal(date:string,from:MealRow,to:MealRow){if(!selected||!canEditAll)return;const mealDays=selected.mealDays.map(day=>{if(day.date!==date)return day;return{...day,[to]:{...day[to],pax:day[from].pax,water:day[from].water,wine:day[from].wine},[from]:{...day[from],pax:0,water:false,wine:false}}});await saveGroup({...selected,mealDays},`${rowLabels[from]} converti en ${rowLabels[to]} le ${date}`)}
 async function validateCommercial(){if(!selected||!canEditAll)return;await patch({commercialValidated:true,validatedAt:stamp(),validatedBy:user.name,commercialState:'Validé'},'Fiche validée par le Commercial')}
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!canEditAll)return;const f=new FormData(e.currentTarget),pax=Number(f.get('pax')||0),stayType=String(f.get('stayType')||'B&B') as StayType,arrival=String(f.get('arrival')||''),departure=String(f.get('departure')||'');const g:Group={id:crypto.randomUUID(),name:String(f.get('name')||''),agency:String(f.get('agency')||''),arrival,departure,pax,rooms:Number(f.get('rooms')||0),status:'Préparation',paymentStatus:String(f.get('paymentStatus')||'Reste à payer') as PaymentStatus,amountDue:Number(f.get('amountDue')||0),debtor:String(f.get('debtor')||''),rooming:false,arrivalTime:String(f.get('arrivalTime')||''),departureTime:String(f.get('departureTime')||''),leader:String(f.get('leader')||''),phone:String(f.get('phone')||''),language:String(f.get('language')||''),buses:Number(f.get('buses')||0),parking:false,stayType,breakfastType:String(f.get('breakfastType')||'Standard') as BreakfastType,housekeepingType:String(f.get('housekeepingType')||'Standard') as HousekeepingType,mealDays:buildMealDays(arrival,departure,pax,stayType),commercialValidated:false,validatedAt:'',validatedBy:'',receptionState:'À préparer',restaurantState:'À préparer',housekeepingState:'À préparer',kitchenState:'À préparer',commercialState:'En cours',receptionNotes:'',restaurantNotes:'',housekeepingNotes:'',kitchenNotes:'',commercialNotes:'',audit:[{id:crypto.randomUUID(),action:'Fiche Groupe 360° créée et planning repas calculé',actor:user.name,role:user.role,at:stamp()}]};const ok=await store.save([g,...groups]);if(ok){setSelectedId(g.id);setCreateOpen(false)}}
 if(store.state==='loading'&&!groups.length)return <div className="groups-page"><p>Chargement des groupes partagés…</p></div>;
 return <div className="groups-page">
  <header className="module-header"><a className="back-link" href="/"><ArrowLeft size={18}/>Tableau de bord</a><div><p className="eyebrow">Commercial & opérations</p><h1>Fiches Groupe 360°</h1><p>Planning repas journalier, hébergement, paiement et validations interservices.</p></div>{canEditAll&&<button className="primary-button" onClick={()=>setCreateOpen(true)}><Plus size={17}/>Nouveau groupe</button>}</header>
  <div className={`sync-banner ${store.state}`}><span>{store.message}{store.updatedAt&&` · ${new Date(store.updatedAt).toLocaleString('fr-FR')}`}</span><button onClick={()=>void store.refresh()}><RefreshCw size={15}/>Actualiser</button></div>
  <section className="groups-kpis"><article><UsersRound/><div><strong>{groups.length}</strong><span>Groupes suivis</span></div></article><article><CalendarDays/><div><strong>{groups.reduce((s,g)=>s+g.pax,0)}</strong><span>Personnes</span></div></article><article><FileSpreadsheet/><div><strong>{groups.filter(g=>!g.rooming).length}</strong><span>Rooming lists manquantes</span></div></article><article><CreditCard/><div><strong>{groups.filter(g=>g.paymentStatus==='Reste à payer').length}</strong><span>Restes à payer</span></div></article></section>
  <section className="groups-toolbar"><label className="search-box"><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Rechercher un groupe…"/></label><div className="filter-chips">{(['Tous','Préparation','Confirmé','Arrivé','En séjour','Parti'] as const).map(v=><button key={v} className={`filter-chip${status===v?' active':''}`} onClick={()=>setStatus(v)}>{v}</button>)}</div></section>
  <section className="groups-layout"><div className="groups-table panel"><div className="groups-row groups-head"><span>Groupe</span><span>Séjour</span><span>Pax</span><span>Paiement</span><span>Rooming</span><span>Statut</span></div>{filtered.map(g=><button key={g.id} className={`groups-row${selected?.id===g.id?' selected':''}`} onClick={()=>setSelectedId(g.id)}><span><strong>{g.name}</strong><small>{g.agency}</small></span><span>{g.arrival}<small>→ {g.departure}</small></span><span><strong>{g.pax}</strong><small>{g.rooms} ch.</small></span><span className={`group-pill ${g.paymentStatus==='Payé'?'success':'danger'}`}>{g.paymentStatus}{g.paymentStatus==='Reste à payer'?` · ${g.amountDue.toFixed(2)} €`:''}</span><span>{g.rooming?'✅ Reçue':'❌ Manquante'}</span><span className="group-pill success">{g.status}</span></button>)}</div>
  {selected?<aside className="group-detail panel group-detail-wide"><div className="detail-heading"><div><p className="eyebrow">Fiche Groupe 360°</p><h2>{selected.name}</h2><span>{selected.agency}</span></div><span className="group-code">{selected.id.slice(0,8).toUpperCase()}</span></div>
   <div className={`commercial-lock ${selected.commercialValidated?'validated':'draft'}`}><LockKeyhole size={18}/><div><strong>{selected.commercialValidated?'Fiche validée et verrouillée':'Brouillon Commercial'}</strong><small>{selected.commercialValidated?`Validée par ${selected.validatedBy} · ${selected.validatedAt}. Seuls le Commercial et les horaires autorisés à la Réception restent modifiables.`:'La fiche doit être validée par le Commercial avant diffusion définitive.'}</small></div>{canEditAll&&!selected.commercialValidated&&<button onClick={()=>void validateCommercial()}>Valider la fiche</button>}</div>
   <div className="group-summary"><div><UsersRound/><strong>{selected.pax} pax</strong><span>{selected.rooms} chambres</span></div><div><Bus/><strong>{selected.buses} bus</strong><span>{selected.parking?'Parking réservé':'À réserver'}</span></div></div>
   <div className="group-fields"><label>Statut<select disabled={!canEditAll} value={selected.status} onChange={e=>void patch({status:e.target.value as GroupStatus},`Statut groupe : ${e.target.value}`)}><option>Préparation</option><option>Confirmé</option><option>Arrivé</option><option>En séjour</option><option>Parti</option></select></label><label>Type de séjour<select disabled={!canEditAll} value={selected.stayType} onChange={e=>void regenerate({stayType:e.target.value as StayType})}><option>Logement</option><option>B&B</option><option>1/2 midi</option><option>1/2 Soir</option><option>Pension complète</option></select></label><label>Type de PDJ<select disabled={!canEditAll} value={selected.breakfastType} onChange={e=>void patch({breakfastType:e.target.value as BreakfastType},`Type PDJ : ${e.target.value}`)}><option>Standard</option><option>PDJ Chaud</option><option>Indiv</option></select></label><label>Housekeeping<select disabled={!canEditAll} value={selected.housekeepingType} onChange={e=>void patch({housekeepingType:e.target.value as HousekeepingType},`Housekeeping : ${e.target.value}`)}><option>Standard</option><option>Prestation express</option></select></label><label>Arrivée<input disabled={!canEditTimes} type="time" value={selected.arrivalTime} onChange={e=>void patch({arrivalTime:e.target.value},'Heure d’arrivée modifiée')}/></label><label>Départ<input disabled={!canEditTimes} type="time" value={selected.departureTime} onChange={e=>void patch({departureTime:e.target.value},'Heure de départ modifiée')}/></label><label>Paiement<select disabled={!canEditAll} value={selected.paymentStatus} onChange={e=>void patch({paymentStatus:e.target.value as PaymentStatus},`Paiement : ${e.target.value}`)}><option>Payé</option><option>Reste à payer</option></select></label><label>Montant restant<input disabled={!canEditAll} type="number" min="0" step="0.01" value={selected.amountDue} onChange={e=>void patch({amountDue:Number(e.target.value)},'Montant restant modifié')}/></label><label>Débiteur<input disabled={!canEditAll} value={selected.debtor} onChange={e=>void patch({debtor:e.target.value},'Débiteur modifié')}/></label></div>
   <div className="meal-planning"><div className="meal-planning-head"><div><h3>Planning repas & logement</h3><p>Calcul automatique selon le séjour. Arrivée au dîner, départ après le petit-déjeuner.</p></div>{canEditAll&&<button onClick={()=>void regenerate()}>Recalculer</button>}</div><div className="meal-table-wrap"><table className="meal-table"><thead><tr><th>Prestation</th>{selected.mealDays.map(day=><th key={day.date}>{parseDate(day.date).toLocaleDateString('fr-FR',{weekday:'short',day:'2-digit',month:'2-digit'})}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row}><th>{rowLabels[row]}</th>{selected.mealDays.map(day=>{const value=day[row];const pair=row==='lunch'?'packedLunch':row==='packedLunch'?'lunch':row==='dinner'?'packedDinner':row==='packedDinner'?'dinner':null;return <td key={`${day.date}-${row}`} className={value.pax>0?'meal-active':''}><input aria-label={`Effectif ${rowLabels[row]} ${day.date}`} disabled={!canEditAll} type="number" min="0" value={value.pax} onChange={e=>void updateMeal(day.date,row,{pax:Number(e.target.value)},`Effectif ${rowLabels[row]} modifié le ${day.date}`)}/>{row!=='lodging'&&<><input className="meal-time" disabled={!canEditTimes} type="time" value={value.time} onChange={e=>void updateMeal(day.date,row,{time:e.target.value},`Horaire ${rowLabels[row]} modifié le ${day.date}`)}/><div className="meal-supplements"><label><input disabled={!canEditAll||value.pax===0} type="checkbox" checked={value.water} onChange={e=>void updateMeal(day.date,row,{water:e.target.checked},`Supplément eau ${e.target.checked?'ajouté':'retiré'} · ${rowLabels[row]} · ${day.date}`)}/> Eau</label><label><input disabled={!canEditAll||value.pax===0} type="checkbox" checked={value.wine} onChange={e=>void updateMeal(day.date,row,{wine:e.target.checked},`Supplément vin ${e.target.checked?'ajouté':'retiré'} · ${rowLabels[row]} · ${day.date}`)}/> Vin</label></div>{pair&&value.pax>0&&canEditAll&&<button className="meal-swap" onClick={()=>void swapMeal(day.date,row,pair)}>{pair.startsWith('packed')?'→ Panier':'→ Repas'}</button>}</>}</td>})}</tr>)}</tbody></table></div></div>
   <div className="group-contact"><h3>Tour leader</h3><strong>{selected.leader||'Non renseigné'}</strong><span>{selected.phone}</span><span>{selected.language}</span></div><details><summary>Historique signé</summary>{selected.audit.slice().reverse().map(a=><p key={a.id}><strong>{a.action}</strong><br/><small>{a.actor} · {a.role} · {a.at}</small></p>)}</details>
  </aside>:<aside className="group-detail panel"><p>Aucun groupe enregistré.</p></aside>}</section>
  {createOpen&&<div className="modal-backdrop" onMouseDown={()=>setCreateOpen(false)}><form className="modal group-create-modal" onSubmit={e=>void create(e)} onMouseDown={e=>e.stopPropagation()}><div className="modal-header"><div><p className="eyebrow">Groupe 360°</p><h2>Nouveau groupe</h2></div><button type="button" className="icon-button" onClick={()=>setCreateOpen(false)}><X size={19}/></button></div><label>Nom du groupe<input name="name" required/></label><label>Agence<input name="agency"/></label><label>Arrivée<input name="arrival" type="date" required/></label><label>Départ<input name="departure" type="date" required/></label><label>Pax<input name="pax" type="number" min="1" required/></label><label>Chambres<input name="rooms" type="number" min="1" required/></label><label>Heure d’arrivée<input name="arrivalTime" type="time"/></label><label>Heure de départ<input name="departureTime" type="time"/></label><label>Tour leader<input name="leader"/></label><label>Téléphone<input name="phone"/></label><label>Langue<input name="language"/></label><label>Bus<input name="buses" type="number" min="0" defaultValue="1"/></label><label>Type de séjour<select name="stayType"><option>Logement</option><option>B&B</option><option>1/2 midi</option><option>1/2 Soir</option><option>Pension complète</option></select></label><label>Type de PDJ<select name="breakfastType"><option>Standard</option><option>PDJ Chaud</option><option>Indiv</option></select></label><label>Housekeeping<select name="housekeepingType"><option>Standard</option><option>Prestation express</option></select></label><label>Paiement<select name="paymentStatus"><option>Payé</option><option>Reste à payer</option></select></label><label>Montant restant<input name="amountDue" type="number" min="0" step="0.01"/></label><label>Débiteur<input name="debtor"/></label><div className="modal-actions"><button type="button" className="secondary-button" onClick={()=>setCreateOpen(false)}>Annuler</button><button className="primary-button" type="submit">Créer et calculer le planning</button></div></form></div>}
 </div>;
}
