import { useEffect, useMemo, useState } from 'react';
import { createPortal } from 'react-dom';
import { Trash2 } from 'lucide-react';
import { can, currentRole } from './permissions';
import { useOperationalStore } from './useOperationalStore';

type Group={id:string;name?:string};
type FunctionLine={groupId:string;[key:string]:unknown};
type WeeklySheet={id:string;status?:string;lines?:FunctionLine[];validatedForPrintBy?:string;validatedForPrintAt?:string;lockedBy?:string;lockedAt?:string;sourceFingerprint?:string;[key:string]:unknown};
type MealOrder={id:string;sourceGroupId?:string;autoGenerated?:boolean;[key:string]:unknown};
type Booking={id:string;groupId?:string;title?:string;[key:string]:unknown};

function selectedId(groups:Group[]){const code=document.querySelector<HTMLElement>('.group-code')?.textContent?.trim().toLowerCase()||'';if(!code)return'';return groups.find(group=>group.id.toLowerCase().startsWith(code))?.id||''}

export function Group360DeleteAction(){
 const groups=useOperationalStore<Group[]>('group-360',[]),sheets=useOperationalStore<WeeklySheet[]>('function-sheets',[]),orders=useOperationalStore<MealOrder[]>('meal-orders',[]),bookings=useOperationalStore<Booking[]>('meeting-rooms',[]),[mount,setMount]=useState<HTMLElement|null>(null),role=currentRole(),allowed=can('commercial.edit',role);
 const id=selectedId(groups.data),group=useMemo(()=>groups.data.find(item=>item.id===id),[groups.data,id]);
 useEffect(()=>{
  if(!allowed||!window.location.pathname.includes('/groupes')){setMount(null);return;}
  const attach=()=>{const detail=document.querySelector<HTMLElement>('.group-detail');if(!detail){setMount(null);return;}let node=detail.querySelector<HTMLElement>(':scope > .group-delete-action-mount');if(!node){node=document.createElement('div');node.className='group-delete-action-mount';const history=detail.querySelector('details');if(history)history.after(node);else detail.appendChild(node);}setMount(node)};
  attach();const observer=new MutationObserver(attach);observer.observe(document.body,{childList:true,subtree:true});return()=>{observer.disconnect();document.querySelectorAll('.group-delete-action-mount').forEach(node=>node.remove())};
 },[allowed]);
 async function remove(){
  if(!group)return;
  const ok=window.confirm(`Supprimer définitivement la fiche Groupe 360° « ${group.name||'Sans nom'} » ?\n\nLes fiches de fonction, bons automatiques et réservations de salles liées seront également mis à jour.`);if(!ok)return;
  const gid=group.id;
  const nextSheets=sheets.data.map(sheet=>{const before=sheet.lines||[],lines=before.filter(line=>line.groupId!==gid);if(lines.length===before.length)return sheet;return{...sheet,lines,status:'Préparation',validatedForPrintBy:'',validatedForPrintAt:'',lockedBy:'',lockedAt:'',sourceFingerprint:''}});
  const nextOrders=orders.data.filter(order=>!(order.autoGenerated&&order.sourceGroupId===gid));
  const nextBookings=bookings.data.filter(booking=>booking.groupId!==gid);
  await Promise.all([sheets.save(nextSheets),orders.save(nextOrders),bookings.save(nextBookings)]);
  await groups.save(groups.data.filter(item=>item.id!==gid));
 }
 if(!mount||!group||!allowed)return null;
 return createPortal(<div className="group-delete-action"><div><strong>Suppression du dossier</strong><small>Réservé au Commercial et à la Direction. Les données liées seront nettoyées automatiquement.</small></div><button type="button" onClick={()=>void remove()}><Trash2 size={16}/>Supprimer la fiche</button></div>,mount);
}
