import { FormEvent, useEffect, useMemo, useRef, useState } from 'react';
import { Bus, CalendarDays, Contact, CreditCard, Hotel, Info, UsersRound, UtensilsCrossed, X } from 'lucide-react';
import { createPortal } from 'react-dom';
import { useOperationalStore } from './useOperationalStore';
import './group-create-experience.css';

type MealCell={pax:number;time:string;water:boolean;wine:boolean};
type MealDay={date:string;breakfast:MealCell;lunch:MealCell;packedLunch:MealCell;dinner:MealCell;packedDinner:MealCell;lodging:MealCell;pdjBox:MealCell};
type GroupRecord={id:string;[key:string]:unknown};

type StayType='Logement'|'B&B'|'1/2 midi'|'1/2 Soir'|'Pension complète';

function isoDate(date:Date){return`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`}
function parseDate(value:string){const[y,m,d]=value.split('-').map(Number);return new Date(y,m-1,d)}
function dateRange(start:string,end:string){if(!start||!end)return[];const cursor=parseDate(start),last=parseDate(end),out:string[]=[];while(cursor<=last){out.push(isoDate(cursor));cursor.setDate(cursor.getDate()+1)}return out}
function cell(time:string,pax=0):MealCell{return{pax,time,water:false,wine:false}}
function buildMealDays(arrival:string,departure:string,pax:number,stayType:StayType):MealDay[]{return dateRange(arrival,departure).map((date,index,dates)=>{const first=index===0,last=index===dates.length-1;const day:MealDay={date,breakfast:cell('07:30'),lunch:cell('12:00'),packedLunch:cell('07:00'),dinner:cell('19:00'),packedDinner:cell('18:00'),lodging:cell('',0),pdjBox:cell('06:30')};if(first&&!last){day.dinner.pax=pax;day.lodging.pax=pax}if(last)day.breakfast.pax=pax;if(!first&&!last){day.lodging.pax=pax;if(stayType!=='Logement')day.breakfast.pax=pax;if(stayType==='1/2 midi'||stayType==='Pension complète')day.lunch.pax=pax;if(stayType==='1/2 Soir'||stayType==='Pension complète')day.dinner.pax=pax}return day})}
function text(form:FormData,key:string){return String(form.get(key)||'').trim()}
function pending(value:string){return value||'À venir'}
function parseSettlement(raw:string){const value=raw.trim();if(!value)return{amountDue:0,debtor:'À venir'};const normalized=value.replace(/\s/g,'').replace(',','.');const numeric=Number(normalized);if(Number.isFinite(numeric)&&numeric>=0)return{amountDue:numeric,debtor:''};if(/taxe\s*de\s*s[eé]jour/i.test(value))return{amountDue:0,debtor:'Taxe de séjour'};if(/solde\s*total/i.test(value))return{amountDue:0,debtor:'Solde Total'};return{amountDue:0,debtor:value}}
function sessionUser(){try{const s=JSON.parse(localStorage.getItem('hospicore.session')||'{}'),u=s.user||{};return{name:`${u.firstName||'Utilisateur'} ${u.lastName||'HospiCore'}`.trim(),role:String(u.role?.name||u.role||'Commercial')}}catch{return{name:'Utilisateur HospiCore',role:'Commercial'}}}

export function GroupCreateExperience(){
 const store=useOperationalStore<GroupRecord[]>('group-360',[]),[active,setActive]=useState(false),originalForm=useRef<HTMLFormElement|null>(null),user=useMemo(sessionUser,[]);
 useEffect(()=>{const detect=()=>{const forms=Array.from(document.querySelectorAll<HTMLFormElement>('.group-create-modal'));const form=forms.find(node=>node.querySelector('h2')?.textContent?.trim()==='Nouveau groupe')||null;originalForm.current=form;if(form){form.style.display='none';setActive(true)}else setActive(false)};detect();const observer=new MutationObserver(detect);observer.observe(document.body,{childList:true,subtree:true});return()=>observer.disconnect()},[]);
 function close(){const form=originalForm.current;if(form){form.style.display='';form.querySelector<HTMLButtonElement>('.icon-button')?.click()}setActive(false)}
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget),name=text(form,'name'),directAgency=text(form,'directAgency'),arrival=text(form,'arrival'),departure=text(form,'departure'),pax=Number(form.get('pax')||0),rooms=Number(form.get('rooms')||0);if(!name||!directAgency||!arrival||!departure||pax<1||rooms<1)return;const stayType=(text(form,'stayType')||'Logement') as StayType,paymentStatus=text(form,'paymentStatus')||'Reste à payer',arrivalTime=text(form,'arrivalTime'),departureTime=text(form,'departureTime'),settlement=parseSettlement(text(form,'settlement')),debtorTyped=text(form,'debtor'),settlementDebtor=debtorTyped||settlement.debtor||'À venir',now=new Date().toLocaleString('fr-FR');const group:GroupRecord={id:crypto.randomUUID(),name,agency:directAgency,directAgency,dmc:pending(text(form,'dmc')),arrival,departure,pax,rooms,status:paymentStatus==='Payé'?'Confirmé':'Préparation',paymentStatus,amountDue:settlement.amountDue,debtor:settlementDebtor,settlementDisplay:text(form,'settlement')||'À venir',rooming:false,roomingPending:true,roomingReceivedAt:'',roomingReceivedBy:'',arrivalTime,arrivalTimePending:!arrivalTime,departureTime,departureTimePending:!departureTime,leaderFirstName:pending(text(form,'leaderFirstName')),leaderLastName:pending(text(form,'leaderLastName')),leaderPhone:pending(text(form,'leaderPhone')),leaderEmail:pending(text(form,'leaderEmail')),language:pending(text(form,'language')),buses:Number(form.get('buses')||0),parking:false,stayType,breakfastType:text(form,'breakfastType')||'Standard',housekeepingType:text(form,'housekeepingType')||'Standard',dietary:pending(text(form,'dietary')),luggageArrival:text(form,'luggageArrival')||'',luggageDeparture:text(form,'luggageDeparture')||'',mealDays:buildMealDays(arrival,departure,pax,stayType),commercialValidated:false,validatedAt:'',validatedBy:'',audit:[{id:crypto.randomUUID(),action:'Fiche Groupe 360° créée',actor:user.name,role:user.role,at:now}]};const ok=await store.save([group,...store.data]);if(ok)close()}
 if(!active)return null;
 return createPortal(<div className="group-create-v2-backdrop" onMouseDown={close}><form className="group-create-v2" onSubmit={event=>void submit(event)} onMouseDown={event=>event.stopPropagation()}>
  <header><div><p>GROUPE 360°</p><h2>Nouveau groupe</h2><span>Les informations non connues seront automatiquement enregistrées comme « À venir ».</span></div><button type="button" onClick={close} aria-label="Fermer"><X size={20}/></button></header>
  <main>
   <section className="group-create-v2-section identity"><div className="section-title"><UsersRound size={19}/><div><strong>1. Identité du groupe</strong><small>Les informations indispensables pour créer le dossier.</small></div></div><div className="fields"><label className="span-2">Nom du groupe <em>Requis</em><input name="name" required autoFocus placeholder="Ex. Pèlerinage Saint-Joseph"/></label><label className="span-2">Agence directe <em>Requis</em><input name="directAgency" required placeholder="Agence ou client direct"/></label><label>DMC <span>Optionnel</span><input name="dmc" placeholder="À venir si vide"/></label><label>Langue / Nationalité <span>Optionnel</span><input name="language" placeholder="À venir si vide"/></label></div></section>
   <section className="group-create-v2-section stay"><div className="section-title"><CalendarDays size={19}/><div><strong>2. Séjour & effectifs</strong><small>Dates, capacité et organisation du séjour.</small></div></div><div className="fields"><label>Arrivée <em>Requis</em><input name="arrival" type="date" required/></label><label>Départ <em>Requis</em><input name="departure" type="date" required/></label><label>Personnes <em>Requis</em><input name="pax" type="number" min="1" inputMode="numeric" required placeholder="0"/></label><label>Chambres <em>Requis</em><input name="rooms" type="number" min="1" inputMode="numeric" required placeholder="0"/></label><label>Heure d’arrivée <span>Optionnel</span><input name="arrivalTime" type="time"/><small>Vide = À venir</small></label><label>Heure de départ <span>Optionnel</span><input name="departureTime" type="time"/><small>Vide = À venir</small></label><label><Bus size={14}/> Bus<input name="buses" type="number" min="0" defaultValue="1"/></label><label>Type de séjour<select name="stayType" defaultValue="Logement"><option>Logement</option><option>B&B</option><option>1/2 midi</option><option>1/2 Soir</option><option>Pension complète</option></select></label></div></section>
   <section className="group-create-v2-section leader"><div className="section-title"><Contact size={19}/><div><strong>3. Tour Leader</strong><small>Laissez vide si l’information n’est pas encore connue.</small></div></div><div className="fields"><label>Prénom<input name="leaderFirstName" placeholder="À venir si vide"/></label><label>Nom<input name="leaderLastName" placeholder="À venir si vide"/></label><label>Téléphone<input name="leaderPhone" type="tel" placeholder="À venir si vide"/></label><label>E-mail<input name="leaderEmail" type="email" placeholder="À venir si vide"/></label></div></section>
   <section className="group-create-v2-section services"><div className="section-title"><UtensilsCrossed size={19}/><div><strong>4. Prestations</strong><small>Ces choix initialisent automatiquement le planning repas.</small></div></div><div className="fields"><label>Type de PDJ<select name="breakfastType"><option>Standard</option><option>PDJ Chaud</option><option>Indiv</option></select></label><label><Hotel size={14}/> Prestation chambres<select name="housekeepingType"><option>Standard</option><option>Prestation express</option></select></label><label>Bagagerie arrivée<select name="luggageArrival"><option value="">Aucune</option><option>Bagagerie 1</option><option>Bagagerie 2</option><option>Bagagerie 3</option></select></label><label>Bagagerie départ<select name="luggageDeparture"><option value="">Aucune</option><option>Bagagerie 1</option><option>Bagagerie 2</option><option>Bagagerie 3</option></select></label><label className="span-4">Régimes alimentaires & allergies <span>Optionnel</span><textarea name="dietary" placeholder="À venir si vide · Sans gluten, végétarien, allergies…"/></label></div></section>
   <section className="group-create-v2-section payment"><div className="section-title"><CreditCard size={19}/><div><strong>5. Paiement</strong><small>Le reste à régler accepte un montant ou un libellé opérationnel.</small></div></div><div className="fields"><label>Statut du paiement<select name="paymentStatus"><option>Reste à payer</option><option>Payé</option></select></label><label className="span-2">Reste à régler<input name="settlement" list="settlement-options" inputMode="decimal" placeholder="Ex. 125 · 125,50 · Taxe de séjour · Solde Total"/><datalist id="settlement-options"><option value="Taxe de séjour"/><option value="Solde Total"/></datalist><small>Montant entier ou décimal, ou sélectionnez un libellé.</small></label><label>Débiteur <span>Optionnel</span><input name="debtor" placeholder="À venir si vide"/></label></div></section>
   <aside className="group-create-v2-note"><Info size={17}/><span><strong>Gain de temps :</strong> DMC, horaires, Tour Leader, débiteur et régimes non renseignés seront automatiquement marqués « À venir ». La Rooming List est également créée en statut « À venir ».</span></aside>
  </main>
  <footer><button type="button" className="secondary" onClick={close}>Annuler</button><button type="submit" className="primary">Créer le groupe et générer le planning</button></footer>
 </form></div>,document.body)
}
