import { useEffect, useMemo, useState } from 'react';
import { createPortal } from 'react-dom';
import { BellRing, CarTaxiFront, Coffee, FileText, PackageCheck, Printer } from 'lucide-react';
import { useOperationalStore } from './useOperationalStore';

type RequestType='Taxi'|'Réveil'|'PDJ Box'|'Panier repas';
type RequestStatus='À préparer'|'Confirmée'|'Terminée';
type RequestItem={id:string;type:RequestType;guestName:string;room:string;date:string;time:string;pax:number;phone:string;destination:string;details:string;status:RequestStatus;createdAt:string;createdBy:string;updatedAt:string;completedAt?:string};
function isoToday(){const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function icon(type:RequestType){return type==='Taxi'?<CarTaxiFront size={18}/>:type==='Réveil'?<BellRing size={18}/>:type==='PDJ Box'?<Coffee size={18}/>:<PackageCheck size={18}/>}
function safe(value:string){return value.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]||c))}
function printReport(items:RequestItem[],date:string){const rows=items.sort((a,b)=>a.time.localeCompare(b.time)).map((i,index)=>`<tr><td>${index+1}</td><td><b>${safe(i.time||'—')}</b></td><td>${safe(i.type)}</td><td>${safe(i.room||'—')}</td><td>${safe(i.guestName||'Client')}</td><td>${i.pax||1}</td><td>${safe(i.destination||i.details||'—')}</td><td>${safe(i.status)}</td></tr>`).join('');const total=items.length,done=items.filter(i=>i.status==='Terminée').length;const w=window.open('','_blank','width=900,height=1100');if(!w)return;w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Rapport demandes individuelles ${date}</title><style>@page{size:A4 portrait;margin:10mm}*{box-sizing:border-box}body{font-family:Arial,sans-serif;color:#2f2326;margin:0;font-size:10px}header{border-bottom:2px solid #7b1e38;padding-bottom:8px;margin-bottom:10px;display:flex;justify-content:space-between;align-items:end}h1{font-size:20px;margin:2px 0;color:#711d34}p{margin:0;color:#756168}.summary{display:flex;gap:8px;margin-bottom:10px}.summary span{border:1px solid #e2d8cf;border-radius:8px;padding:6px 9px;background:#faf7f3}table{width:100%;border-collapse:collapse;table-layout:fixed}th{background:#711d34;color:#fff;text-align:left;padding:5px 4px;font-size:8px}td{border-bottom:1px solid #e8dfd7;padding:5px 4px;vertical-align:top;overflow-wrap:anywhere}th:nth-child(1),td:nth-child(1){width:4%}th:nth-child(2),td:nth-child(2){width:8%}th:nth-child(3),td:nth-child(3){width:12%}th:nth-child(4),td:nth-child(4){width:7%}th:nth-child(5),td:nth-child(5){width:16%}th:nth-child(6),td:nth-child(6){width:5%}th:nth-child(7),td:nth-child(7){width:34%}th:nth-child(8),td:nth-child(8){width:14%}footer{margin-top:8px;text-align:right;color:#8d797f;font-size:8px}@media print{body{zoom:${total>24?'.72':total>18?'.82':total>12?'.9':'1'}}}</style></head><body><header><div><p>HÔTEL PARADIS · LOURDES</p><h1>Rapport des demandes clients individuels</h1><p>${new Date(`${date}T12:00:00`).toLocaleDateString('fr-FR',{weekday:'long',day:'2-digit',month:'long',year:'numeric'})}</p></div><b>HospiCore</b></header><div class="summary"><span><b>${total}</b> demande(s)</span><span><b>${done}</b> terminée(s)</span><span><b>${total-done}</b> en cours</span></div><table><thead><tr><th>#</th><th>Heure</th><th>Type</th><th>Ch.</th><th>Client</th><th>Pax</th><th>Destination / consigne</th><th>Statut</th></tr></thead><tbody>${rows||'<tr><td colspan="8">Aucune demande enregistrée.</td></tr>'}</tbody></table><footer>Rapport édité depuis HospiCore · ${new Date().toLocaleString('fr-FR')}</footer><script>window.onload=()=>{window.print()}</script></body></html>`);w.document.close()}
export function IndividualRequestsCommandDashboard(){
 const store=useOperationalStore<RequestItem[]>('individual-requests',[]),[target,setTarget]=useState<HTMLElement|null>(null),[open,setOpen]=useState(false),today=isoToday();
 useEffect(()=>{const locate=()=>setTarget(document.querySelector<HTMLElement>('.command-content'));locate();const observer=new MutationObserver(locate);observer.observe(document.body,{childList:true,subtree:true});return()=>observer.disconnect()},[]);
 const day=useMemo(()=>store.data.filter(i=>i.date===today).sort((a,b)=>a.time.localeCompare(b.time)),[store.data,today]);const active=day.filter(i=>i.status!=='Terminée');const preparing=active.filter(i=>i.status==='À préparer').length,confirmed=active.filter(i=>i.status==='Confirmée').length;
 if(!target||window.location.pathname!=='/')return null;
 return createPortal(<section className={`ir-command-dashboard${open?' open':''}`}><button className="ir-command-summary" onClick={()=>setOpen(v=>!v)}><span className="ir-command-icon"><BellRing size={20}/></span><div><small>RÉCEPTION · DEMANDES CLIENTS</small><strong>Demandes individuelles du jour</strong><p>{active.length} active(s) · {preparing} à préparer · {confirmed} confirmée(s)</p></div><b>{active.length}</b><span className="ir-command-toggle">{open?'Réduire':'Déplier'}</span></button>{open&&<div className="ir-command-body"><header><div><h3>Suivi de la journée</h3><span>Classé chronologiquement par heure demandée.</span></div><div><button onClick={()=>printReport(day,today)}><Printer size={16}/>Rapport du jour</button><button onClick={()=>location.href='/reception/demandes-individuelles'}><FileText size={16}/>Ouvrir</button></div></header>{active.length?<div className="ir-command-list">{active.map(i=><article key={i.id}><span className="ir-command-type">{icon(i.type)}</span><time>{i.time||'—'}</time><div><strong>{i.type} · Chambre {i.room||'—'}</strong><span>{i.guestName||'Client'} · {i.pax||1} pers.</span>{(i.destination||i.details)&&<small>{i.destination||i.details}</small>}</div><b className={i.status==='À préparer'?'prepare':'confirmed'}>{i.status}</b></article>)}</div>:<p className="ir-command-empty">Aucune demande individuelle active pour aujourd’hui.</p>}</div>}</section>,target)
}
