import React from 'react';
import ReactDOM from 'react-dom/client';
import { AppRouter } from './AppRouter';
import { OperationalToastHost } from './OperationalToastHost';
import { UserAccountMenu } from './UserAccountMenu';
import { DirectionCashUnlockBridge } from './DirectionCashUnlockBridge';
import { CashValidatedBannerScopeBridge } from './CashValidatedBannerScopeBridge';
import { ComplaintsPrintBridge } from './ComplaintsPrintBridge';
import { OperationalPrintRecovery } from './OperationalPrintRecovery';
import { cleanupLegacyLocalData } from './legacy-cleanup';
import './styles.css';
import './auth.css';
import './meeting-rooms.css';
import './general-instructions.css';
import './tasks.css';
import './reception-group-control.css';
import './reception-hub.css';
import './reception-night.css';
import './reception-workspace.css';
import './reception-archives-tree.css';
import './complaints.css';
import './direction-reports.css';
import './user-account-menu.css';
import './hospicore-live.css';
import './core-dashboard.css';
import './control-matrix.css';

cleanupLegacyLocalData();
const path=window.location.pathname,cashRoute=path.startsWith('/reception/caisse'),complaintsRoute=path.startsWith('/reception/plaintes'),nightRoute=path.startsWith('/reception/feuille-route-veilleur');
function RouteScopedBridges(){return <><OperationalToastHost/><UserAccountMenu/>{cashRoute&&<><DirectionCashUnlockBridge/><CashValidatedBannerScopeBridge/><OperationalPrintRecovery/></>}{complaintsRoute&&<ComplaintsPrintBridge/>}{(nightRoute||complaintsRoute)&&<OperationalPrintRecovery/>}</>}
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><AppRouter/><RouteScopedBridges/></React.StrictMode>);
