import { FormEvent, useMemo, useState } from 'react';
import { ArrowLeft, CheckCircle2, Coffee, PackageCheck, Plus, Printer, RefreshCw, Trash2, UtensilsCrossed, X } from 'lucide-react';
import { can } from './permissions';
import { useOperationalStore } from './useOperationalStore';
import './meal-orders.css';

type OrderType='PDJ Box'|'Panier déjeuner'|'Panier dîner';
type OrderStatus='À préparer'|'Préparé'|'Remis';
type MealOrder={id:string;type:OrderType;date:string;pickupTime:string;quantity:number;recipient:string;room:string;destination:string;contact:string;allergies:string;composition:string;notes:string;status:OrderStatus;createdAt:string;createdBy:string;updatedAt?:string;updatedBy?:string;printedAt?:string;printedBy?:string};
const EMPTY:MealOrder[]=[];
function iso(){const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function actor(){try{const u=JSON.parse(localStorage.getItem('hospicore.session')||'{}').user||{};return`${u.firstName||'Utilisateur'} ${u.lastName||'HospiCore'}`.trim()}catch{return'Utilisateur HospiCore'}}
function blank(date=iso()):MealOrder{return{id:'',type:'PDJ Box',date,pickupTime:'06:30',quantity:1,recipient:'',room:'',destination:'',contact:'',allergies:'',composition:'',notes:'',status:'À préparer',createdAt:new Date().toISOString(),createdBy:actor()}}
function icon(type:OrderType){return type==='PDJ Box'?Coffee:type==='Panier déjeuner'?PackageCheck:UtensilsCrossed}
function chunks<T>(items:T[],size:number){const result:T[][]=[];for(let i=0;i<items.length;i+=size)result.push(items.slice(i,i+size));return result}

export function MealOrdersPage(){
 const store=useOperationalStore<MealOrder[]>('meal-orders',EMPTY),[date,setDate]=useState(iso()),[selected,setSelected]=useState<MealOrder|null>(null),[printIds,setPrintIds]=useState<string[]>([]),[removingIds,setRemovingIds]=useState<string[]>([]),[deletingId,setDeletingId]=useState<string|null>(null);
 const visibleData=useMemo(()=>store.data.filter(o=>!removingIds.includes(o.id)),[store.data,removingIds]);
 const orders=useMemo(()=>visibleData.filter(o=>o.date===date).sort((a,b)=>a.pickupTime.localeCompare(b.pickupTime)||a.type.localeCompare(b.type,'fr')),[visibleData,date]),printOrders=useMemo(()=>{const chosen=visibleData.filter(o=>printIds.includes(o.id));return chosen.length?chosen:orders},[visibleData,printIds,orders]);
 const busy=store.state==='loading'||store.state==='saving',canEdit=can('reception.operate');
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selected||!canEdit)return;const f=new FormData(e.currentTarget),now=new Date().toISOString(),value:MealOrder={...selected,id:selected.id||crypto.randomUUID(),type:String(f.get('type')) as OrderType,date:String(f.get('date')),pickupTime:String(f.get('pickupTime')),quantity:Number(f.get('quantity')||1),recipient:String(f.get('recipient')||''),room:String(f.get('room')||''),destination:String(f.get('destination')||''),contact:String(f.get('contact')||''),allergies:String(f.get('allergies')||''),composition:String(f.get('composition')||''),notes:String(f.get('notes')||''),status:String(f.get('status')) as OrderStatus,createdAt:selected.id?selected.createdAt:now,createdBy:selected.id?selected.createdBy:actor(),updatedAt:now,updatedBy:actor()};const next=selected.id?store.data.map(o=>o.id===selected.id?value:o):[...store.data,value];if(await store.save(next)){setSelected(null);setDate(value.date)}}
 async function remove(order:MealOrder){
  if(!canEdit||deletingId||!confirm(`Supprimer le bon ${order.type} pour ${order.recipient||'ce client'} ?`))return;
  const id=order.id;
  const next=store.data.filter(o=>o.id!==id);
  setDeletingId(id);
  setRemovingIds(ids=>ids.includes(id)?ids:[...ids,id]);
  setPrintIds(ids=>ids.filter(x=>x!==id));
  if(selected?.id===id)setSelected(null);
  try{
   const saved=await store.save(next);
   if(!saved){setRemovingIds(ids=>ids.filter(x=>x!==id));await store.refresh()}
   else setRemovingIds(ids=>ids.filter(x=>x!==id));
  }catch{
   setRemovingIds(ids=>ids.filter(x=>x!==id));
   await store.refresh();
  }finally{setDeletingId(null)}
 }
 async function print(){const now=new Date().toISOString(),by=actor(),ids=new Set(printOrders.map(o=>o.id));if(ids.size){await store.save(store.data.map(o=>ids.has(o.id)?{...o,printedAt:now,printedBy:by}:o));setTimeout(()=>window.print(),120)}else window.print()}
 function togglePrint(id:string){setPrintIds(ids=>ids.includes(id)?ids.filter(x=>x!==id):[...ids,id])}
 return <div className="meal-orders-page"><header className="meal-screen-header no-print"><button onClick={()=>location.href='/reception'}><ArrowLeft size={18}/>Réception</button><div><p>HospiCore · Réception</p><h1>Paniers repas & PDJ Box</h1><span>Création et impression des bons de commande à transmettre pour préparation.</span></div><div className="meal-head-actions"><input type="date" value={date} onChange={e=>{setDate(e.target.value);setPrintIds([])}}/><button onClick={()=>void store.refresh()} disabled={busy}><RefreshCw size={16}/>Actualiser</button>{canEdit&&<button onClick={()=>setSelected(blank(date))} disabled={busy||Boolean(deletingId)}><Plus size={16}/>Nouveau bon</button>}<button className="primary" onClick={()=>void print()} disabled={!printOrders.length||Boolean(deletingId)}><Printer size={16}/>Imprimer {printIds.length?`${printIds.length} bon(s)`:'la journée'}</button></div></header>
 <main className="meal-workspace no-print"><section className="meal-kpis"><article><Coffee/><span>PDJ Box</span><strong>{orders.filter(o=>o.type==='PDJ Box').reduce((n,o)=>n+o.quantity,0)}</strong></article><article><PackageCheck/><span>Paniers déjeuner</span><strong>{orders.filter(o=>o.type==='Panier déjeuner').reduce((n,o)=>n+o.quantity,0)}</strong></article><article><UtensilsCrossed/><span>Paniers dîner</span><strong>{orders.filter(o=>o.type==='Panier dîner').reduce((n,o)=>n+o.quantity,0)}</strong></article><article><CheckCircle2/><span>À préparer</span><strong>{orders.filter(o=>o.status==='À préparer').length}</strong></article></section>
 <section className="meal-list"><header><div><h2>Bons du {new Date(`${date}T12:00:00`).toLocaleDateString('fr-FR',{weekday:'long',day:'2-digit',month:'long',year:'numeric'})}</h2><p>Cochez les bons à imprimer. Sans sélection, tous les bons de la journée sont imprimés.</p></div><b>{orders.length}</b></header>{orders.length===0?<div className="meal-empty">Aucun bon de commande pour cette date.</div>:orders.map(o=>{const Icon=icon(o.type),isDeleting=deletingId===o.id;return <article key={o.id} aria-busy={isDeleting}><label className="meal-select"><input type="checkbox" checked={printIds.includes(o.id)} onChange={()=>togglePrint(o.id)} disabled={Boolean(deletingId)}/></label><Icon size={21}/><time>{o.pickupTime}</time><div className="meal-order-main"><strong>{o.type} · {o.quantity} unité(s)</strong><span>{o.recipient||'Client non précisé'}{o.room?` · Chambre ${o.room}`:''}{o.destination?` · ${o.destination}`:''}</span>{o.allergies&&<small>⚠ Allergies / régime : {o.allergies}</small>}</div><b className={`meal-status ${o.status.replaceAll(' ','-').toLowerCase()}`}>{o.status}</b>{canEdit&&<><button onClick={()=>setSelected(o)} disabled={Boolean(deletingId)}>Modifier</button><button className="delete" disabled={Boolean(deletingId)} onClick={()=>void remove(o)} aria-label={`Supprimer ${o.type}`}>{isDeleting?'…':<Trash2 size={16}/>}</button></>}</article>})}</section></main>
 {selected&&<div className="meal-modal no-print" onMouseDown={()=>setSelected(null)}><form onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><header><div><p>Bon de commande</p><h2>{selected.id?'Modifier le bon':'Nouveau bon'}</h2></div><button type="button" onClick={()=>setSelected(null)}><X/></button></header><div className="meal-form"><label>Type<select name="type" defaultValue={selected.type}><option>PDJ Box</option><option>Panier déjeuner</option><option>Panier dîner</option></select></label><label>Date<input name="date" type="date" defaultValue={selected.date} required/></label><label>Heure de remise<input name="pickupTime" type="time" defaultValue={selected.pickupTime} required/></label><label>Quantité<input name="quantity" type="number" min="1" defaultValue={selected.quantity} required/></label><label>Client / Groupe<input name="recipient" defaultValue={selected.recipient} required/></label><label>Chambre<input name="room" defaultValue={selected.room}/></label><label>Destination / lieu de remise<input name="destination" defaultValue={selected.destination} placeholder="Bus, réception, chambre, excursion…"/></label><label>Contact / téléphone<input name="contact" defaultValue={selected.contact}/></label><label>Statut<select name="status" defaultValue={selected.status}><option>À préparer</option><option>Préparé</option><option>Remis</option></select></label><label className="wide">Allergies / régimes alimentaires<textarea name="allergies" defaultValue={selected.allergies} placeholder="Sans gluten, végétarien, allergies…"/></label><label className="wide">Composition / contenu demandé<textarea name="composition" defaultValue={selected.composition} placeholder="Contenu du panier ou de la box, boissons, quantités particulières…"/></label><label className="wide">Consignes complémentaires<textarea name="notes" defaultValue={selected.notes} placeholder="Informations de préparation ou de remise…"/></label></div><footer><button type="button" onClick={()=>setSelected(null)}>Annuler</button><button className="primary" type="submit">Enregistrer le bon</button></footer></form></div>}
 <div className="meal-print-root">{chunks(printOrders,2).map((pair,page)=><section className="meal-print-page" key={page}>{pair.map(order=><article className="meal-voucher" key={order.id}><header><div><p>HÔTEL PARADIS · LOURDES</p><h2>BON DE COMMANDE</h2><span>{order.type}</span></div><div><strong>{order.quantity}</strong><small>unité(s)</small></div></header><div className="voucher-highlight"><time>{new Date(`${order.date}T12:00:00`).toLocaleDateString('fr-FR')} · {order.pickupTime}</time><b>{order.status}</b></div><dl><div><dt>Client / Groupe</dt><dd>{order.recipient||'—'}</dd></div><div><dt>Chambre</dt><dd>{order.room||'—'}</dd></div><div><dt>Destination / remise</dt><dd>{order.destination||'—'}</dd></div><div><dt>Contact</dt><dd>{order.contact||'—'}</dd></div></dl><section><h3>ALLERGIES / RÉGIMES</h3><p>{order.allergies||'Aucune information signalée'}</p></section><section><h3>COMPOSITION / CONTENU</h3><p>{order.composition||'Selon composition standard'}</p></section><section><h3>CONSIGNES</h3><p>{order.notes||'—'}</p></section><footer><div><span>Demandé par</span><strong>{order.createdBy}</strong></div><div><span>Préparé par</span><i/></div><div><span>Contrôlé / remis par</span><i/></div></footer><small className="voucher-stamp">HospiCore · Impression {new Date().toLocaleString('fr-FR')}</small></article>)}</section>)}</div></div>
}
