import { useEffect, useRef } from 'react';
import { useOperationalStore } from './useOperationalStore';

type MealCell={pax?:number;time?:string};
type MealKey='pdjBox'|'packedLunch'|'packedDinner';
type MealDay={date:string;pdjBox?:MealCell;packedLunch?:MealCell;packedDinner?:MealCell};
type Group={id:string;name?:string;leaderPhone?:string;phone?:string;dietary?:string;allergies?:string;mealDays?:MealDay[]};
type OrderType='PDJ Box'|'Panier déjeuner'|'Panier dîner';
type OrderStatus='À préparer'|'Préparé'|'Remis';
type MealOrder={id:string;type:OrderType;date:string;pickupTime:string;quantity:number;recipient:string;room:string;destination:string;contact:string;allergies:string;composition:string;notes:string;status:OrderStatus;createdAt:string;createdBy:string;updatedAt?:string;updatedBy?:string;printedAt?:string;printedBy?:string;sourceGroupId?:string;sourceMealKey?:MealKey;autoGenerated?:boolean};

function orderId(groupId:string,date:string,key:MealKey){return`group360-${groupId}-${date}-${key}`}
function autoOrder(group:Group,day:MealDay,key:MealKey,existing?:MealOrder):MealOrder{
 const meal=day[key]!,type:OrderType=key==='pdjBox'?'PDJ Box':key==='packedLunch'?'Panier déjeuner':'Panier dîner',now=new Date().toISOString();
 const fallbackTime=key==='pdjBox'?'06:30':key==='packedLunch'?'11:30':'18:30';
 return {
  id:orderId(group.id,day.date,key),
  type,
  date:day.date,
  pickupTime:meal.time||existing?.pickupTime||fallbackTime,
  quantity:Math.max(1,Number(meal.pax||0)),
  recipient:group.name||existing?.recipient||'Groupe',
  room:existing?.room||'',
  destination:existing?.destination||'Réception',
  contact:group.leaderPhone||group.phone||existing?.contact||'',
  allergies:group.dietary||group.allergies||existing?.allergies||'',
  composition:existing?.composition||'',
  notes:existing?.notes||'Bon généré automatiquement depuis la Fiche Groupe 360°. À vérifier par la Réception avant impression.',
  status:existing?.status||'À préparer',
  createdAt:existing?.createdAt||now,
  createdBy:existing?.createdBy||'HospiCore · Fiche Groupe 360°',
  updatedAt:now,
  updatedBy:'HospiCore · synchronisation Groupe 360°',
  printedAt:existing?.printedAt,
  printedBy:existing?.printedBy,
  sourceGroupId:group.id,
  sourceMealKey:key,
  autoGenerated:true,
 };
}
function same(a:MealOrder,b:MealOrder){return a.type===b.type&&a.date===b.date&&a.pickupTime===b.pickupTime&&a.quantity===b.quantity&&a.recipient===b.recipient&&a.contact===b.contact&&a.allergies===b.allergies&&a.sourceGroupId===b.sourceGroupId&&a.sourceMealKey===b.sourceMealKey}
function orderIsStillRequired(order:MealOrder,groups:Group[]){
 if(!order.autoGenerated||order.printedAt)return true;
 return groups.some(group=>(group.mealDays||[]).some(day=>(['pdjBox','packedLunch','packedDinner'] as const).some(key=>orderId(group.id,day.date,key)===order.id&&Number(day[key]?.pax||0)>0)));
}

export function MealOrderAutoSync(){
 const groups=useOperationalStore<Group[]>('group-360',[]),orders=useOperationalStore<MealOrder[]>('meal-orders',[]),saving=useRef(false);
 useEffect(()=>{
  if(saving.current||groups.state==='loading'||orders.state==='loading'||groups.state==='saving'||orders.state==='saving')return;
  const desired=new Map<string,MealOrder>();
  for(const group of groups.data)for(const day of group.mealDays||[])for(const key of ['pdjBox','packedLunch','packedDinner'] as const){
   const meal=day[key];
   if(Number(meal?.pax||0)>0){const id=orderId(group.id,day.date,key),existing=orders.data.find(order=>order.id===id);desired.set(id,autoOrder(group,day,key,existing));}
  }
  let changed=false;
  const next=orders.data.map(order=>{
   const wanted=desired.get(order.id);if(!wanted)return order;
   desired.delete(order.id);
   if(order.printedAt)return order;
   if(same(order,wanted))return order;
   changed=true;return {...order,...wanted};
  });
  for(const created of desired.values()){next.push(created);changed=true;}
  const cleaned=next.filter(order=>orderIsStillRequired(order,groups.data));
  if(cleaned.length!==next.length)changed=true;
  if(!changed)return;
  saving.current=true;void orders.save(cleaned).finally(()=>{saving.current=false});
 },[groups.data,orders.data,groups.state,orders.state]);
 return null;
}
