import { useEffect, useRef } from 'react';
import { useOperationalStore } from './useOperationalStore';

type MealCell={pax?:number;time?:string};
type MealDay={date:string;packedLunch?:MealCell;packedDinner?:MealCell};
type Group={id:string;name?:string;leaderPhone?:string;phone?:string;dietary?:string;allergies?:string;mealDays?:MealDay[]};
type OrderType='PDJ Box'|'Panier déjeuner'|'Panier dîner';
type OrderStatus='À préparer'|'Préparé'|'Remis';
type MealOrder={id:string;type:OrderType;date:string;pickupTime:string;quantity:number;recipient:string;room:string;destination:string;contact:string;allergies:string;composition:string;notes:string;status:OrderStatus;createdAt:string;createdBy:string;updatedAt?:string;updatedBy?:string;printedAt?:string;printedBy?:string;sourceGroupId?:string;sourceMealKey?:'packedLunch'|'packedDinner';autoGenerated?:boolean};

function orderId(groupId:string,date:string,key:'packedLunch'|'packedDinner'){return`group360-${groupId}-${date}-${key}`}
function autoOrder(group:Group,day:MealDay,key:'packedLunch'|'packedDinner',existing?:MealOrder):MealOrder{
 const meal=day[key]!,type:OrderType=key==='packedLunch'?'Panier déjeuner':'Panier dîner',now=new Date().toISOString();
 return {
  id:orderId(group.id,day.date,key),
  type,
  date:day.date,
  pickupTime:meal.time||existing?.pickupTime||(key==='packedLunch'?'11:30':'18:30'),
  quantity:Math.max(1,Number(meal.pax||0)),
  recipient:group.name||existing?.recipient||'Groupe',
  room:existing?.room||'',
  destination:existing?.destination||'Réception',
  contact:group.leaderPhone||group.phone||existing?.contact||'',
  allergies:group.dietary||group.allergies||existing?.allergies||'',
  composition:existing?.composition||'',
  notes:existing?.notes||'Bon généré automatiquement depuis la Fiche Groupe 360°. À vérifier par la Réception avant impression.',
  status:existing?.status||'À préparer',
  createdAt:existing?.createdAt||now,
  createdBy:existing?.createdBy||'HospiCore · Fiche Groupe 360°',
  updatedAt:now,
  updatedBy:'HospiCore · synchronisation Groupe 360°',
  printedAt:existing?.printedAt,
  printedBy:existing?.printedBy,
  sourceGroupId:group.id,
  sourceMealKey:key,
  autoGenerated:true,
 };
}
function same(a:MealOrder,b:MealOrder){return a.type===b.type&&a.date===b.date&&a.pickupTime===b.pickupTime&&a.quantity===b.quantity&&a.recipient===b.recipient&&a.contact===b.contact&&a.allergies===b.allergies&&a.sourceGroupId===b.sourceGroupId&&a.sourceMealKey===b.sourceMealKey}

export function MealOrderAutoSync(){
 const groups=useOperationalStore<Group[]>('group-360',[]),orders=useOperationalStore<MealOrder[]>('meal-orders',[]),saving=useRef(false);
 useEffect(()=>{
  if(saving.current||groups.state==='loading'||orders.state==='loading'||groups.state==='saving'||orders.state==='saving')return;
  const desired=new Map<string,MealOrder>();
  for(const group of groups.data)for(const day of group.mealDays||[])for(const key of ['packedLunch','packedDinner'] as const){const meal=day[key];if(Number(meal?.pax||0)>0){const id=orderId(group.id,day.date,key),existing=orders.data.find(o=>o.id===id);desired.set(id,autoOrder(group,day,key,existing));}}
  let changed=false;
  const next=orders.data.map(order=>{
   const wanted=desired.get(order.id);if(!wanted)return order;
   desired.delete(order.id);
   if(order.printedAt)return order;
   if(same(order,wanted))return order;
   changed=true;return {...order,...wanted};
  });
  for(const created of desired.values()){next.push(created);changed=true;}
  // Retire uniquement les bons auto non imprimés si le panier est supprimé de la fiche Groupe 360°.
  const activeIds=new Set(next.filter(o=>!o.autoGenerated||o.printedAt||groups.data.some(g=>(g.mealDays||[]).some(d=>orderId(g.id,d.date,'packedLunch')===o.id&&Number(d.packedLunch?.pax||0)>0||orderId(g.id,d.date,'packedDinner')===o.id&&Number(d.packedDinner?.pax||0)>0))).map(o=>o.id));
  const cleaned=next.filter(o=>activeIds.has(o.id));if(cleaned.length!==next.length)changed=true;
  if(!changed)return;
  saving.current=true;void orders.save(cleaned).finally(()=>{saving.current=false});
 },[groups.data,orders.data,groups.state,orders.state]);
 return null;
}
