import { useMemo, useState } from 'react';
import { ArrowLeft, CheckCircle2, Coffee, MoonStar, Printer, RefreshCw, Save } from 'lucide-react';
import { useOperationalStore } from './useOperationalStore';

type MealRow={id:string;date:string;service:string;time:string;pax:number;water:boolean;wine:boolean;notes:string};
type GroupControl={id:string;groupName:string;agency:string;arrival:string;departure:string;pax:number;rooms:number;leaderName:string;leaderRoom:string;leaderPhone:string;notes:string;meals:MealRow[];status:string};
type RouteNote={date:string;note:string;updatedAt:string;updatedBy:string;validatedAt?:string;validatedBy?:string};
function iso(d=new Date()){return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function addDay(v:string,n:number){const d=new Date(`${v}T12:00:00`);d.setDate(d.getDate()+n);return iso(d)}
function name(){try{const u=JSON.parse(localStorage.getItem('hospicore.session')||'{}')?.user||{};return`${u.firstName||'Utilisateur'} ${u.lastName||'HospiCore'}`.trim()}catch{return'Utilisateur HospiCore'}}
function stamp(){return new Date().toLocaleString('fr-FR')}
function mins(v:string){if(!v)return 9999;const[h,m]=v.split(':').map(Number);return h*60+m}
function initial(){const q=new URLSearchParams(location.search).get('date');return/^\d{4}-\d{2}-\d{2}$/.test(q||'')?q!:iso()}
function label(v:string){return new Date(`${v}T12:00:00`).toLocaleDateString('fr-FR',{weekday:'long',day:'2-digit',month:'long',year:'numeric'})}

export function NightWatchRoutePage(){
 const controls=useOperationalStore<GroupControl[]>('group-controls',[],3000),notes=useOperationalStore<RouteNote[]>('night-route-notes',[],3000),[date,setDate]=useState(initial),[manual,setManual]=useState(()=>notes.data.find(n=>n.date===initial())?.note||'');
 const next=addDay(date,1),current=notes.data.find(n=>n.date===date);
 const meals=useMemo(()=>controls.data.flatMap(c=>c.meals.filter(m=>(m.date===date&&mins(m.time)>=1320)||(m.date===next&&mins(m.time)<=510)).map(m=>({control:c,meal:m}))).sort((a,b)=>{const ad=a.meal.date===date?0:1,bd=b.meal.date===date?0:1;return ad-bd||mins(a.meal.time)-mins(b.meal.time)}),[controls.data,date,next]);
 async function save(validate=false){const at=stamp(),item:RouteNote={date,note:manual,updatedAt:at,updatedBy:name(),...(validate?{validatedAt:at,validatedBy:name()}:{validatedAt:current?.validatedAt,validatedBy:current?.validatedBy})};await notes.save([item,...notes.data.filter(n=>n.date!==date)])}
 function change(v:string){setDate(v);setManual(notes.data.find(n=>n.date===v)?.note||'');history.replaceState({},'',`/reception/feuille-route-veilleur?date=${v}`)}
 const busy=controls.state==='loading'||controls.state==='saving'||notes.state==='loading'||notes.state==='saving';
 return <main className="night-route-page"><header className="night-route-screen-header"><button onClick={()=>location.href='/'}><ArrowLeft size={18}/>Accueil</button><div><p>HospiCore · Nuit</p><h1><MoonStar size={30}/>Feuille de route veilleur</h1><span>Les repas ci-dessous proviennent exclusivement de la Matrice Contrôle Groupe.</span></div><div className="night-route-actions"><input type="date" value={date} onChange={e=>change(e.target.value)}/><button onClick={()=>{void controls.refresh();void notes.refresh()}}><RefreshCw size={17}/>{busy?'Synchronisation…':'Actualiser'}</button><button onClick={()=>void save(true)}><CheckCircle2 size={17}/>Valider</button><button className="print" onClick={()=>window.print()}><Printer size={17}/>Imprimer</button></div></header><article className="night-route-sheet"><header className="night-print-title"><div><p>HÔTEL PARADIS · LOURDES</p><h2>FEUILLE DE ROUTE VEILLEUR</h2><span>{label(date)} 22h00 → {label(next)} 08h30</span>{current?.validatedAt&&<small>Validée le {current.validatedAt} par {current.validatedBy}</small>}</div><div><strong>{meals.length}</strong><small>service(s) groupe</small></div></header><section className="night-block"><header><Coffee size={19}/><div><h3>Repas & effectifs groupes</h3><span>Source : Matrice Contrôle Groupe</span></div></header>{!meals.length?<p className="night-empty">Aucun repas groupe renseigné sur cette plage.</p>:<table><thead><tr><th>Date</th><th>Heure</th><th>Groupe</th><th>Service</th><th>Pax</th><th>Inclus</th><th>Guide / consignes</th></tr></thead><tbody>{meals.map(({control,meal})=><tr key={`${control.id}-${meal.id}`}><td>{new Date(`${meal.date}T12:00:00`).toLocaleDateString('fr-FR')}</td><td><b>{meal.time||'—'}</b></td><td><strong>{control.groupName}</strong><small>{control.agency||''}</small></td><td>{meal.service}</td><td><b>{meal.pax}</b></td><td>{[meal.water&&'Eau',meal.wine&&'Vin'].filter(Boolean).join(' + ')||'—'}</td><td>{[control.leaderName,control.leaderRoom&&`Ch. ${control.leaderRoom}`,control.leaderPhone,meal.notes].filter(Boolean).join(' · ')||'—'}</td></tr>)}</tbody></table>}</section><section className="night-block manual"><header><MoonStar size={19}/><div><h3>Transmission manuelle</h3><span>Consignes complémentaires pour le service de nuit.</span></div></header><textarea value={manual} onChange={e=>setManual(e.target.value)} placeholder="Consignes, appel attendu, surveillance particulière…"/><div className="night-note-footer"><span>{current?`Dernière mise à jour : ${current.updatedAt} · ${current.updatedBy}`:'Aucune transmission enregistrée.'}</span><button onClick={()=>void save(false)}><Save size={16}/>Enregistrer</button></div></section><footer className="night-print-footer"><span>HospiCore · source Contrôle Groupe</span><span>Veilleur : ____________________</span></footer></article></main>;
}
