import { useMemo, useState } from 'react';
import { AlertTriangle, Archive, ArrowDownToLine, ArrowLeft, ArrowUpFromLine, Calculator, CalendarDays, CheckCircle2, ClipboardList, Coffee, FileText, ListTodo, MessageSquareWarning, MoonStar, PackageCheck, Printer, RefreshCw, Save, Settings } from 'lucide-react';
import { useOperationalStore } from './useOperationalStore';

type MealRow={id:string;date:string;service:string;time:string;pax:number;water:boolean;wine:boolean;notes:string};
type GroupControl={id:string;groupName:string;agency:string;arrival:string;departure:string;pax:number;rooms:number;leaderName:string;leaderRoom:string;leaderPhone:string;notes:string;meals:MealRow[];status:string;validatedAt?:string};
type ManualMovement={id:string;name:string;agency:string;pax:number;rooms:number;arrivalDate:string;arrivalTime:string;departureDate:string;departureTime:string;transport:string;leaderName:string;leaderRoom:string;leaderPhone:string;notes:string};
type MealOrder={id:string;type:string;date:string;pickupTime:string;quantity:number;recipient:string;room:string;destination:string;allergies:string;notes:string;status:string};
type Task={id:string;reference:string;title:string;description:string;service:string;assignee:string;priority:string;status:string;dueAt:string;linkedTo:string};
type Instruction={id:string;reference:string;message:string;targetServices:string[];createdAt:string;authorName:string;directionPriority:boolean};
type Complaint={id:string;client:string;room:string;category:string;description:string;status:string;createdAt:string};
type Booking={id:string;title:string;room:string;date:string;start:string;end:string;attendees:number;organiser:string;setup:string;description?:string;notes:string;status:string};
type CashDay={id?:string;date?:string;department?:string;cashier?:string;notes?:string;lockedAt?:string;lockedBy?:string;directionValidatedAt?:string};
type Report={id:string;date:string;generatedAt:string;complaints?:unknown[];tasks?:unknown[];instructions?:unknown[];meetingRooms?:unknown[];cashYesterday?:{total:number}};
type AdminSettings={rooms?:Array<{id:string;name:string;active:boolean}>;categories?:unknown[]};
type RouteNote={date:string;note:string;updatedAt:string;updatedBy:string;validatedAt?:string;validatedBy?:string};
type NightMovement={kind:'Arrivée'|'Départ';date:string;time:string;item:ManualMovement};
function iso(d=new Date()){return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function addDay(v:string,n:number){const d=new Date(`${v}T12:00:00`);d.setDate(d.getDate()+n);return iso(d)}
function name(){try{const u=JSON.parse(localStorage.getItem('hospicore.session')||'{}')?.user||{};return`${u.firstName||'Utilisateur'} ${u.lastName||'HospiCore'}`.trim()}catch{return'Utilisateur HospiCore'}}
function stamp(){return new Date().toLocaleString('fr-FR')}
function mins(v?:string){if(!v)return 9999;const[h,m]=v.split(':').map(Number);return h*60+m}
function initial(){const q=new URLSearchParams(location.search).get('date');return/^\d{4}-\d{2}-\d{2}$/.test(q||'')?q!:iso()}
function label(v:string){return new Date(`${v}T12:00:00`).toLocaleDateString('fr-FR',{weekday:'long',day:'2-digit',month:'long',year:'numeric'})}
function shortDate(v:string){return new Date(`${v}T12:00:00`).toLocaleDateString('fr-FR')}
function inNight(eventDate:string,eventTime:string,start:string,end:string){if(!eventTime)return false;const m=mins(eventTime);return(eventDate===start&&m>=1320)||(eventDate===end&&m<=510)}
function dueInNight(value:string,start:string,end:string){if(!value)return false;const d=new Date(value);if(Number.isNaN(d.getTime()))return false;const from=new Date(`${start}T22:00:00`),to=new Date(`${end}T08:30:00`);return d<=to&&d>=from}
function cashRecords(data:unknown):CashDay[]{if(Array.isArray(data))return data as CashDay[];return data&&typeof data==='object'?[data as CashDay]:[]}
function overlapsNight(b:Booking,start:string,end:string){return(b.date===start&&mins(b.end)>1320)||(b.date===end&&mins(b.start)<510)||(b.date===start&&mins(b.start)>=1320)}

export function NightWatchRoutePage(){
 const controls=useOperationalStore<GroupControl[]>('group-controls',[],3000),movements=useOperationalStore<ManualMovement[]>('manual-arrivals-departures',[],3000),mealOrders=useOperationalStore<MealOrder[]>('meal-orders',[],3000),tasks=useOperationalStore<Task[]>('tasks',[],3000),instructions=useOperationalStore<Instruction[]>('general-instructions',[],3000),complaints=useOperationalStore<Complaint[]>('client-complaints',[],3000),meetings=useOperationalStore<Booking[]>('meeting-rooms',[],3000),cash=useOperationalStore<unknown>('reception-cash-day',[],3000),reports=useOperationalStore<Report[]>('direction-daily-reports',[],3000),admin=useOperationalStore<AdminSettings>('administration-settings',{rooms:[],categories:[]},5000),notes=useOperationalStore<RouteNote[]>('night-route-notes',[],3000),[date,setDate]=useState(initial),[manual,setManual]=useState(()=>notes.data.find(n=>n.date===initial())?.note||'');
 const next=addDay(date,1),current=notes.data.find(n=>n.date===date);
 const nightMovements=useMemo<NightMovement[]>(()=>movements.data.flatMap(item=>{const rows:NightMovement[]=[];if(inNight(item.arrivalDate,item.arrivalTime,date,next))rows.push({kind:'Arrivée',date:item.arrivalDate,time:item.arrivalTime,item});if(inNight(item.departureDate,item.departureTime,date,next))rows.push({kind:'Départ',date:item.departureDate,time:item.departureTime,item});return rows}).sort((a,b)=>{const ad=a.date===date?0:1,bd=b.date===date?0:1;return ad-bd||mins(a.time)-mins(b.time)}),[movements.data,date,next]);
 const meals=useMemo(()=>controls.data.flatMap(c=>(c.meals||[]).filter(m=>inNight(m.date,m.time,date,next)).map(m=>({control:c,meal:m}))).sort((a,b)=>{const ad=a.meal.date===date?0:1,bd=b.meal.date===date?0:1;return ad-bd||mins(a.meal.time)-mins(b.meal.time)}),[controls.data,date,next]);
 const orders=useMemo(()=>mealOrders.data.filter(o=>o.status!=='Remis'&&inNight(o.date,o.pickupTime,date,next)).sort((a,b)=>a.date.localeCompare(b.date)||a.pickupTime.localeCompare(b.pickupTime)),[mealOrders.data,date,next]);
 const activeTasks=useMemo(()=>tasks.data.filter(t=>t.status!=='Terminée'&&(dueInNight(t.dueAt,date,next)||['Critique','Haute'].includes(t.priority))).sort((a,b)=>String(a.dueAt||'9999').localeCompare(String(b.dueAt||'9999'))),[tasks.data,date,next]);
 const nightInstructions=useMemo(()=>instructions.data.filter(i=>i.directionPriority||i.targetServices?.includes('Réception')).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,8),[instructions.data]);
 const openComplaints=useMemo(()=>complaints.data.filter(c=>c.status!=='Traitée').sort((a,b)=>b.createdAt.localeCompare(a.createdAt)),[complaints.data]);
 const nightMeetings=useMemo(()=>meetings.data.filter(b=>overlapsNight(b,date,next)).sort((a,b)=>a.date.localeCompare(b.date)||a.start.localeCompare(b.start)),[meetings.data,date,next]);
 const cashState=useMemo(()=>cashRecords(cash.data).filter(c=>c.date===date||c.date===next).sort((a,b)=>String(a.department).localeCompare(String(b.department))),[cash.data,date,next]);
 const latestReport=useMemo(()=>reports.data.find(r=>r.date===date)||[...reports.data].sort((a,b)=>b.date.localeCompare(a.date))[0],[reports.data,date]);
 const archiveSummary=useMemo(()=>{const validatedControls=controls.data.filter(c=>c.validatedAt||c.status==='Validé').length,lockedCash=cashRecords(cash.data).filter(c=>c.lockedAt).length,validatedRoutes=notes.data.filter(n=>n.validatedAt).length;return{validatedControls,lockedCash,validatedRoutes}},[controls.data,cash.data,notes.data]);
 const activeRooms=(admin.data.rooms||[]).filter(r=>r.active!==false).length;
 async function save(validate=false){const at=stamp(),item:RouteNote={date,note:manual,updatedAt:at,updatedBy:name(),...(validate?{validatedAt:at,validatedBy:name()}:{validatedAt:current?.validatedAt,validatedBy:current?.validatedBy})};await notes.save([item,...notes.data.filter(n=>n.date!==date)])}
 function change(v:string){setDate(v);setManual(notes.data.find(n=>n.date===v)?.note||'');history.replaceState({},'',`/reception/feuille-route-veilleur?date=${v}`)}
 const stores=[controls,movements,mealOrders,tasks,instructions,complaints,meetings,cash,reports,admin,notes],busy=stores.some(s=>s.state==='loading'||s.state==='saving');
 const total=nightMovements.length+meals.length+orders.length+activeTasks.length+nightInstructions.length+openComplaints.length+nightMeetings.length;
 function refreshAll(){stores.forEach(s=>void s.refresh())}
 return <main className="night-route-page"><header className="night-route-screen-header"><button onClick={()=>location.href='/'}><ArrowLeft size={18}/>Accueil</button><div><p>HospiCore · Nuit</p><h1><MoonStar size={30}/>Feuille de route veilleur</h1><span>Synthèse automatique des informations utiles provenant de tous les modules opérationnels HospiCore.</span></div><div className="night-route-actions"><input type="date" value={date} onChange={e=>change(e.target.value)}/><button onClick={refreshAll}><RefreshCw size={17}/>{busy?'Synchronisation…':'Actualiser tout'}</button><button onClick={()=>void save(true)}><CheckCircle2 size={17}/>Valider</button><button className="print" onClick={()=>window.print()}><Printer size={17}/>Imprimer</button></div></header><article className="night-route-sheet"><header className="night-print-title"><div><p>HÔTEL PARADIS · LOURDES</p><h2>FEUILLE DE ROUTE VEILLEUR</h2><span>{label(date)} 22h00 → {label(next)} 08h30</span>{current?.validatedAt&&<small>Validée le {current.validatedAt} par {current.validatedBy}</small>}</div><div><strong>{total}</strong><small>élément(s) opérationnel(s)</small></div></header>
 <section className="night-summary"><div><span>Mouvements</span><strong>{nightMovements.length}</strong></div><div><span>Repas groupes</span><strong>{meals.length}</strong></div><div><span>Bons repas</span><strong>{orders.length}</strong></div><div><span>Tâches</span><strong>{activeTasks.length}</strong></div><div><span>Plaintes</span><strong>{openComplaints.length}</strong></div><div><span>Salles</span><strong>{nightMeetings.length}</strong></div></section>
 <section className="night-block"><header><ArrowDownToLine size={19}/><div><h3>Arrivées / Départs</h3><span>Source : Arrivées / Départs</span></div></header>{!nightMovements.length?<p className="night-empty">Aucun mouvement sur cette plage.</p>:<table><thead><tr><th>Type</th><th>Heure</th><th>Groupe / client</th><th>Pax</th><th>Ch.</th><th>Transport</th><th>Guide / consignes</th></tr></thead><tbody>{nightMovements.map(({kind,time,item})=><tr key={`${item.id}-${kind}`}><td><b>{kind==='Arrivée'?<><ArrowDownToLine size={14}/> Arrivée</>:<><ArrowUpFromLine size={14}/> Départ</>}</b></td><td><b>{time}</b></td><td>{item.name}<small>{item.agency}</small></td><td>{item.pax}</td><td>{item.rooms}</td><td>{item.transport||'—'}</td><td>{[item.leaderName,item.leaderRoom&&`Ch. ${item.leaderRoom}`,item.leaderPhone,item.notes].filter(Boolean).join(' · ')||'—'}</td></tr>)}</tbody></table>}</section>
 <section className="night-block"><header><Coffee size={19}/><div><h3>Contrôles Groupe · repas</h3><span>Source : Contrôle Groupe</span></div></header>{!meals.length?<p className="night-empty">Aucun repas groupe sur cette plage.</p>:<table><thead><tr><th>Heure</th><th>Groupe</th><th>Service</th><th>Pax</th><th>Inclus</th><th>Consignes</th></tr></thead><tbody>{meals.map(({control,meal})=><tr key={`${control.id}-${meal.id}`}><td><b>{meal.time}</b></td><td>{control.groupName}</td><td>{meal.service}</td><td><b>{meal.pax}</b></td><td>{[meal.water&&'Eau',meal.wine&&'Vin'].filter(Boolean).join(' + ')||'—'}</td><td>{meal.notes||control.notes||'—'}</td></tr>)}</tbody></table>}</section>
 <section className="night-block"><header><PackageCheck size={19}/><div><h3>Paniers repas & PDJ Box</h3><span>Source : commandes repas</span></div></header>{!orders.length?<p className="night-empty">Aucun bon à remettre pendant la nuit.</p>:<table><thead><tr><th>Heure</th><th>Type</th><th>Qté</th><th>Client / Groupe</th><th>Lieu</th><th>Régime / consignes</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td><b>{o.pickupTime}</b></td><td>{o.type}</td><td>{o.quantity}</td><td>{o.recipient}{o.room?` · Ch. ${o.room}`:''}</td><td>{o.destination||'—'}</td><td>{[o.allergies&&`⚠ ${o.allergies}`,o.notes].filter(Boolean).join(' · ')||'—'}</td></tr>)}</tbody></table>}</section>
 <section className="night-block"><header><ListTodo size={19}/><div><h3>Tâches à surveiller</h3><span>Source : Tâches · échéance de nuit ou priorité haute/critique</span></div></header>{!activeTasks.length?<p className="night-empty">Aucune tâche prioritaire pour cette nuit.</p>:<table><thead><tr><th>Priorité</th><th>Tâche</th><th>Assignée à</th><th>Échéance</th><th>Détail</th></tr></thead><tbody>{activeTasks.map(t=><tr key={t.id}><td><b>{t.priority}</b></td><td>{t.reference} · {t.title}</td><td>{t.assignee||t.service}</td><td>{t.dueAt?.replace('T',' ')||'—'}</td><td>{t.description||t.linkedTo||'—'}</td></tr>)}</tbody></table>}</section>
 <section className="night-block"><header><ClipboardList size={19}/><div><h3>Consignes Réception / Direction</h3><span>Source : Consignes</span></div></header>{!nightInstructions.length?<p className="night-empty">Aucune consigne active.</p>:<div className="night-request-list">{nightInstructions.map(i=><article key={i.id}>{i.directionPriority?<AlertTriangle size={18}/>:<ClipboardList size={18}/>}<div><strong>{i.reference} · {i.authorName}</strong><span>{i.message}</span></div></article>)}</div>}</section>
 <section className="night-block"><header><MessageSquareWarning size={19}/><div><h3>Plaintes ouvertes</h3><span>Source : Plaintes</span></div></header>{!openComplaints.length?<p className="night-empty">Aucune plainte ouverte.</p>:<table><thead><tr><th>Client / chambre</th><th>Catégorie</th><th>Plainte</th></tr></thead><tbody>{openComplaints.map(c=><tr key={c.id}><td>{c.client||'Client'}{c.room?` · Ch. ${c.room}`:''}</td><td>{c.category}</td><td>{c.description}</td></tr>)}</tbody></table>}</section>
 <section className="night-block"><header><CalendarDays size={19}/><div><h3>Salles de réunion</h3><span>Source : Salles de réunion</span></div></header>{!nightMeetings.length?<p className="night-empty">Aucune salle active sur cette plage.</p>:<table><thead><tr><th>Horaire</th><th>Salle</th><th>Réservation</th><th>Pers.</th><th>Consignes</th></tr></thead><tbody>{nightMeetings.map(b=><tr key={b.id}><td><b>{b.start}–{b.end}</b></td><td>{b.room}</td><td>{b.title}</td><td>{b.attendees}</td><td>{[b.setup,b.description,b.notes].filter(Boolean).join(' · ')||'—'}</td></tr>)}</tbody></table>}</section>
 <section className="night-block"><header><Calculator size={19}/><div><h3>État des caisses</h3><span>Source : Caisse</span></div></header>{!cashState.length?<p className="night-empty">Aucune caisse enregistrée pour cette période.</p>:<table><thead><tr><th>Service</th><th>Date</th><th>Statut</th><th>Caissier</th><th>Notes</th></tr></thead><tbody>{cashState.map((c,i)=><tr key={`${c.id||c.date}-${i}`}><td>{c.department||'Réception'}</td><td>{c.date?shortDate(c.date):'—'}</td><td><b>{c.lockedAt?'Verrouillée':'En cours'}</b></td><td>{c.cashier||'—'}</td><td>{c.notes||'—'}</td></tr>)}</tbody></table>}</section>
 <section className="night-block"><header><Archive size={19}/><div><h3>Archives & continuité</h3><span>Source : Archives</span></div></header><div className="night-summary"><div><span>Contrôles validés</span><strong>{archiveSummary.validatedControls}</strong></div><div><span>Caisses verrouillées</span><strong>{archiveSummary.lockedCash}</strong></div><div><span>Feuilles nuit validées</span><strong>{archiveSummary.validatedRoutes}</strong></div></div></section>
 <section className="night-block"><header><FileText size={19}/><div><h3>Rapport Direction</h3><span>Source : Rapport Direction</span></div></header>{latestReport?<p className="night-empty">Dernier rapport disponible : <b>{shortDate(latestReport.date)}</b> · {latestReport.complaints?.length||0} plainte(s) · {latestReport.tasks?.length||0} tâche(s) · {latestReport.instructions?.length||0} consigne(s) · {latestReport.meetingRooms?.length||0} salle(s).</p>:<p className="night-empty">Aucun rapport Direction disponible.</p>}</section>
 <section className="night-block"><header><Settings size={19}/><div><h3>État HospiCore / Administration</h3><span>Source : Administration</span></div></header><p className="night-empty"><b>{activeRooms}</b> salle(s) active(s) dans le référentiel. Les données opérationnelles ci-dessus sont synchronisées depuis leurs modules respectifs.</p></section>
 <section className="night-block manual"><header><MoonStar size={19}/><div><h3>Transmission manuelle du veilleur</h3><span>Complément libre à la synthèse automatique.</span></div></header><textarea value={manual} onChange={e=>setManual(e.target.value)} placeholder="Consignes, appel attendu, surveillance particulière…"/><div className="night-note-footer"><span>{current?`Dernière mise à jour : ${current.updatedAt} · ${current.updatedBy}`:'Aucune transmission enregistrée.'}</span><button onClick={()=>void save(false)}><Save size={16}/>Enregistrer</button></div></section><footer className="night-print-footer"><span>HospiCore · synthèse multi-modules</span><span>Veilleur : ____________________</span></footer></article></main>;
}
