import { useEffect, useMemo, useRef, useState } from 'react';
import { Bell, BellRing, CheckCheck, X } from 'lucide-react';
import type { OperationalChangeDetail } from './useOperationalStore';

type Toast={id:string;title:string;detail:string;href:string;namespace:string;at:number;read:boolean};
type SessionUser={id?:string;firstName?:string;lastName?:string;role?:string|{name?:string;baseRole?:string}};
type Task={id:string;reference?:string;title:string;service:string;assignee?:string;assigneeId?:string;assignmentType?:'user'|'service';status?:string;dueAt?:string};
const labels:Record<string,{title:string;detail:string;href:string}>={'group-360':{title:'Groupes mis à jour',detail:'Une fiche groupe a été modifiée depuis un autre poste.',href:'/reception'},'function-sheets':{title:'Fiche de fonction mise à jour',detail:'Les données commerciales ou la diffusion ont changé.',href:'/commercial'},'meeting-rooms':{title:'Salles de réunion mises à jour',detail:'Une réservation ou un horaire a changé.',href:'/salles-reunion'},'maintenance-interventions':{title:'Maintenance mise à jour',detail:'Une intervention a été créée ou modifiée.',href:'/tickets'},tasks:{title:'Tâches mises à jour',detail:'La liste des tâches opérationnelles a changé.',href:'/taches'},'general-instructions':{title:'Consignes mises à jour',detail:'Une consigne opérationnelle a été modifiée.',href:'/consignes-generales'},'operations-center':{title:'Centre des opérations mis à jour',detail:'Un prêt ou un équipement a changé.',href:'/centre-operations'}};
const receptionNamespaces=['group-360','function-sheets','meeting-rooms','maintenance-interventions','tasks','general-instructions','operations-center'];
const roleNamespaces:Record<string,string[]>={reception:receptionNamespaces,reception_manager:receptionNamespaces,commercial:['group-360','function-sheets','meeting-rooms','tasks','general-instructions'],maintenance:['maintenance-interventions','tasks','general-instructions']};
function currentUser():SessionUser{try{return JSON.parse(localStorage.getItem('hospicore.session')||'{}')?.user||{}}catch{return{}}}
function normalizedRole(user:SessionUser){const role=user.role,raw=String(typeof role==='object'?(role.baseRole||role.name||''):role||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();if(raw.includes('direction')||raw.includes('directeur')||raw.includes('admin'))return'direction';if(raw.includes('chef de reception')||raw.includes('responsable reception')||raw.includes('reception_manager')||raw.includes('front office manager'))return'reception_manager';if(raw.includes('maintenance')||raw.includes('tech'))return'maintenance';if(raw.includes('commercial')||raw.includes('vente'))return'commercial';if(raw.includes('reception')||raw.includes('front'))return'reception';return'direction';}
function serviceForRole(role:string){if(role==='direction')return'Direction';if(role==='commercial')return'Commercial';if(role==='maintenance')return'Maintenance';if(role==='reception'||role==='reception_manager')return'Réception';return'';}
function notificationKey(user:SessionUser){const identity=user.id||`${user.firstName||'user'}-${user.lastName||''}`;return`hospicore.notifications.v3.${identity}`}
function loadNotifications(key:string):Toast[]{try{const parsed=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(parsed)?parsed.slice(0,50):[]}catch{return[]}}
function readTaskSnapshot():Task[]{try{const raw=localStorage.getItem('hospicore.tasks.notification-snapshot');return raw?JSON.parse(raw):[]}catch{return[]}}
function writeTaskSnapshot(tasks:Task[]){localStorage.setItem('hospicore.tasks.notification-snapshot',JSON.stringify(tasks.map(t=>({id:t.id,reference:t.reference,title:t.title,service:t.service,assignee:t.assignee,assigneeId:t.assigneeId,assignmentType:t.assignmentType,status:t.status,dueAt:t.dueAt}))))}
function targetedTasks(previous:Task[],current:Task[],user:SessionUser,service:string){const old=new Map(previous.map(t=>[t.id,JSON.stringify(t)]));return current.filter(t=>t.status!=='Terminée'&&old.get(t.id)!==JSON.stringify(t)&&((t.assignmentType==='user'||t.assigneeId)?String(t.assigneeId)===String(user.id):t.service===service));}
export function OperationalToastHost(){
 const user=useMemo(()=>currentUser(),[]),role=useMemo(()=>normalizedRole(user),[user]),userService=useMemo(()=>serviceForRole(role),[role]),storageKey=useMemo(()=>notificationKey(user),[user]);
 const[toasts,setToasts]=useState<Toast[]>([]),[history,setHistory]=useState<Toast[]>(()=>loadNotifications(storageKey)),[open,setOpen]=useState(false);const timers=useRef<number[]>([]),taskSnapshot=useRef<Task[]>(readTaskSnapshot());
 const canReceive=(namespace:string)=>role==='direction'||(roleNamespaces[role]||[]).includes(namespace);
 const persist=(items:Toast[])=>{const next=items.slice(0,50);setHistory(next);localStorage.setItem(storageKey,JSON.stringify(next));};
 const markRead=(id:string)=>persist(history.map(item=>item.id===id?{...item,read:true}:item));const openNotification=(item:Toast)=>{markRead(item.id);location.assign(item.href)};const markAllRead=()=>persist(history.map(item=>({...item,read:true})));const unread=history.filter(item=>!item.read).length;
 useEffect(()=>{document.documentElement.dataset.hospicoreRole=role;document.body.dataset.hospicoreRole=role;return()=>{delete document.documentElement.dataset.hospicoreRole;delete document.body.dataset.hospicoreRole}},[role]);
 useEffect(()=>{const onChange=(event:Event)=>{const detail=(event as CustomEvent<OperationalChangeDetail>).detail;if(!detail||detail.source!=='remote'||!canReceive(detail.namespace))return;
   if(detail.namespace==='tasks'){fetch('/api/operational-sync/tasks',{headers:{Authorization:`Bearer ${JSON.parse(localStorage.getItem('hospicore.session')||'{}')?.token||localStorage.getItem('hospicore.token')||''}`}}).then(r=>r.ok?r.json():null).then(body=>{const current:Array<Task>=Array.isArray(body?.data)?body.data:Array.isArray(body)?body:[];if(!current.length)return;const targets=targetedTasks(taskSnapshot.current,current,user,userService);writeTaskSnapshot(current);taskSnapshot.current=current;if(!targets.length)return;targets.forEach(task=>{const id=`task-${task.id}-${detail.version}`,notification:Toast={id,title:'Nouvelle tâche assignée',detail:`${task.title}${task.dueAt?` · échéance ${new Date(task.dueAt).toLocaleString('fr-FR')}`:''}`,href:'/taches',namespace:'tasks',at:Date.now(),read:false};setToasts(c=>[notification,...c.filter(x=>x.id!==id)].slice(0,3));setHistory(c=>{const n=[notification,...c.filter(x=>x.id!==id)].slice(0,50);localStorage.setItem(storageKey,JSON.stringify(n));return n;});const timer=window.setTimeout(()=>setToasts(c=>c.filter(x=>x.id!==id)),6500);timers.current.push(timer);});}).catch(()=>{});return;}
   const meta=labels[detail.namespace]||{title:'HospiCore mis à jour',detail:'De nouvelles données viennent d’être synchronisées.',href:'/'};const id=`${detail.namespace}-${detail.version}-${detail.at}`,notification:Toast={id,...meta,namespace:detail.namespace,at:detail.at,read:false};setToasts(c=>[notification,...c.filter(i=>i.id!==id)].slice(0,3));setHistory(c=>{const n=[notification,...c.filter(i=>i.id!==id)].slice(0,50);localStorage.setItem(storageKey,JSON.stringify(n));return n;});const timer=window.setTimeout(()=>setToasts(c=>c.filter(i=>i.id!==id)),5000);timers.current.push(timer);};window.addEventListener('hospicore:operational-change',onChange);return()=>{window.removeEventListener('hospicore:operational-change',onChange);timers.current.forEach(t=>window.clearTimeout(t));timers.current=[]}},[role,storageKey,userService,user.id]);
 return <><div style={{position:'fixed',top:18,right:18,zIndex:9999,display:'grid',gap:10,width:'min(380px, calc(100vw - 36px))',pointerEvents:'none'}}>{toasts.map(t=><div key={t.id} style={{pointerEvents:'auto',display:'grid',gridTemplateColumns:'34px 1fr 28px',gap:10,alignItems:'start',padding:14,borderRadius:14,background:'#fff',border:'1px solid rgba(123,29,61,.16)',boxShadow:'0 14px 34px rgba(25,18,21,.16)'}}><button onClick={()=>openNotification(t)} style={{width:34,height:34,borderRadius:10,border:0,background:'#f7eef1',color:'#7b1d3d',display:'grid',placeItems:'center'}}><BellRing size={18}/></button><button onClick={()=>openNotification(t)} style={{border:0,background:'transparent',textAlign:'left',padding:0,color:'#24191d'}}><strong style={{display:'block',fontSize:14}}>{t.title}</strong><span style={{display:'block',marginTop:3,fontSize:12,lineHeight:1.4,color:'#6f6267'}}>{t.detail}</span></button><button onClick={()=>setToasts(c=>c.filter(i=>i.id!==t.id))} style={{width:28,height:28,border:0,background:'transparent'}}><X size={16}/></button></div>)}</div>
 <button onClick={()=>setOpen(v=>!v)} aria-label="Notifications" style={{position:'fixed',right:22,bottom:22,zIndex:9998,width:48,height:48,borderRadius:16,border:'1px solid rgba(123,29,61,.18)',background:'#fff',color:'#7b1d3d',boxShadow:'0 12px 30px rgba(25,18,21,.16)',display:'grid',placeItems:'center'}}><Bell size={20}/>{unread>0&&<span style={{position:'absolute',top:-6,right:-6,minWidth:22,height:22,padding:'0 5px',borderRadius:11,background:'#b42318',color:'#fff',fontSize:11,fontWeight:800,display:'grid',placeItems:'center',border:'2px solid #fff'}}>{unread>99?'99+':unread}</span>}</button>
 {open&&<aside style={{position:'fixed',right:22,bottom:80,zIndex:9998,width:'min(390px, calc(100vw - 32px))',maxHeight:'min(600px, calc(100vh - 120px))',overflow:'hidden',borderRadius:18,background:'#fff',border:'1px solid rgba(123,29,61,.14)',boxShadow:'0 18px 45px rgba(25,18,21,.2)',display:'grid',gridTemplateRows:'auto 1fr'}}><header style={{padding:'14px 16px',borderBottom:'1px solid #eee5e8',display:'flex',alignItems:'center',justifyContent:'space-between'}}><div><strong>Notifications</strong><span style={{display:'block',fontSize:11,color:'#7d7075'}}>{unread} non lue(s) · {userService||role}</span></div><button onClick={markAllRead} disabled={!unread} style={{border:0,background:'transparent',color:'#7b1d3d'}}><CheckCheck size={19}/></button></header><div style={{overflowY:'auto',padding:8}}>{!history.length&&<p style={{padding:20,textAlign:'center',color:'#807479'}}>Aucune notification récente.</p>}{history.map(item=><button key={item.id} onClick={()=>openNotification(item)} style={{width:'100%',border:0,borderRadius:12,padding:'11px 12px',marginBottom:4,background:item.read?'transparent':'#faf2f5',display:'grid',gridTemplateColumns:'10px 1fr',gap:9,textAlign:'left'}}><span style={{width:8,height:8,borderRadius:'50%',marginTop:5,background:item.read?'#d7cfd2':'#7b1d3d'}}/><span><strong style={{display:'block',fontSize:13}}>{item.title}</strong><small style={{display:'block',marginTop:2,color:'#766a6f'}}>{item.detail}</small><time style={{display:'block',marginTop:5,fontSize:10,color:'#9a8f93'}}>{new Date(item.at).toLocaleString('fr-FR')}</time></span></button>)}</div></aside>}</>;
}
