import { useEffect, useMemo, useState } from 'react';
import { createPortal } from 'react-dom';
import { Archive, BellRing, CheckCircle2, ChevronDown, Folder, FolderOpen, ListTodo } from 'lucide-react';
import { useOperationalStore } from './useOperationalStore';

type Task={id:string;reference?:string;title:string;description?:string;service:string;assignee?:string;status:string;completedAt?:string;createdAt?:string;history?:{comment?:string}[]};
type RequestItem={id:string;type:string;guestName:string;room:string;date:string;time:string;pax:number;destination:string;details:string;status:string;createdAt:string;createdBy:string;updatedAt:string;completedAt?:string};
type ArchiveRow={id:string;kind:'task'|'request';title:string;subtitle:string;detail:string;timestamp:number};
function ts(value?:string){if(!value)return 0;const direct=Date.parse(value);if(Number.isFinite(direct))return direct;const m=value.match(/(\d{2})\/(\d{2})\/(\d{4})[^\d]*(\d{2}):(\d{2})/);return m?new Date(Number(m[3]),Number(m[2])-1,Number(m[1]),Number(m[4]),Number(m[5])).getTime():0}
function requestTimestamp(i:RequestItem){return ts(i.completedAt)||ts(`${i.date}T${i.time||'00:00'}`)||ts(i.updatedAt)}
function period(timestamp:number){const d=new Date(timestamp);return{year:String(d.getFullYear()),month:String(d.getMonth()+1).padStart(2,'0'),monthLabel:d.toLocaleDateString('fr-FR',{month:'long'}).replace(/^./,c=>c.toUpperCase()),day:`${d.toLocaleDateString('fr-FR',{weekday:'long'}).replace(/^./,c=>c.toUpperCase())} ${d.toLocaleDateString('fr-FR',{day:'2-digit',month:'2-digit',year:'numeric'})}`}}
function ArchiveTree({title,rows,icon}:{title:string;rows:ArchiveRow[];icon:'task'|'request'}){const years=Array.from(new Set(rows.map(r=>period(r.timestamp).year))).sort((a,b)=>b.localeCompare(a));return <details className="op-archive-folder"><summary><span>{icon==='task'?<ListTodo size={21}/>:<BellRing size={21}/>}</span><div><strong>{title}</strong><small>{rows.length} élément(s)</small></div><b>{rows.length}</b><ChevronDown size={18}/></summary><div>{years.map(year=>{const yr=rows.filter(r=>period(r.timestamp).year===year),months=Array.from(new Map(yr.map(r=>[period(r.timestamp).month,period(r.timestamp).monthLabel])).entries()).sort((a,b)=>b[0].localeCompare(a[0]));return <details className="op-archive-year" key={year}><summary><Folder size={18}/><FolderOpen size={18}/><strong>{year}</strong><b>{yr.length}</b><ChevronDown size={16}/></summary>{months.map(([month,label])=>{const mr=yr.filter(r=>period(r.timestamp).month===month),days=Array.from(new Set(mr.map(r=>period(r.timestamp).day)));return <details className="op-archive-month" key={`${year}-${month}`}><summary><Folder size={17}/><FolderOpen size={17}/><strong>{label}</strong><b>{mr.length}</b><ChevronDown size={15}/></summary>{days.map(day=>{const dr=mr.filter(r=>period(r.timestamp).day===day).sort((a,b)=>b.timestamp-a.timestamp);return <details className="op-archive-day" key={`${year}-${month}-${day}`}><summary><Archive size={16}/><strong>{day}</strong><b>{dr.length}</b><ChevronDown size={14}/></summary><div className="op-archive-items">{dr.map(r=><article key={r.id}><span>{r.kind==='task'?<CheckCircle2 size={17}/>:<BellRing size={17}/>}</span><div><strong>{r.title}</strong><small>{r.subtitle}</small>{r.detail&&<p>{r.detail}</p>}</div><time>{new Date(r.timestamp).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}</time></article>)}</div></details>})}</details>})}</details>})}</div></details>}
export function OperationalArchiveAdditions(){const tasks=useOperationalStore<Task[]>('tasks',[]),requests=useOperationalStore<RequestItem[]>('individual-requests',[]),[target,setTarget]=useState<HTMLElement|null>(null);useEffect(()=>{const locate=()=>setTarget(document.querySelector<HTMLElement>('.reception-archives-page'));locate();const observer=new MutationObserver(locate);observer.observe(document.body,{childList:true,subtree:true});return()=>observer.disconnect()},[]);
 const taskRows=useMemo<ArchiveRow[]>(()=>tasks.data.filter(t=>t.status==='Terminée').map<ArchiveRow>(t=>({id:`task-${t.id}`,kind:'task',title:`${t.reference||'Tâche'} · ${t.title}`,subtitle:`${t.service}${t.assignee?` · ${t.assignee}`:''}`,detail:t.history?.slice().reverse().find(h=>h.comment)?.comment||t.description||'',timestamp:ts(t.completedAt)||ts(t.createdAt)})).filter(r=>r.timestamp>0).sort((a,b)=>b.timestamp-a.timestamp),[tasks.data]);
 const requestRows=useMemo<ArchiveRow[]>(()=>requests.data.filter(r=>r.status==='Terminée').map<ArchiveRow>(r=>({id:`request-${r.id}`,kind:'request',title:`${r.type} · Chambre ${r.room||'—'} · ${r.guestName||'Client'}`,subtitle:`${r.date} à ${r.time} · ${r.pax||1} pers. · ${r.createdBy}`,detail:r.destination||r.details||'',timestamp:requestTimestamp(r)})).filter(r=>r.timestamp>0).sort((a,b)=>b.timestamp-a.timestamp),[requests.data]);
 if(!target||!window.location.pathname.startsWith('/reception/archives'))return null;return createPortal(<section className="op-archive-additions"><header><p>ARCHIVES OPÉRATIONNELLES</p><h2>Tâches & demandes clients</h2><span>Les éléments terminés quittent automatiquement leurs vues actives et sont classés ici.</span></header><div className="op-archive-grid"><ArchiveTree title="Tâches terminées" rows={taskRows} icon="task"/><ArchiveTree title="Demandes clients individuels" rows={requestRows} icon="request"/></div></section>,target)}
