import { useEffect, useMemo, useRef, useState } from 'react';
import { BellRing, X } from 'lucide-react';
import type { OperationalChangeDetail } from './useOperationalStore';

type Toast={id:string;title:string;detail:string;href:string;namespace:string;at:number;read:boolean};
type SessionUser={id?:string;firstName?:string;lastName?:string;role?:string|{name?:string;baseRole?:string}};
type Task={id:string;reference?:string;title:string;service:string;assignee?:string;assigneeId?:string;assignmentType?:'user'|'service';status?:string;dueAt?:string};
const labels:Record<string,{title:string;detail:string;href:string}>={'group-360':{title:'Groupes mis à jour',detail:'Une fiche groupe a été modifiée depuis un autre poste.',href:'/reception'},'function-sheets':{title:'Fiche de fonction mise à jour',detail:'Les données commerciales ou la diffusion ont changé.',href:'/commercial'},'meeting-rooms':{title:'Salles de réunion mises à jour',detail:'Une réservation ou un horaire a changé.',href:'/salles-reunion'},'maintenance-interventions':{title:'Maintenance mise à jour',detail:'Une intervention a été créée ou modifiée.',href:'/tickets'},tasks:{title:'Tâches mises à jour',detail:'La liste des tâches opérationnelles a changé.',href:'/taches'},'general-instructions':{title:'Consignes mises à jour',detail:'Une consigne opérationnelle a été modifiée.',href:'/consignes-generales'},'operations-center':{title:'Centre des opérations mis à jour',detail:'Un prêt ou un équipement a changé.',href:'/centre-operations'}};
const receptionNamespaces=['group-360','function-sheets','meeting-rooms','maintenance-interventions','tasks','general-instructions','operations-center'];
const roleNamespaces:Record<string,string[]>={reception:receptionNamespaces,reception_manager:receptionNamespaces,commercial:['group-360','function-sheets','meeting-rooms','tasks','general-instructions'],maintenance:['maintenance-interventions','tasks','general-instructions']};
function currentUser():SessionUser{try{return JSON.parse(localStorage.getItem('hospicore.session')||'{}')?.user||{}}catch{return{}}}
function normalizedRole(user:SessionUser){const role=user.role,raw=String(typeof role==='object'?(role.baseRole||role.name||''):role||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();if(raw.includes('direction')||raw.includes('directeur')||raw.includes('admin'))return'direction';if(raw.includes('chef de reception')||raw.includes('responsable reception')||raw.includes('reception_manager')||raw.includes('front office manager'))return'reception_manager';if(raw.includes('maintenance')||raw.includes('tech'))return'maintenance';if(raw.includes('commercial')||raw.includes('vente'))return'commercial';if(raw.includes('reception')||raw.includes('front'))return'reception';return'direction';}
function serviceForRole(role:string){if(role==='direction')return'Direction';if(role==='commercial')return'Commercial';if(role==='maintenance')return'Maintenance';if(role==='reception'||role==='reception_manager')return'Réception';return'';}
function readTaskSnapshot():Task[]{try{const raw=localStorage.getItem('hospicore.tasks.notification-snapshot');return raw?JSON.parse(raw):[]}catch{return[]}}
function writeTaskSnapshot(tasks:Task[]){localStorage.setItem('hospicore.tasks.notification-snapshot',JSON.stringify(tasks.map(t=>({id:t.id,reference:t.reference,title:t.title,service:t.service,assignee:t.assignee,assigneeId:t.assigneeId,assignmentType:t.assignmentType,status:t.status,dueAt:t.dueAt}))))}
function targetedTasks(previous:Task[],current:Task[],user:SessionUser,service:string){const old=new Map(previous.map(t=>[t.id,JSON.stringify(t)]));return current.filter(t=>t.status!=='Terminée'&&old.get(t.id)!==JSON.stringify(t)&&((t.assignmentType==='user'||t.assigneeId)?String(t.assigneeId)===String(user.id):t.service===service));}

export function OperationalToastHost(){
 const user=useMemo(()=>currentUser(),[]),role=useMemo(()=>normalizedRole(user),[user]),userService=useMemo(()=>serviceForRole(role),[role]);
 const[toasts,setToasts]=useState<Toast[]>([]);const timers=useRef<number[]>([]),taskSnapshot=useRef<Task[]>(readTaskSnapshot());
 const canReceive=(namespace:string)=>role==='direction'||(roleNamespaces[role]||[]).includes(namespace);
 const openNotification=(item:Toast)=>location.assign(item.href);
 useEffect(()=>{document.documentElement.dataset.hospicoreRole=role;document.body.dataset.hospicoreRole=role;return()=>{delete document.documentElement.dataset.hospicoreRole;delete document.body.dataset.hospicoreRole}},[role]);
 useEffect(()=>{const onChange=(event:Event)=>{const detail=(event as CustomEvent<OperationalChangeDetail>).detail;if(!detail||detail.source!=='remote'||!canReceive(detail.namespace))return;
   if(detail.namespace==='tasks'){fetch('/api/operational-sync/tasks',{headers:{Authorization:`Bearer ${JSON.parse(localStorage.getItem('hospicore.session')||'{}')?.token||localStorage.getItem('hospicore.token')||''}`}}).then(r=>r.ok?r.json():null).then(body=>{const current:Array<Task>=Array.isArray(body?.data)?body.data:Array.isArray(body)?body:[];if(!current.length)return;const targets=targetedTasks(taskSnapshot.current,current,user,userService);writeTaskSnapshot(current);taskSnapshot.current=current;if(!targets.length)return;targets.forEach(task=>{const id=`task-${task.id}-${detail.version}`,notification:Toast={id,title:'Nouvelle tâche assignée',detail:`${task.title}${task.dueAt?` · échéance ${new Date(task.dueAt).toLocaleString('fr-FR')}`:''}`,href:'/taches',namespace:'tasks',at:Date.now(),read:false};setToasts(c=>[notification,...c.filter(x=>x.id!==id)].slice(0,3));const timer=window.setTimeout(()=>setToasts(c=>c.filter(x=>x.id!==id)),6500);timers.current.push(timer);});}).catch(()=>{});return;}
   const meta=labels[detail.namespace]||{title:'HospiCore mis à jour',detail:'De nouvelles données viennent d’être synchronisées.',href:'/'};const id=`${detail.namespace}-${detail.version}-${detail.at}`,notification:Toast={id,...meta,namespace:detail.namespace,at:detail.at,read:false};setToasts(c=>[notification,...c.filter(i=>i.id!==id)].slice(0,3));const timer=window.setTimeout(()=>setToasts(c=>c.filter(i=>i.id!==id)),5000);timers.current.push(timer);};window.addEventListener('hospicore:operational-change',onChange);return()=>{window.removeEventListener('hospicore:operational-change',onChange);timers.current.forEach(t=>window.clearTimeout(t));timers.current=[]}},[role,userService,user.id]);
 return <div style={{position:'fixed',top:18,right:18,zIndex:9999,display:'grid',gap:10,width:'min(380px, calc(100vw - 36px))',pointerEvents:'none'}}>{toasts.map(t=><div key={t.id} style={{pointerEvents:'auto',display:'grid',gridTemplateColumns:'34px 1fr 28px',gap:10,alignItems:'start',padding:14,borderRadius:14,background:'#fff',border:'1px solid rgba(123,29,61,.16)',boxShadow:'0 14px 34px rgba(25,18,21,.16)'}}><button onClick={()=>openNotification(t)} style={{width:34,height:34,borderRadius:10,border:0,background:'#f7eef1',color:'#7b1d3d',display:'grid',placeItems:'center'}}><BellRing size={18}/></button><button onClick={()=>openNotification(t)} style={{border:0,background:'transparent',textAlign:'left',padding:0,color:'#24191d'}}><strong style={{display:'block',fontSize:14}}>{t.title}</strong><span style={{display:'block',marginTop:3,fontSize:12,lineHeight:1.4,color:'#6f6267'}}>{t.detail}</span></button><button onClick={()=>setToasts(c=>c.filter(i=>i.id!==t.id))} style={{width:28,height:28,border:0,background:'transparent'}}><X size={16}/></button></div>)}</div>;
}
