import { FormEvent, useMemo, useState } from 'react';
import { ArrowLeft, CheckCircle2, Clock3, Package, PackagePlus, Plus, RefreshCw, Search, Trash2, Wrench, X } from 'lucide-react';
import { useOperationalStore } from './useOperationalStore';

type LoanStatus='En cours'|'Restitué';
type EquipmentStatus='Disponible'|'Maintenance';
type History={id:string;action:string;actor:string;role:string;at:string};
type Loan={id:string;reference:string;itemType:string;equipmentId:string;clientName:string;room:string;startAt:string;expectedEndAt:string;status:LoanStatus;history:History[]};
type Equipment={id:string;itemType:string;label:string;quantity:number;location:string;condition:string;status:EquipmentStatus;updatedBy:string;updatedAt:string};
type Store={loans:Loan[];equipment:Equipment[]};
const INITIAL:Store={loans:[],equipment:[]};
function actor(){try{const s=JSON.parse(localStorage.getItem('hospicore.session')||'{}'),u=s.user||{};return{name:`${u.firstName||'Utilisateur'} ${u.lastName||'HospiCore'}`.trim(),role:u.role||'Collaborateur'}}catch{return{name:'Utilisateur HospiCore',role:'Collaborateur'}}}
function stamp(){return new Date().toLocaleString('fr-FR',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit'})}
function normalize(data:Store):Store{return{loans:(data.loans||[]).map(l=>({...l,equipmentId:l.equipmentId||''})),equipment:(data.equipment||[]).map((e:any)=>({...e,quantity:Math.max(1,Number(e.quantity)||1),status:e.status==='Prêté'?'Disponible':e.status||'Disponible'}))}}
export function OperationsCenterV2Page(){
 const store=useOperationalStore<Store>('operations-center',INITIAL),data=normalize(store.data);const[tab,setTab]=useState<'prets'|'inventaire'>('prets'),[query,setQuery]=useState(''),[loanOpen,setLoanOpen]=useState(false),[equipmentOpen,setEquipmentOpen]=useState(false);
 const activeLoans=data.loans.filter(l=>l.status==='En cours');
 const available=(e:Equipment)=>Math.max(0,e.quantity-activeLoans.filter(l=>l.equipmentId===e.id||(!l.equipmentId&&l.itemType===e.itemType)).length);
 const loans=useMemo(()=>data.loans.filter(l=>l.status==='En cours'&&`${l.reference} ${l.clientName} ${l.room} ${l.itemType}`.toLowerCase().includes(query.toLowerCase())),[store.data,query]);
 const equipment=useMemo(()=>data.equipment.filter(e=>`${e.label} ${e.itemType} ${e.location}`.toLowerCase().includes(query.toLowerCase())),[store.data,query]);
 const overdue=activeLoans.filter(l=>new Date(l.expectedEndAt)<new Date()).length,totalAvailable=data.equipment.reduce((n,e)=>n+(e.status==='Disponible'?available(e):0),0);
 async function createEquipment(ev:FormEvent<HTMLFormElement>){ev.preventDefault();const f=new FormData(ev.currentTarget),u=actor(),item:Equipment={id:crypto.randomUUID(),itemType:String(f.get('itemType')||''),label:String(f.get('label')||''),quantity:Math.max(1,Number(f.get('quantity')||1)),location:String(f.get('location')||'Réception'),condition:String(f.get('condition')||'Bon état'),status:'Disponible',updatedBy:u.name,updatedAt:stamp()};if(await store.save({...data,equipment:[item,...data.equipment]}))setEquipmentOpen(false)}
 async function createLoan(ev:FormEvent<HTMLFormElement>){ev.preventDefault();const f=new FormData(ev.currentTarget),equipmentId=String(f.get('equipmentId')||''),item=data.equipment.find(e=>e.id===equipmentId);if(!item||item.status!=='Disponible'||available(item)<=0)return;const u=actor(),loan:Loan={id:crypto.randomUUID(),reference:`OP-${new Date().getFullYear()}-${String(data.loans.length+1).padStart(6,'0')}`,equipmentId:item.id,itemType:item.itemType,clientName:String(f.get('clientName')||''),room:String(f.get('room')||''),startAt:String(f.get('startAt')||''),expectedEndAt:String(f.get('expectedEndAt')||''),status:'En cours',history:[{id:crypto.randomUUID(),action:`Prêt créé · 1 ${item.label} sorti du stock`,actor:u.name,role:u.role,at:stamp()}]};if(await store.save({equipment:data.equipment,loans:[loan,...data.loans]}))setLoanOpen(false)}
 async function closeLoan(id:string){const u=actor();await store.save({...data,loans:data.loans.map(l=>l.id===id?{...l,status:'Restitué' as const,history:[...l.history,{id:crypto.randomUUID(),action:'Matériel restitué · quantité remise en stock',actor:u.name,role:u.role,at:stamp()}]}:l)})}
 async function toggleMaintenance(id:string){const u=actor();await store.save({...data,equipment:data.equipment.map(e=>e.id===id?{...e,status:e.status==='Maintenance'?'Disponible':'Maintenance',updatedBy:u.name,updatedAt:stamp()}:e)})}
 async function removeEquipment(id:string){const item=data.equipment.find(e=>e.id===id);if(!item||activeLoans.some(l=>l.equipmentId===id))return;if(!confirm(`Supprimer « ${item.label} » de l’inventaire ?`))return;await store.save({...data,equipment:data.equipment.filter(e=>e.id!==id)})}
 return <div className="operations-page"><header className="operations-header"><div><button onClick={()=>location.href='/'}><ArrowLeft size={18}/>Tableau de bord</button><p>HospiCore · Centre des opérations</p><h1>Prêts & inventaire partagé</h1><span>Un item correspond à un type de matériel et sa quantité totale. Chaque prêt décrémente automatiquement le disponible.</span></div><div className="operations-header-actions"><button className="operations-secondary" onClick={()=>void store.refresh()}><RefreshCw size={17}/>{store.message}</button><button className="operations-primary" onClick={()=>tab==='prets'?setLoanOpen(true):setEquipmentOpen(true)}><Plus size={18}/>{tab==='prets'?'Nouveau prêt':'Ajouter un item'}</button></div></header>
 <div className="operations-tabs"><button className={tab==='prets'?'active':''} onClick={()=>setTab('prets')}><PackagePlus size={17}/>Prêts en cours</button><button className={tab==='inventaire'?'active':''} onClick={()=>setTab('inventaire')}><Package size={17}/>Catalogue & quantités</button></div>
 <section className="operations-kpis"><article><PackagePlus/><span>Prêts actifs</span><strong>{activeLoans.length}</strong></article><article><Clock3/><span>Retours en retard</span><strong>{overdue}</strong></article><article><CheckCircle2/><span>Unités disponibles</span><strong>{totalAvailable}</strong></article><article><Wrench/><span>Items maintenance</span><strong>{data.equipment.filter(e=>e.status==='Maintenance').length}</strong></article></section>
 <label className="operations-search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher…"/></label>
 {tab==='prets'?<section className="operations-list">{loans.length===0&&<article className="loan-card"><h2>Aucun prêt en cours</h2><p>Les prêts restitués quittent automatiquement cette vue.</p></article>}{loans.map(l=><article className="loan-card" key={l.id}><div className="loan-title"><div><span className="loan-status">En cours</span><h2>{l.itemType}</h2><small>{l.reference}</small></div><div><strong>{l.clientName}</strong><span>Chambre {l.room}</span></div></div><div className="loan-grid"><div><span>Début</span><strong>{l.startAt.replace('T',' ')}</strong></div><div><span>Retour prévu</span><strong>{l.expectedEndAt.replace('T',' ')}</strong></div></div><button className="operations-secondary" onClick={()=>void closeLoan(l.id)}><CheckCircle2 size={17}/>Enregistrer la restitution</button></article>)}</section>:<section className="equipment-grid">{equipment.map(e=>{const out=e.quantity-available(e);return <article className="equipment-card" key={e.id}><div className="equipment-heading"><div><span className={`equipment-status ${e.status.toLowerCase()}`}>{e.status}</span><h2>{e.label}</h2><small>{e.itemType}</small></div><Package size={23}/></div><div className="equipment-details"><div><span>Stock total</span><strong>{e.quantity}</strong></div><div><span>Prêté</span><strong>{out}</strong></div><div><span>Disponible</span><strong>{e.status==='Maintenance'?0:available(e)}</strong></div><div><span>Emplacement</span><strong>{e.location}</strong></div></div><small>Mis à jour par {e.updatedBy} · {e.updatedAt}</small><div className="operations-item-actions"><button className="operations-secondary" onClick={()=>void toggleMaintenance(e.id)}><Wrench size={17}/>{e.status==='Maintenance'?'Remettre disponible':'Maintenance'}</button><button className="operations-secondary operations-danger" disabled={out>0} title={out>0?'Impossible : des unités sont actuellement prêtées':'Supprimer cet item'} onClick={()=>void removeEquipment(e.id)}><Trash2 size={17}/>Supprimer</button></div></article>})}</section>}
 {equipmentOpen&&<div className="operations-modal"><form onSubmit={e=>void createEquipment(e)}><header><h2>Ajouter un item au catalogue</h2><button type="button" onClick={()=>setEquipmentOpen(false)}><X/></button></header><div className="operations-form-grid"><label>Catégorie<input name="itemType" required placeholder="Adaptateur, parapluie…"/></label><label>Désignation<input name="label" required placeholder="Adaptateur universel"/></label><label>Quantité totale<input type="number" name="quantity" min="1" defaultValue="1" required/></label><label>Emplacement<input name="location" defaultValue="Réception" required/></label><label>État<input name="condition" defaultValue="Bon état"/></label></div><footer><button type="button" onClick={()=>setEquipmentOpen(false)}>Annuler</button><button className="operations-primary" type="submit">Ajouter et synchroniser</button></footer></form></div>}
 {loanOpen&&<div className="operations-modal"><form onSubmit={e=>void createLoan(e)}><header><h2>Nouveau prêt</h2><button type="button" onClick={()=>setLoanOpen(false)}><X/></button></header><div className="operations-form-grid"><label>Matériel<select name="equipmentId" required defaultValue=""><option value="" disabled>Sélectionner…</option>{data.equipment.filter(e=>e.status==='Disponible'&&available(e)>0).map(e=><option key={e.id} value={e.id}>{e.label} · {available(e)}/{e.quantity} disponible(s)</option>)}</select></label><label>Client<input name="clientName" required/></label><label>Chambre<input name="room" required/></label><label>Début<input type="datetime-local" name="startAt" required/></label><label>Retour prévu<input type="datetime-local" name="expectedEndAt" required/></label></div><footer><button type="button" onClick={()=>setLoanOpen(false)}>Annuler</button><button className="operations-primary" type="submit">Prêter 1 unité</button></footer></form></div>}
 </div>}
