import { FormEvent, useEffect, useMemo, useState } from 'react';
import { ArrowLeft, CheckCircle2, Clock3, CreditCard, Package, PackagePlus, Plus, RefreshCw, Search, ShieldAlert, UserRound, Wrench, X } from 'lucide-react';
import { loadSharedData, saveSharedData } from './operational-sync';

type LoanStatus='En cours'|'Restitué';
type EquipmentStatus='Disponible'|'Prêté'|'Maintenance';
type History={id:string;action:string;actor:string;role:string;at:string};
type Loan={id:string;reference:string;itemType:string;inventoryNumber:string;clientName:string;room:string;phone:string;nationality:string;startAt:string;expectedEndAt:string;actualEndAt?:string;depositAmount:number;cardBrand:string;cardLast4:string;preauthorizationReference:string;notes:string;status:LoanStatus;history:History[]};
type Equipment={id:string;inventoryNumber:string;itemType:string;label:string;location:string;condition:string;status:EquipmentStatus;notes:string;updatedBy:string;updatedAt:string};
type Store={loans:Loan[];equipment:Equipment[]};

const LOCAL='hospicore.operations.shared.v2';
const fallback:Store={
 loans:[{id:'loan-1',reference:'OP-2026-000128',itemType:'Fauteuil roulant',inventoryNumber:'FR-03',clientName:'John Smith',room:'315',phone:'+44 7700 900000',nationality:'Britannique',startAt:'2026-08-05T18:15',expectedEndAt:'2026-08-08T10:00',depositAmount:100,cardBrand:'Visa',cardLast4:'4587',preauthorizationReference:'PREAUTH-78451',notes:'Roue avant légèrement marquée.',status:'En cours',history:[{id:'h1',action:'Prêt créé et matériel remis',actor:'Thomas PETRISSANS',role:'Directeur Hébergement',at:'05/08/2026 18:15:22'}]}],
 equipment:[{id:'eq1',inventoryNumber:'FR-01',itemType:'Fauteuil roulant',label:'Fauteuil roulant n°1',location:'Réception A',condition:'Bon état',status:'Disponible',notes:'',updatedBy:'Thomas PETRISSANS',updatedAt:'05/08/2026 18:00:00'},{id:'eq2',inventoryNumber:'FR-03',itemType:'Fauteuil roulant',label:'Fauteuil roulant n°3',location:'Chambre 315',condition:'Roue avant marquée',status:'Prêté',notes:'Prêt OP-2026-000128',updatedBy:'Thomas PETRISSANS',updatedAt:'05/08/2026 18:15:22'},{id:'eq3',inventoryNumber:'AD-14',itemType:'Adaptateur',label:'Adaptateur universel n°14',location:'Réception A',condition:'Bon état',status:'Disponible',notes:'',updatedBy:'Thomas PETRISSANS',updatedAt:'05/08/2026 17:30:00'}]
};
function local():Store{try{return JSON.parse(localStorage.getItem(LOCAL)||'null')||fallback}catch{return fallback}}
function actor(){try{const s=JSON.parse(localStorage.getItem('hospicore.session')||'{}');const u=s.user||{};return{name:`${u.firstName||'Utilisateur'} ${u.lastName||'HospiCore'}`.trim(),role:u.role||'Collaborateur'}}catch{return{name:'Utilisateur HospiCore',role:'Collaborateur'}}}
function stamp(){return new Date().toLocaleString('fr-FR',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit'})}

export function OperationsCenterSharedPage(){
 const [data,setData]=useState<Store>(local);const [version,setVersion]=useState(0);const [sync,setSync]=useState('Chargement…');const [busy,setBusy]=useState(false);const [tab,setTab]=useState<'prets'|'inventaire'>('prets');const [loanOpen,setLoanOpen]=useState(false);const [eqOpen,setEqOpen]=useState(false);const [query,setQuery]=useState('');
 async function refresh(silent=false){if(!silent)setSync('Synchronisation…');const r=await loadSharedData<Store>('loans-equipment',local());setData(r.payload);setVersion(r.version);localStorage.setItem(LOCAL,JSON.stringify(r.payload));setSync(r.version?'Données partagées à jour':'Mode local');}
 useEffect(()=>{refresh();const id=setInterval(()=>refresh(true),30000);return()=>clearInterval(id)},[]);
 async function commit(next:Store){setBusy(true);setData(next);localStorage.setItem(LOCAL,JSON.stringify(next));try{const r=await saveSharedData('loans-equipment',next,version);setVersion(r.version);setSync(`Enregistré · version ${r.version}`)}catch(e){setSync(e instanceof Error?e.message:'Erreur de synchronisation')}finally{setBusy(false)}}
 const loans=useMemo(()=>data.loans.filter(l=>`${l.reference} ${l.itemType} ${l.clientName} ${l.room}`.toLowerCase().includes(query.toLowerCase())),[data.loans,query]);
 const equipment=useMemo(()=>data.equipment.filter(i=>`${i.inventoryNumber} ${i.itemType} ${i.label} ${i.location}`.toLowerCase().includes(query.toLowerCase())),[data.equipment,query]);
 const overdue=data.loans.filter(l=>l.status!=='Restitué'&&new Date(l.expectedEndAt)<new Date()).length;
 function createLoan(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),u=actor(),inv=String(f.get('inventoryNumber')||''),item=data.equipment.find(x=>x.inventoryNumber===inv),ref=`OP-${new Date().getFullYear()}-${String(data.loans.length+129).padStart(6,'0')}`;if(!item)return;const loan:Loan={id:crypto.randomUUID(),reference:ref,itemType:item.itemType,inventoryNumber:inv,clientName:String(f.get('clientName')||''),room:String(f.get('room')||''),phone:String(f.get('phone')||''),nationality:String(f.get('nationality')||''),startAt:String(f.get('startAt')||''),expectedEndAt:String(f.get('expectedEndAt')||''),depositAmount:Number(f.get('depositAmount')||0),cardBrand:String(f.get('cardBrand')||''),cardLast4:String(f.get('cardLast4')||'').slice(-4),preauthorizationReference:String(f.get('preauthorizationReference')||''),notes:String(f.get('notes')||''),status:'En cours',history:[{id:crypto.randomUUID(),action:'Prêt créé et matériel remis',actor:u.name,role:u.role,at:stamp()}]};commit({loans:[loan,...data.loans],equipment:data.equipment.map(x=>x.id===item.id?{...x,status:'Prêté',location:`Chambre ${loan.room}`,notes:`Prêt ${ref}`,updatedBy:u.name,updatedAt:stamp()}:x)});setLoanOpen(false)}
 function closeLoan(id:string){const u=actor(),loan=data.loans.find(l=>l.id===id);if(!loan)return;commit({loans:data.loans.map(l=>l.id===id?{...l,status:'Restitué',actualEndAt:new Date().toISOString().slice(0,16),history:[...l.history,{id:crypto.randomUUID(),action:'Matériel restitué et dossier clôturé',actor:u.name,role:u.role,at:stamp()}]}:l),equipment:data.equipment.map(x=>x.inventoryNumber===loan.inventoryNumber?{...x,status:'Disponible',location:'Réception A',notes:'Restitué et disponible',updatedBy:u.name,updatedAt:stamp()}:x)})}
 function createEquipment(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),u=actor();const item:Equipment={id:crypto.randomUUID(),inventoryNumber:String(f.get('inventoryNumber')||''),itemType:String(f.get('itemType')||''),label:String(f.get('label')||''),location:String(f.get('location')||''),condition:String(f.get('condition')||'Bon état'),status:String(f.get('status')||'Disponible') as EquipmentStatus,notes:String(f.get('notes')||''),updatedBy:u.name,updatedAt:stamp()};commit({...data,equipment:[item,...data.equipment]});setEqOpen(false)}
 function toggleMaintenance(id:string){const u=actor();commit({...data,equipment:data.equipment.map(x=>x.id===id?{...x,status:x.status==='Maintenance'?'Disponible':'Maintenance',updatedBy:u.name,updatedAt:stamp()}:x)})}
 return <div className="operations-page"><header className="operations-header"><div><button onClick={()=>location.href='/'}><ArrowLeft size={18}/>Tableau de bord</button><p>HospiCore · Centre des opérations</p><h1>Prêts & inventaire partagé</h1><span>Les remises, restitutions et changements de statut sont synchronisés entre tous les services.</span></div><div className="operations-header-actions"><button className="operations-secondary" onClick={()=>refresh()} disabled={busy}><RefreshCw size={17}/>{sync}</button><button className="operations-primary" disabled={busy} onClick={()=>tab==='prets'?setLoanOpen(true):setEqOpen(true)}><Plus size={18}/>{tab==='prets'?'Nouveau prêt':'Ajouter du matériel'}</button></div></header>
 <div className="operations-tabs"><button className={tab==='prets'?'active':''} onClick={()=>setTab('prets')}><PackagePlus size={17}/>Prêts</button><button className={tab==='inventaire'?'active':''} onClick={()=>setTab('inventaire')}><Package size={17}/>Inventaire</button></div>
 <section className="operations-kpis"><article><PackagePlus/><span>Prêts actifs</span><strong>{data.loans.filter(l=>l.status==='En cours').length}</strong></article><article><Clock3/><span>Retours en retard</span><strong>{overdue}</strong></article><article><CheckCircle2/><span>Disponibles</span><strong>{data.equipment.filter(i=>i.status==='Disponible').length}</strong></article><article><Wrench/><span>Maintenance</span><strong>{data.equipment.filter(i=>i.status==='Maintenance').length}</strong></article></section>
 <div className="operations-search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher…"/></div>
 {tab==='prets'?<section className="operations-list">{loans.map(l=><article className="loan-card" key={l.id}><div className="loan-title"><div><span className={`loan-status ${l.status.toLowerCase().replace(' ','-')}`}>{l.status}</span><h2>{l.itemType} · {l.inventoryNumber}</h2><small>{l.reference}</small></div><div className="loan-client"><UserRound size={20}/><strong>{l.clientName}</strong><span>Chambre {l.room}</span></div></div><div className="loan-grid"><div><span>Début</span><strong>{l.startAt.replace('T',' ')}</strong></div><div><span>Retour prévu</span><strong>{l.expectedEndAt.replace('T',' ')}</strong></div><div><span>Caution</span><strong>{l.depositAmount.toFixed(2)} €</strong></div><div><span>Garantie CB</span><strong><CreditCard size={15}/>{l.cardBrand||'Aucune'} {l.cardLast4?`•••• ${l.cardLast4}`:''}</strong><small>{l.preauthorizationReference||'Sans préautorisation'}</small></div></div><p className="loan-notes">{l.notes||'Aucune observation.'}</p><div className="loan-history"><strong>Historique signé</strong>{l.history.map(h=><div key={h.id}><span>{h.at}</span><p>{h.action}</p><small>{h.actor} · {h.role}</small></div>)}</div>{l.status!=='Restitué'&&<button className="operations-secondary" disabled={busy} onClick={()=>closeLoan(l.id)}><CheckCircle2 size={17}/>Enregistrer la restitution</button>}</article>)}</section>:<section className="equipment-grid">{equipment.map(i=><article className="equipment-card" key={i.id}><div className="equipment-heading"><div><span className={`equipment-status ${i.status.toLowerCase()}`}>{i.status}</span><h2>{i.label}</h2><small>{i.inventoryNumber} · {i.itemType}</small></div>{i.status==='Maintenance'?<ShieldAlert size={23}/>:<Package size={23}/>}</div><div className="equipment-details"><div><span>Emplacement</span><strong>{i.location}</strong></div><div><span>État</span><strong>{i.condition}</strong></div></div><p>{i.notes||'Aucune observation.'}</p><small>Mis à jour par {i.updatedBy} · {i.updatedAt}</small>{i.status!=='Prêté'&&<button className="operations-secondary" disabled={busy} onClick={()=>toggleMaintenance(i.id)}>{i.status==='Maintenance'?<CheckCircle2 size={17}/>:<Wrench size={17}/>} {i.status==='Maintenance'?'Remettre disponible':'Passer en maintenance'}</button>}</article>)}</section>}
 {loanOpen&&<div className="operations-modal"><form onSubmit={createLoan}><header><div><p>Nouveau dossier</p><h2>Prêt de matériel</h2></div><button type="button" onClick={()=>setLoanOpen(false)}><X/></button></header><div className="operations-form-grid"><label>N° inventaire<select name="inventoryNumber" required defaultValue=""><option value="" disabled>Sélectionner…</option>{data.equipment.filter(i=>i.status==='Disponible').map(i=><option key={i.id} value={i.inventoryNumber}>{i.inventoryNumber} · {i.label}</option>)}</select></label><label>Client<input name="clientName" required/></label><label>Chambre<input name="room" required/></label><label>Téléphone<input name="phone"/></label><label>Nationalité<input name="nationality"/></label><label>Début<input type="datetime-local" name="startAt" required/></label><label>Retour prévu<input type="datetime-local" name="expectedEndAt" required/></label><label>Caution (€)<input type="number" min="0" step="0.01" name="depositAmount"/></label><label>Carte<select name="cardBrand"><option value="">Aucune</option><option>Visa</option><option>Mastercard</option><option>Amex</option></select></label><label>4 derniers chiffres<input name="cardLast4" maxLength={4} pattern="[0-9]{4}"/></label><label>Référence préautorisation<input name="preauthorizationReference"/></label><label className="wide">Observations<textarea name="notes"/></label></div><p className="card-warning">Ne jamais saisir le numéro complet de carte ni le cryptogramme.</p><footer><button type="button" onClick={()=>setLoanOpen(false)}>Annuler</button><button className="operations-primary" type="submit">Créer, remettre et signer</button></footer></form></div>}
 {eqOpen&&<div className="operations-modal"><form onSubmit={createEquipment}><header><div><p>Inventaire</p><h2>Ajouter un équipement</h2></div><button type="button" onClick={()=>setEqOpen(false)}><X/></button></header><div className="operations-form-grid"><label>N° inventaire<input name="inventoryNumber" required/></label><label>Catégorie<input name="itemType" required/></label><label className="wide">Désignation<input name="label" required/></label><label>Emplacement<input name="location" required/></label><label>État<input name="condition" defaultValue="Bon état"/></label><label>Statut<select name="status"><option>Disponible</option><option>Maintenance</option></select></label><label className="wide">Observations<textarea name="notes"/></label></div><footer><button type="button" onClick={()=>setEqOpen(false)}>Annuler</button><button className="operations-primary" type="submit">Ajouter et signer</button></footer></form></div>}
 </div>;
}
