import { KeyboardEvent, useEffect, useMemo, useRef, useState } from 'react';
import { ArrowLeft, CheckCircle2, Lock, Paperclip, Printer, RefreshCw, ShieldCheck } from 'lucide-react';
import { can } from './permissions';
import { useOperationalStore } from './useOperationalStore';
import './reception-cash.css';

type CashDepartment='reception'|'restaurant'|'bar';
type PaymentKey='cbVad'|'cbEmv'|'cbContact'|'amexEmv'|'amexVad'|'amexSc'|'ancvConnect'|'adyen'|'bankTransfer'|'ancvPaper'|'bankCheque'|'cashDeposit';
type Validation={validated:boolean;by?:string;at?:string};
type Denomination={value:number;qty:string};
type CashDay={id:string;date:string;department:CashDepartment;cashier:string;cbVad:string;cbEmv:string;cbContact:string;amexEmv:string;amexVad:string;amexSc:string;ancvConnect:string;adyen:string;bankTransfer:string;ancvPaper:string;bankCheque:string;cashExpense:string;vegaTotal:string;telecollections:string;notes:string;denominations:Denomination[];validations:Partial<Record<PaymentKey,Validation>>;createdAt:string;updatedAt?:string;lockedAt?:string;lockedBy?:string;directionValidatedAt?:string;directionValidatedBy?:string};
type LegacyCashDay={date?:string;department?:CashDepartment;cash?:string;card?:string;bankTransfer?:string;ancvPaper?:string;ancvConnect?:string;amex?:string;adyen?:string;bankCheque?:string;vegaTotal?:string;telecollections?:string;notes?:string;preparedBy?:string;updatedAt?:string};
type StoreData=CashDay[]|LegacyCashDay;
type SaveState='saved'|'pending'|'saving'|'error';
const DENOMS=[500,200,100,50,20,10,5,2,1,.5,.2,.1,.05,.02,.01];
const DEPARTMENTS:Record<CashDepartment,{label:string;subtitle:string}>={reception:{label:'Réception',subtitle:'Caisse réalisée chaque soir'},restaurant:{label:'Restaurant',subtitle:'Caisse réalisée chaque soir'},bar:{label:'Bar',subtitle:'Caisse de la veille réalisée le lendemain matin'}};
const VALIDATION_ROWS:[PaymentKey,string][]=[['cbVad','CB VAD'],['cbEmv','CB EMV'],['cbContact','CB sans contact'],['amexEmv','Amex EMV'],['amexVad','Amex VAD'],['amexSc','Amex sans contact'],['ancvConnect','ANCV Connect'],['adyen','Adyen'],['bankTransfer','Virement bancaire'],['ancvPaper','Chèques-Vacances papier'],['bankCheque','Chèques bancaires'],['cashDeposit','Recette espèces']];
function iso(date=new Date()){return`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`}
function yesterday(){const d=new Date();d.setDate(d.getDate()-1);return iso(d)}
function money(v:string|undefined){const normalized=String(v||'').replace(/\s/g,'').replace(',','.');const n=Number(normalized);return Number.isFinite(n)?n:0}
function euro(n:number){return n.toLocaleString('fr-FR',{style:'currency',currency:'EUR'})}
function session(){try{return JSON.parse(localStorage.getItem('hospicore.session')||'{}')?.user||{}}catch{return{}}}
function person(){const u=session();return`${u.firstName||''} ${u.lastName||''}`.trim()||'Utilisateur HospiCore'}
function validDepartment(value:string|null|undefined):CashDepartment{return value==='restaurant'||value==='bar'?value:'reception'}
function defaultDate(department:CashDepartment){return department==='bar'?yesterday():iso()}
function blank(date=iso(),department:CashDepartment='reception'):CashDay{return{id:crypto.randomUUID(),date,department,cashier:person(),cbVad:'',cbEmv:'',cbContact:'',amexEmv:'',amexVad:'',amexSc:'',ancvConnect:'',adyen:'',bankTransfer:'',ancvPaper:'',bankCheque:'',cashExpense:'',vegaTotal:'',telecollections:'',notes:'',denominations:DENOMS.map(value=>({value,qty:''})),validations:{},createdAt:new Date().toISOString()}}
function normalize(data:StoreData):CashDay[]{if(Array.isArray(data))return data.map(r=>({...r,department:validDepartment(r.department),denominations:Array.isArray(r.denominations)?r.denominations:DENOMS.map(value=>({value,qty:''})),validations:r.validations||{}}));if(data&&data.date){const migrated=blank(data.date,validDepartment(data.department));migrated.cashier=data.preparedBy||person();migrated.cbEmv=data.card||'';migrated.bankTransfer=data.bankTransfer||'';migrated.ancvPaper=data.ancvPaper||'';migrated.ancvConnect=data.ancvConnect||'';migrated.amexEmv=data.amex||'';migrated.adyen=data.adyen||'';migrated.bankCheque=data.bankCheque||'';migrated.vegaTotal=data.vegaTotal||'';migrated.telecollections=data.telecollections||'';migrated.notes=data.notes||'';migrated.updatedAt=data.updatedAt;return[migrated]}return[]}
function advanceOnEnter(event:KeyboardEvent<HTMLInputElement|HTMLTextAreaElement>){if(event.key!=='Enter'||event.shiftKey||event.currentTarget.tagName==='TEXTAREA')return;event.preventDefault();const fields=Array.from(document.querySelectorAll<HTMLElement>('.cash-sheet [data-cash-entry="true"]:not([disabled])'));const index=fields.indexOf(event.currentTarget);const next=fields[index+1];if(next){next.focus();if(next instanceof HTMLInputElement)next.select()}}

export function ReceptionCashPage(){
 const params=new URLSearchParams(location.search),initialDepartment=validDepartment(params.get('department'));
 const store=useOperationalStore<StoreData>('reception-cash-day',[]),records=normalize(store.data),[department,setDepartment]=useState<CashDepartment>(initialDepartment),[selectedDate,setSelectedDate]=useState(()=>params.get('date')||defaultDate(initialDepartment));
 const source=useMemo(()=>records.find(r=>r.date===selectedDate&&r.department===department)||blank(selectedDate,department),[store.data,store.version,selectedDate,department]);
 const[draft,setDraft]=useState<CashDay>(source),[saveState,setSaveState]=useState<SaveState>('saved');
 const timer=useRef<number|null>(null),draftRef=useRef(draft),recordsRef=useRef(records),dirtyRef=useRef(false);
 useEffect(()=>{recordsRef.current=records},[store.data,store.version]);
 useEffect(()=>{draftRef.current=draft},[draft]);
 useEffect(()=>{if(dirtyRef.current)return;setDraft(source);draftRef.current=source;setSaveState('saved')},[store.version,source]);
 useEffect(()=>{if(timer.current)window.clearTimeout(timer.current);dirtyRef.current=false;setDraft(source);draftRef.current=source;setSaveState('saved')},[selectedDate,department]);
 useEffect(()=>()=>{if(timer.current)window.clearTimeout(timer.current)},[]);
 const record=draft,locked=Boolean(record.lockedAt),canEdit=can('cash.edit')&&!locked,canValidate=can('cash.validate')&&locked&&selectedDate<iso();
 const cbTotal=money(record.cbVad)+money(record.cbEmv)+money(record.cbContact),amexTotal=money(record.amexEmv)+money(record.amexVad)+money(record.amexSc),cashDeposit=record.denominations.reduce((sum,row)=>sum+row.value*money(row.qty),0),cashExpense=money(record.cashExpense),cashRevenue=cashDeposit+cashExpense,total=cbTotal+amexTotal+money(record.ancvConnect)+money(record.adyen)+money(record.bankTransfer)+money(record.ancvPaper)+money(record.bankCheque)+cashRevenue,vega=money(record.vegaTotal),difference=total-vega,allValidated=VALIDATION_ROWS.every(([key])=>record.validations[key]?.validated);
 async function persist(next:CashDay){const current=recordsRef.current,updated=[...current.filter(r=>!(r.date===next.date&&r.department===next.department)),next].sort((a,b)=>`${b.date}-${b.department}`.localeCompare(`${a.date}-${a.department}`)),stamp=next.updatedAt;setSaveState('saving');const ok=await store.save(updated);if(draftRef.current.updatedAt===stamp){dirtyRef.current=!ok;setSaveState(ok?'saved':'error')}else if(ok)setSaveState('pending');return ok}
 function schedule(next:CashDay,delay=700){dirtyRef.current=true;setDraft(next);draftRef.current=next;setSaveState('pending');if(timer.current)window.clearTimeout(timer.current);timer.current=window.setTimeout(()=>{timer.current=null;void persist({...draftRef.current,updatedAt:new Date().toISOString()})},delay)}
 function set<K extends keyof CashDay>(key:K,value:CashDay[K]){if(!canEdit)return;schedule({...draftRef.current,[key]:value,updatedAt:new Date().toISOString()})}
 function setDenom(index:number,qty:string){if(!canEdit)return;const denominations=draftRef.current.denominations.map((row,i)=>i===index?{...row,qty}:row);schedule({...draftRef.current,denominations,updatedAt:new Date().toISOString()})}
 function selectDepartment(next:CashDepartment){if(next===department)return;const nextDate=new URLSearchParams(location.search).has('date')?selectedDate:defaultDate(next);setDepartment(next);setSelectedDate(nextDate);history.replaceState({},'',`/reception/caisse?department=${next}&date=${nextDate}`)}
 function selectDate(date:string){setSelectedDate(date);history.replaceState({},'',`/reception/caisse?department=${department}&date=${date}`)}
 async function printAndLock(){if(locked){window.print();return}if(!can('cash.edit'))return;if(timer.current){window.clearTimeout(timer.current);timer.current=null}const now=new Date().toISOString(),next={...draftRef.current,department,cashier:draftRef.current.cashier||person(),lockedAt:now,lockedBy:person(),updatedAt:now};dirtyRef.current=true;setDraft(next);draftRef.current=next;if(await persist(next)){dirtyRef.current=false;setTimeout(()=>window.print(),150)}}
 function toggleValidation(key:PaymentKey){if(!canValidate)return;const current=draftRef.current.validations[key],validated=!current?.validated,validations={...draftRef.current.validations,[key]:validated?{validated:true,by:person(),at:new Date().toISOString()}:{validated:false}},now=new Date().toISOString(),complete=VALIDATION_ROWS.every(([rowKey])=>validations[rowKey]?.validated),next={...draftRef.current,validations,directionValidatedAt:complete?(draftRef.current.directionValidatedAt||now):undefined,directionValidatedBy:complete?(draftRef.current.directionValidatedBy||person()):undefined,updatedAt:now};schedule(next,350)}
 const saveLabel=saveState==='pending'?'Sauvegarde automatique…':saveState==='saving'?'Enregistrement…':saveState==='error'?'Erreur d’enregistrement':'Enregistré';
 return <div className="cash-page"><header className="cash-toolbar no-print"><button onClick={()=>location.href='/'}><ArrowLeft size={17}/>Centre de Commandement</button><div><strong>Caisse {DEPARTMENTS[department].label}</strong><span>{locked?'Caisse verrouillée':canEdit?'Saisie de la caisse':'Lecture seule'} · {saveLabel}</span></div><div className="cash-department-switch" role="tablist">{(Object.keys(DEPARTMENTS) as CashDepartment[]).map(key=><button type="button" role="tab" aria-selected={department===key} className={department===key?'active':''} onClick={()=>selectDepartment(key)} key={key}>{DEPARTMENTS[key].label}</button>)}</div><label className="cash-day-picker">Journée<input type="date" value={selectedDate} max={iso()} onChange={e=>selectDate(e.target.value)}/></label><button onClick={()=>void store.refresh()}><RefreshCw size={16}/>Actualiser</button>{can('cash.edit')&&<button className="primary" onClick={()=>void printAndLock()}><Printer size={16}/>{locked?'Réimprimer':'Imprimer & verrouiller'}</button>}</header>
 <main className={`cash-sheet${locked?' locked':''}`}><header className="cash-head"><div><p>HÔTEL PARADIS · LOURDES</p><h1>Feuille de caisse</h1><span>{DEPARTMENTS[department].label} · {DEPARTMENTS[department].subtitle}</span></div><div className="cash-meta"><label>Caissier<input data-cash-entry="true" disabled={!canEdit} value={record.cashier} onKeyDown={advanceOnEnter} onFocus={e=>e.currentTarget.select()} onChange={e=>set('cashier',e.target.value)}/></label><label>Date de caisse<input type="date" disabled value={record.date}/></label></div></header>
 {locked&&<div className="cash-lock-banner"><Lock size={16}/><span>Saisie verrouillée le {new Date(record.lockedAt!).toLocaleString('fr-FR')} par <strong>{record.lockedBy}</strong>.</span></div>}
 <section className="cash-core-grid"><div className="cash-payments"><h2>Total CB & autres règlements</h2><CashRow label="CB VAD (paiement à distance)" value={record.cbVad} disabled={!canEdit} onChange={v=>set('cbVad',v)} validation={record.validations.cbVad} validate={()=>toggleValidation('cbVad')} canValidate={canValidate}/><CashRow label="CB EMV" value={record.cbEmv} disabled={!canEdit} onChange={v=>set('cbEmv',v)} validation={record.validations.cbEmv} validate={()=>toggleValidation('cbEmv')} canValidate={canValidate}/><CashRow label="CB sans contact" value={record.cbContact} disabled={!canEdit} onChange={v=>set('cbContact',v)} validation={record.validations.cbContact} validate={()=>toggleValidation('cbContact')} canValidate={canValidate}/><TotalRow label="TOTAL CARTE BANCAIRE" value={cbTotal}/><CashRow label="AMEX EMV" value={record.amexEmv} disabled={!canEdit} onChange={v=>set('amexEmv',v)} validation={record.validations.amexEmv} validate={()=>toggleValidation('amexEmv')} canValidate={canValidate}/><CashRow label="AMEX VAD" value={record.amexVad} disabled={!canEdit} onChange={v=>set('amexVad',v)} validation={record.validations.amexVad} validate={()=>toggleValidation('amexVad')} canValidate={canValidate}/><CashRow label="AMEX sans contact" value={record.amexSc} disabled={!canEdit} onChange={v=>set('amexSc',v)} validation={record.validations.amexSc} validate={()=>toggleValidation('amexSc')} canValidate={canValidate}/><TotalRow label="TOTAL AMEX" value={amexTotal}/><CashRow label="ANCV Connect" value={record.ancvConnect} disabled={!canEdit} onChange={v=>set('ancvConnect',v)} validation={record.validations.ancvConnect} validate={()=>toggleValidation('ancvConnect')} canValidate={canValidate}/><CashRow label="Dépense de caisse (+ recette espèces)" value={record.cashExpense} disabled={!canEdit} onChange={v=>set('cashExpense',v)}/><CashRow label="TOTAL VIREMENT" value={record.bankTransfer} disabled={!canEdit} onChange={v=>set('bankTransfer',v)} validation={record.validations.bankTransfer} validate={()=>toggleValidation('bankTransfer')} canValidate={canValidate}/><CashRow label="TOTAL ADYEN" value={record.adyen} disabled={!canEdit} onChange={v=>set('adyen',v)} validation={record.validations.adyen} validate={()=>toggleValidation('adyen')} canValidate={canValidate}/><CashRow label="CHÈQUES-VACANCES PAPIER" value={record.ancvPaper} disabled={!canEdit} onChange={v=>set('ancvPaper',v)} validation={record.validations.ancvPaper} validate={()=>toggleValidation('ancvPaper')} canValidate={canValidate}/><CashRow label="CHÈQUES BANCAIRES" value={record.bankCheque} disabled={!canEdit} onChange={v=>set('bankCheque',v)} validation={record.validations.bankCheque} validate={()=>toggleValidation('bankCheque')} canValidate={canValidate}/></div>
 <div className="cash-denoms"><h2>Remise espèces (= espèces physiquement remises)</h2><div className="denom-head"><span>Coupure</span><span>Qté</span><span>Montant</span></div>{record.denominations.map((row,index)=><div className="denom-row" key={row.value}><span>{euro(row.value)}</span><input data-cash-entry="true" disabled={!canEdit} inputMode="numeric" value={row.qty} onFocus={e=>e.currentTarget.select()} onKeyDown={advanceOnEnter} onChange={e=>setDenom(index,e.target.value)} placeholder="0"/><strong>{euro(row.value*money(row.qty))}</strong></div>)}<div className="denom-subtotal"><span>Remise espèces physique</span><strong>{euro(cashDeposit)}</strong></div><div className="denom-subtotal expense"><span>+ Dépense de caisse</span><strong>{euro(cashExpense)}</strong></div><div className="denom-total"><span>RECETTE ESPÈCES RECONSTITUÉE</span><strong>{euro(cashRevenue)}</strong><label className="direction-check"><input type="checkbox" checked={Boolean(record.validations.cashDeposit?.validated)} disabled={!canValidate} onChange={()=>toggleValidation('cashDeposit')}/><span>{record.validations.cashDeposit?.validated?'Validé Direction':'À valider'}</span></label></div></div></section>
 <section className="cash-reconcile"><div><span>TOTAL FEUILLE DE CAISSE</span><strong>{euro(total)}</strong><small>Inclut remise espèces + dépense de caisse</small></div><label><span>TOTAL VEGA (DÉTAILS TOUS RÈGLEMENTS)</span><input data-cash-entry="true" disabled={!canEdit} inputMode="decimal" value={record.vegaTotal} onFocus={e=>e.currentTarget.select()} onKeyDown={advanceOnEnter} onChange={e=>set('vegaTotal',e.target.value)} placeholder="0,00"/><b>€</b></label><div className={Math.abs(difference)<.005?'ok':'alert'}><strong>{Math.abs(difference)<.005?'CONTRÔLE OK':'ÉCART À CONTRÔLER'}</strong><span>{euro(difference)}</span></div></section>
 <section className="cash-direction"><header><ShieldCheck size={18}/><div><h2>Validation Direction</h2><p>Chaque moyen de paiement est contrôlé individuellement. La validation complète est horodatée automatiquement.</p></div><strong>{allValidated?'VALIDATION COMPLÈTE':`${VALIDATION_ROWS.filter(([k])=>record.validations[k]?.validated).length}/${VALIDATION_ROWS.length}`}</strong></header>{record.directionValidatedAt&&<div className="cash-direction-stamp"><ShieldCheck size={15}/><span>Validation Direction complète le <strong>{new Date(record.directionValidatedAt).toLocaleString('fr-FR')}</strong> par <strong>{record.directionValidatedBy}</strong></span></div>}<div className="direction-grid">{VALIDATION_ROWS.map(([key,label])=>{const v=record.validations[key];return <label key={key} className={v?.validated?'validated':''}><input type="checkbox" checked={Boolean(v?.validated)} disabled={!canValidate} onChange={()=>toggleValidation(key)}/><span><b>{label}</b><small>{v?.validated?`${v.by} · ${new Date(v.at!).toLocaleString('fr-FR')}`:locked?(selectedDate<iso()?(can('cash.validate')?'En attente Direction':'Réservé Direction'):'Disponible demain'):'Caisse non verrouillée'}</small></span></label>})}</div></section>
 <section className="cash-attachment"><header><Paperclip size={17}/><div><h2>Télécollectes du jour</h2><p>Agrafer ici les tickets CB, AMEX, ADYEN et ANCV Connect.</p></div></header><div className="staple-zone"><span>ZONE D'AGRAFAGE</span><textarea data-cash-entry="true" disabled={!canEdit} value={record.telecollections} onChange={e=>set('telecollections',e.target.value)} placeholder="Références / observations télécollectes…"/></div></section><section className="cash-notes"><label>Observations / remarques / justification d'écart<textarea data-cash-entry="true" disabled={!canEdit} value={record.notes} onChange={e=>set('notes',e.target.value)} placeholder="Informations complémentaires…"/></label></section>
 <footer className="cash-signatures"><div><span>Horodatage verrouillage</span><strong>{record.lockedAt?new Date(record.lockedAt).toLocaleString('fr-FR'):'À l’impression'}</strong></div><div><span>Signature du caissier</span><strong>{record.lockedBy||record.cashier}</strong><i/></div><div><span>Validation Direction</span><strong>{record.directionValidatedAt?`${record.directionValidatedBy} · ${new Date(record.directionValidatedAt).toLocaleString('fr-FR')}`:'En attente'}</strong><i/></div></footer><p className="cash-foot">Document interne · Hôtel Paradis Lourdes · Caisse {DEPARTMENTS[department].label} · Une fois imprimée, la saisie de caisse est verrouillée.</p></main></div>
}
function CashRow({label,value,disabled,onChange,validation,validate,canValidate}:{label:string;value:string;disabled:boolean;onChange:(v:string)=>void;validation?:Validation;validate?:()=>void;canValidate?:boolean}){return <div className="cash-row"><span>{label}</span><div className="amount"><input data-cash-entry="true" disabled={disabled} inputMode="decimal" value={value} onFocus={e=>e.currentTarget.select()} onKeyDown={advanceOnEnter} onChange={e=>onChange(e.target.value)} placeholder="0,00"/><b>€</b></div>{validate?<label className={`mini-check${validation?.validated?' validated':''}`} title={validation?.validated?`${validation.by} · ${validation.at}`:'Validation Direction'}><input type="checkbox" checked={Boolean(validation?.validated)} disabled={!canValidate} onChange={validate}/>{validation?.validated?<CheckCircle2 size={15}/>:<span>Dir.</span>}</label>:<span className="mini-check empty"/>}</div>}
function TotalRow({label,value}:{label:string;value:number}){return <div className="cash-row total"><span>{label}</span><strong>{euro(value)}</strong><span className="mini-check empty"/></div>}
