import { useMemo, useState } from 'react';
import { ArrowLeft, CheckCircle2, ClipboardCheck, Plus, RefreshCw, Save, Trash2 } from 'lucide-react';
import { useOperationalStore } from './useOperationalStore';

type MealKey='breakfast'|'lunch'|'packedLunch'|'dinner'|'packedDinner';
type MealCell={pax?:number;time?:string;water?:boolean;wine?:boolean};
type MealDay={date:string;breakfast?:MealCell;lunch?:MealCell;packedLunch?:MealCell;dinner?:MealCell;packedDinner?:MealCell};
type ActualMeal={id?:string;date:string;service:MealKey;planned:number;actual:number;time:string;water:boolean;wine:boolean};
type Audit={id:string;action:string;actor:string;role:string;at:string};
type GroupControl={single:number;double:number;twin:number;triple:number;quadruple:number;babies:number;children3to6:number;children7to10:number;minors11to17:number;totalRooms:number;totalPax:number;adults:number;taxableAdults:number;leaderRoom:string;leaderPhone:string;directAgency:string;dmc:string;actualMeals:ActualMeal[];validatedBy:string;validatedAt:string;printedBy?:string;printedAt?:string;locked:boolean;commercialValidation?:'À valider'|'Validé';commercialValidatedBy?:string;commercialValidatedAt?:string};
type Group={id:string;name?:string;agency?:string;directAgency?:string;dmc?:string;arrival?:string;departure?:string;rooms?:number;pax?:number;status?:string;leaderRoom?:string;leaderPhone?:string;mealDays?:MealDay[];audit?:Audit[];groupControl?:GroupControl};
type SessionUser={name:string;role:string};

const EMPTY:GroupControl={single:0,double:0,twin:0,triple:0,quadruple:0,babies:0,children3to6:0,children7to10:0,minors11to17:0,totalRooms:0,totalPax:0,adults:0,taxableAdults:0,leaderRoom:'',leaderPhone:'',directAgency:'',dmc:'',actualMeals:[],validatedBy:'',validatedAt:'',locked:false};
const mealLabels:Record<MealKey,string>={breakfast:'Petit-déjeuner',lunch:'Déjeuner',packedLunch:'Panier midi',dinner:'Dîner',packedDinner:'Panier soir'};
function stamp(){return new Date().toLocaleString('fr-FR')}
function actor():SessionUser{try{const s=JSON.parse(localStorage.getItem('hospicore.session')||'{}');const u=s.user||{};return{name:`${u.firstName||'Utilisateur'} ${u.lastName||'HospiCore'}`.trim(),role:String(u.role?.name||u.role||'Réception')}}catch{return{name:'Utilisateur HospiCore',role:'Réception'}}}
function calc(v:GroupControl){const totalRooms=v.single+v.double+v.twin+v.triple+v.quadruple,totalPax=v.single+2*v.double+2*v.twin+3*v.triple+4*v.quadruple,minors=v.babies+v.children3to6+v.children7to10+v.minors11to17,adults=Math.max(0,totalPax-minors);return{...v,totalRooms,totalPax,adults,taxableAdults:adults,locked:false}}
function fmt(v?:string){return v?new Date(`${v}T12:00:00`).toLocaleDateString('fr-FR'):'—'}
function legacyMeals(g:Group):ActualMeal[]{return(g.mealDays||[]).flatMap(day=>(Object.keys(mealLabels) as MealKey[]).flatMap(service=>{const cell=day[service];if(!cell||(!cell.pax&&!cell.time))return[];const pax=Number(cell.pax||0);return[{id:crypto.randomUUID(),date:day.date,service,planned:pax,actual:pax,time:cell.time||'',water:Boolean(cell.water),wine:Boolean(cell.wine)}]}))}
function syncMealDays(days:MealDay[]|undefined,meals:ActualMeal[]):MealDay[]{const byDate=new Map<string,MealDay>((days||[]).map(day=>[day.date,{...day}]));for(const meal of meals){const day=byDate.get(meal.date)||{date:meal.date};byDate.set(meal.date,{...day,[meal.service]:{pax:Number(meal.actual||0),time:meal.time,water:meal.water,wine:meal.wine}})}return[...byDate.values()].sort((a,b)=>a.date.localeCompare(b.date))}

export function ReceptionControlsPage(){
 const store=useOperationalStore<Group[]>('group-360',[]),me=actor();
 const[selectedId,setSelectedId]=useState(''),[draft,setDraft]=useState<GroupControl>(EMPTY),[query,setQuery]=useState('');
 const groups=useMemo(()=>store.data.filter(g=>g.status!=='Parti'||Boolean(g.groupControl)).filter(g=>`${g.name||''} ${g.directAgency||g.agency||''} ${g.dmc||''}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>(a.arrival||'9999').localeCompare(b.arrival||'9999')||(a.name||'').localeCompare(b.name||'')),[store.data,query]);
 const selected=store.data.find(g=>g.id===selectedId);
 const pending=store.data.filter(g=>g.status!=='Parti'&&!g.groupControl?.validatedAt).length;
 function open(g:Group){const c=g.groupControl;const meals=c?.actualMeals?.length?c.actualMeals.map(m=>({...m,id:m.id||crypto.randomUUID()})):legacyMeals(g);setDraft(calc({...EMPTY,...c,leaderRoom:c?.leaderRoom||g.leaderRoom||'',leaderPhone:c?.leaderPhone||g.leaderPhone||'',directAgency:c?.directAgency||g.directAgency||g.agency||'',dmc:c?.dmc||g.dmc||'',actualMeals:meals,locked:false}));setSelectedId(g.id)}
 function numberField(key:keyof Pick<GroupControl,'single'|'double'|'twin'|'triple'|'quadruple'|'babies'|'children3to6'|'children7to10'|'minors11to17'>,value:number){setDraft(current=>calc({...current,[key]:Math.max(0,Number(value)||0)}))}
 function mealPatch(index:number,patch:Partial<ActualMeal>){setDraft(current=>({...current,actualMeals:current.actualMeals.map((meal,i)=>i===index?{...meal,...patch,planned:patch.actual!==undefined?Number(patch.actual):meal.planned}:meal)}))}
 function addMeal(){setDraft(current=>({...current,actualMeals:[...current.actualMeals,{id:crypto.randomUUID(),date:selected?.arrival||new Date().toISOString().slice(0,10),service:'breakfast',planned:0,actual:0,time:'07:00',water:false,wine:false}]}))}
 function removeMeal(index:number){setDraft(current=>({...current,actualMeals:current.actualMeals.filter((_,i)=>i!==index)}))}
 async function persist(validate=false){if(!selected)return;const at=stamp(),control=calc({...draft,validatedAt:validate?at:draft.validatedAt,validatedBy:validate?me.name:draft.validatedBy,commercialValidation:validate?(draft.commercialValidation==='Validé'?'Validé':'À valider'):draft.commercialValidation,locked:false});const audit:Audit={id:crypto.randomUUID(),action:validate?'Contrôle Groupe manuel validé':'Contrôle Groupe manuel enregistré',actor:me.name,role:me.role,at};const next=store.data.map(g=>g.id===selected.id?{...g,directAgency:control.directAgency,agency:control.directAgency||g.agency,dmc:control.dmc,leaderRoom:control.leaderRoom,leaderPhone:control.leaderPhone,mealDays:syncMealDays(g.mealDays,control.actualMeals),groupControl:control,audit:[...(g.audit||[]),audit]}:g);const ok=await store.saveImmediate(next);if(ok)setDraft(control)}
 return <main className="reception-daily-page"><header className="reception-daily-header"><button onClick={()=>location.href='/reception'}><ArrowLeft size={18}/>Espace Réception</button><p>Réception · Groupes</p><h1><ClipboardCheck size={30}/>Contrôle Groupe</h1><span>Saisie manuelle de référence. Les horaires et effectifs repas renseignés ici alimentent la feuille de route du veilleur.</span></header>
 <section className="reception-groups360"><header><div><p>Contrôles manuels</p><h2>Groupes à renseigner</h2></div><b>{pending} à compléter</b></header><div className="manual-control-toolbar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher un groupe ou une agence"/><button onClick={()=>void store.refresh()}><RefreshCw size={16}/>Actualiser</button></div><div className="reception-group-list">{groups.map(g=><article key={g.id} className={`reception-group360-card${selectedId===g.id?' open':''}`}><button className="reception-group360-summary" onClick={()=>open(g)}><span><strong>{g.name||'Groupe sans nom'}</strong><span>{fmt(g.arrival)} → {fmt(g.departure)} · {g.status||'Statut non renseigné'}</span></span><span className="reception-group360-status"><em>{g.groupControl?.validatedAt?'Validé':'À compléter'}</em></span></button></article>)}</div></section>
 {selected&&<section className="manual-group-control"><header><div><p>Contrôle en cours</p><h2>{selected.name||'Groupe sans nom'}</h2><span>{fmt(selected.arrival)} → {fmt(selected.departure)} · les données restent modifiables quel que soit le statut du groupe.</span></div><div><button className="control-save" onClick={()=>void persist(false)}><Save size={17}/>Enregistrer</button><button className="control-validate" onClick={()=>void persist(true)}><CheckCircle2 size={17}/>Valider le contrôle</button></div></header>
 <section className="control-print-summary"><div><span>Agence directe</span><input value={draft.directAgency} onChange={e=>setDraft(c=>({...c,directAgency:e.target.value}))}/></div><div><span>DMC</span><input value={draft.dmc} onChange={e=>setDraft(c=>({...c,dmc:e.target.value}))}/></div><div><span>Chambre guide</span><input value={draft.leaderRoom} onChange={e=>setDraft(c=>({...c,leaderRoom:e.target.value}))}/></div><div><span>Téléphone guide</span><input value={draft.leaderPhone} onChange={e=>setDraft(c=>({...c,leaderPhone:e.target.value}))}/></div></section>
 <section className="control-room-types"><h3>Chambres réellement occupées</h3><div>{([['single','Individuelles'],['double','Doubles'],['twin','Twins'],['triple','Triples'],['quadruple','Quadruples']] as const).map(([key,label])=><label key={key}><span>{label}</span><input type="number" min="0" value={draft[key]} onChange={e=>numberField(key,Number(e.target.value))}/></label>)}</div></section>
 <section className="control-age-groups"><h3>Mineurs / réductions</h3><div>{([['babies','Bébés'],['children3to6','3–6 ans'],['children7to10','7–10 ans'],['minors11to17','11–17 ans']] as const).map(([key,label])=><label key={key}><span>{label}</span><input type="number" min="0" value={draft[key]} onChange={e=>numberField(key,Number(e.target.value))}/></label>)}</div></section>
 <section className="control-results"><article><span>Chambres</span><strong>{draft.totalRooms}</strong></article><article><span>Personnes</span><strong>{draft.totalPax}</strong></article><article><span>Adultes</span><strong>{draft.adults}</strong></article><article><span>Taxes</span><strong>{draft.taxableAdults}</strong></article></section>
 <section className="control-meal-table manual-meals"><header><div><h3>Horaires & effectifs repas</h3><p>Ces lignes sont la source utilisée par la feuille de route du veilleur.</p></div><button onClick={addMeal}><Plus size={16}/>Ajouter un repas</button></header>{draft.actualMeals.length===0?<p className="manual-control-empty">Aucun repas renseigné. Ajoutez chaque service manuellement.</p>:<table><thead><tr><th>Date</th><th>Service</th><th>Heure</th><th>Effectif</th><th>Eau</th><th>Vin</th><th></th></tr></thead><tbody>{draft.actualMeals.map((meal,index)=><tr key={meal.id||`${meal.date}-${meal.service}-${index}`}><td><input type="date" value={meal.date} onChange={e=>mealPatch(index,{date:e.target.value})}/></td><td><select value={meal.service} onChange={e=>mealPatch(index,{service:e.target.value as MealKey})}>{(Object.keys(mealLabels) as MealKey[]).map(key=><option key={key} value={key}>{mealLabels[key]}</option>)}</select></td><td><input type="time" value={meal.time} onChange={e=>mealPatch(index,{time:e.target.value})}/></td><td><input type="number" min="0" value={meal.actual} onChange={e=>mealPatch(index,{actual:Math.max(0,Number(e.target.value)||0)})}/></td><td><input type="checkbox" checked={meal.water} onChange={e=>mealPatch(index,{water:e.target.checked})}/></td><td><input type="checkbox" checked={meal.wine} onChange={e=>mealPatch(index,{wine:e.target.checked})}/></td><td><button className="meal-delete" onClick={()=>removeMeal(index)} title="Supprimer"><Trash2 size={15}/></button></td></tr>)}</tbody></table>}</section>
 <footer className="manual-control-footer"><span>{draft.validatedAt?`Dernière validation : ${draft.validatedAt} · ${draft.validatedBy}`:'Contrôle non validé'}</span><div><button className="control-save" onClick={()=>void persist(false)}><Save size={17}/>Enregistrer</button><button className="control-validate" onClick={()=>void persist(true)}><CheckCircle2 size={17}/>Valider le contrôle</button></div></footer></section>}
 </main>
}
