import { FormEvent, useEffect, useMemo, useState } from 'react';
import { ArrowLeft, CalendarClock, CheckCircle2, ChevronDown, ChevronRight, Clock3, MessageSquarePlus, Plus, RefreshCw, Search, UserRound, UsersRound, X } from 'lucide-react';
import { useOperationalStore } from './useOperationalStore';

type TaskStatus='À faire'|'En cours'|'En attente'|'Terminée'; type Priority='Faible'|'Normale'|'Haute'|'Critique';
type HistoryEntry={id:string;action:string;actor:string;role:string;at:string;comment?:string};
type Task={id:string;reference:string;title:string;description:string;service:string;assignee:string;assigneeId?:string;assignmentType?:'user'|'service';priority:Priority;status:TaskStatus;dueAt:string;linkedTo:string;createdAt?:string;history:HistoryEntry[]};
type Account={id:string;firstName:string;lastName:string;role:string;roleLabel?:string;baseRole?:string;status?:string};
const columns:TaskStatus[]=['À faire','En cours','En attente','Terminée']; const services=['Tous','Réception','Commercial','Maintenance','Direction'];
function session(){try{return JSON.parse(localStorage.getItem('hospicore.session')||'{}')}catch{return{}}}
function token(){return session()?.token||localStorage.getItem('hospicore.token')||''}
function currentUser(){const u=session()?.user||{};return{id:String(u.id||''),name:`${u.firstName||'Utilisateur'} ${u.lastName||'HospiCore'}`.trim(),role:String(u.role?.name||u.role||'Collaborateur'),service:serviceForRole(String(u.role?.baseRole||u.role?.name||u.role||''))};}
function serviceForRole(value:string){const r=value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();if(r.includes('direction')||r.includes('directeur')||r.includes('admin'))return'Direction';if(r.includes('commercial')||r.includes('vente'))return'Commercial';if(r.includes('maintenance')||r.includes('tech'))return'Maintenance';if(r.includes('reception')||r.includes('front'))return'Réception';return'';}
function stamp(){return new Date().toLocaleString('fr-FR',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit'});} function cleanTasks(items:Task[]){return items.filter(i=>!['Housekeeping','Restaurant','Cuisine'].includes(i.service));}
async function loadUsers(){try{const r=await fetch('/api/auth/directory',{headers:{Authorization:`Bearer ${token()}`}});if(!r.ok)return[];return await r.json() as Account[]}catch{return[]}}
export function TasksPage(){
 const store=useOperationalStore<Task[]>('tasks',[]),items=useMemo(()=>cleanTasks(store.data),[store.data]),me=currentUser();
 const[open,setOpen]=useState(false),[query,setQuery]=useState(''),[service,setService]=useState('Tous'),[commentTask,setCommentTask]=useState<Task|null>(null),[mineOpen,setMineOpen]=useState(true),[assignmentType,setAssignmentType]=useState<'user'|'service'>('user'),[users,setUsers]=useState<Account[]>([]);
 useEffect(()=>{void loadUsers().then(setUsers)},[]);
 const myTasks=useMemo(()=>items.filter(t=>t.status!=='Terminée'&&((t.assignmentType==='user'||t.assigneeId)?t.assigneeId===me.id:t.service===me.service)),[items,me.id,me.service]);
 const filtered=useMemo(()=>items.filter(t=>(service==='Tous'||t.service===service)&&`${t.reference} ${t.title} ${t.description} ${t.assignee} ${t.linkedTo}`.toLowerCase().includes(query.toLowerCase())),[items,query,service]);
 async function commit(next:Task[]){return store.save(cleanTasks(next));}
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),u=currentUser(),kind=String(f.get('assignmentType')||'user') as 'user'|'service';let targetService='',assignee='',assigneeId='';if(kind==='user'){const selected=users.find(x=>x.id===String(f.get('assigneeId')||''));if(!selected)return;assigneeId=selected.id;assignee=`${selected.firstName} ${selected.lastName}`.trim();targetService=serviceForRole(selected.baseRole||selected.role||selected.roleLabel||'');}else{targetService=String(f.get('service')||'');assignee=`Service ${targetService}`;}const v:Task={id:crypto.randomUUID(),reference:`T-${new Date().getFullYear()}-${String(items.length+1).padStart(6,'0')}`,title:String(f.get('title')||''),description:String(f.get('description')||''),service:targetService,assignee,assigneeId,assignmentType:kind,priority:String(f.get('priority')) as Priority,status:'À faire',dueAt:String(f.get('dueAt')||''),linkedTo:String(f.get('linkedTo')||''),createdAt:new Date().toISOString(),history:[{id:crypto.randomUUID(),action:`Tâche créée et assignée à ${assignee}`,actor:u.name,role:u.role,at:stamp()}]};if(await commit([v,...items]))setOpen(false);}
 async function move(id:string,status:TaskStatus,comment=''){const u=currentUser(),next=items.map(t=>t.id===id?{...t,status,history:[...(t.history||[]),{id:crypto.randomUUID(),action:`Statut modifié : ${status}`,actor:u.name,role:u.role,at:stamp(),comment:comment||undefined}]}:t);if(await commit(next))setCommentTask(null);}
 const card=(t:Task)=><article className="task-card" key={t.id}><div className="task-card-top"><span className={`task-priority ${t.priority.toLowerCase()}`}>{t.priority}</span><small>{t.reference}</small></div><h3>{t.title}</h3><p>{t.description}</p><div className="task-meta"><span>{t.assignmentType==='service'?<UsersRound size={14}/>:<UserRound size={14}/>} {t.assignee||t.service}</span><span><Clock3 size={14}/>{t.dueAt.replace('T',' ')}</span><span>{t.service}</span>{t.linkedTo&&<span>{t.linkedTo}</span>}</div><div className="task-actions">{t.status!=='En cours'&&t.status!=='Terminée'&&<button disabled={store.rawState==='saving'} onClick={()=>void move(t.id,'En cours')}>Démarrer</button>}{t.status==='En cours'&&<button disabled={store.rawState==='saving'} onClick={()=>void move(t.id,'En attente')}>Mettre en attente</button>}{t.status!=='Terminée'&&<button disabled={store.rawState==='saving'} onClick={()=>setCommentTask(t)}><CheckCircle2 size={15}/>Terminer</button>}</div><details><summary>Historique signé</summary>{(t.history||[]).map(h=><div className="task-history" key={h.id}><strong>{h.action}</strong><small>{h.actor} · {h.role} · {h.at}</small>{h.comment&&<p>{h.comment}</p>}</div>)}</details></article>;
 return <div className="tasks-page"><header className="tasks-header"><div><button onClick={()=>location.href='/'}><ArrowLeft size={18}/>Tableau de bord</button><p>HospiCore · Coordination</p><h1>Tâches</h1><span>Actions assignées à un collaborateur ou à un service.</span></div><div className="tasks-header-actions"><div className={`tasks-sync ${store.rawState}`}><RefreshCw size={17}/><div><strong>{store.message}</strong>{store.lastSuccessAt&&<small>Dernière mise à jour : {new Date(store.lastSuccessAt).toLocaleString('fr-FR')}</small>}</div></div><button className="tasks-primary" onClick={()=>setOpen(true)}><Plus size={18}/>Nouvelle tâche</button></div></header>
 <section className="my-tasks"><button className="my-tasks-toggle" onClick={()=>setMineOpen(v=>!v)}>{mineOpen?<ChevronDown size={18}/>:<ChevronRight size={18}/>}<strong>Mes tâches</strong><span>{myTasks.length}</span></button>{mineOpen&&<div className="my-tasks-list">{myTasks.length?myTasks.map(card):<p className="my-tasks-empty">Aucune tâche en cours ne vous est assignée.</p>}</div>}</section>
 <section className="tasks-kpis"><article><Clock3/><span>À faire</span><strong>{items.filter(t=>t.status==='À faire').length}</strong></article><article><CalendarClock/><span>En cours</span><strong>{items.filter(t=>t.status==='En cours').length}</strong></article><article><CheckCircle2/><span>Terminées</span><strong>{items.filter(t=>t.status==='Terminée').length}</strong></article></section>
 <div className="tasks-toolbar"><label><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher une tâche…"/></label><select value={service} onChange={e=>setService(e.target.value)}>{services.map(s=><option key={s}>{s}</option>)}</select></div>
 <section className="tasks-board">{columns.map(col=><div className="task-column" key={col}><header><h2>{col}</h2><span>{filtered.filter(t=>t.status===col).length}</span></header>{filtered.filter(t=>t.status===col).map(card)}</div>)}</section>
 {open&&<div className="tasks-modal"><form onSubmit={e=>void create(e)}><header><div><p>Nouvelle action</p><h2>Créer une tâche</h2></div><button type="button" onClick={()=>setOpen(false)}><X/></button></header><div className="tasks-form"><label className="wide">Titre<input name="title" required/></label><label>Type d’assignation<select name="assignmentType" value={assignmentType} onChange={e=>setAssignmentType(e.target.value as 'user'|'service')}><option value="user">Utilisateur existant</option><option value="service">Service entier</option></select></label>{assignmentType==='user'?<label>Utilisateur<select name="assigneeId" required defaultValue=""><option value="" disabled>Choisir un utilisateur…</option>{users.map(u=><option value={u.id} key={u.id}>{u.firstName} {u.lastName} · {serviceForRole(u.baseRole||u.role||u.roleLabel||'')}</option>)}</select></label>:<label>Service<select name="service" required>{services.slice(1).map(s=><option key={s}>{s}</option>)}</select></label>}<label>Priorité<select name="priority"><option>Faible</option><option>Normale</option><option>Haute</option><option>Critique</option></select></label><label>Échéance<input type="datetime-local" name="dueAt" required/></label><label className="wide">Lié à<input name="linkedTo" placeholder="Groupe, chambre, salle…"/></label><label className="wide">Description<textarea name="description" required/></label></div><footer><button type="button" onClick={()=>setOpen(false)}>Annuler</button><button className="tasks-primary" disabled={store.rawState==='saving'} type="submit">Créer et notifier</button></footer></form></div>}
 {commentTask&&<div className="tasks-modal"><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void move(commentTask.id,'Terminée',String(f.get('comment')||''));}}><header><div><p>Clôture</p><h2>Terminer la tâche</h2></div><button type="button" onClick={()=>setCommentTask(null)}><X/></button></header><label className="task-comment"><MessageSquarePlus size={18}/>Commentaire de clôture<textarea name="comment" required/></label><footer><button type="button" onClick={()=>setCommentTask(null)}>Annuler</button><button className="tasks-primary" disabled={store.rawState==='saving'} type="submit">Terminer et synchroniser</button></footer></form></div>}
 </div>;
}
