import { FormEvent, useEffect, useMemo, useState } from 'react';
import { ArrowLeft, CalendarClock, CheckCircle2, ChevronDown, ChevronRight, Clock3, MessageSquarePlus, Plus, RefreshCw, Search, UserRound, UsersRound, X } from 'lucide-react';
import { useOperationalStore } from './useOperationalStore';

type TaskStatus='À faire'|'En cours'|'En attente'|'Terminée';
type Priority='Faible'|'Normale'|'Haute'|'Critique';
type HistoryEntry={id:string;action:string;actor:string;role:string;at:string;comment?:string};
type Task={id:string;reference:string;title:string;description:string;service:string;assignee:string;assigneeId?:string;assignmentType?:'user'|'service';priority:Priority;status:TaskStatus;dueAt:string;linkedTo:string;createdAt?:string;completedAt?:string;history:HistoryEntry[]};
type Account={id:string;firstName:string;lastName:string;email?:string;role:string;roleLabel?:string;baseRole?:string;service?:string;status?:string};

const services=['Tous','Réception','Commercial','Maintenance','Direction'];
function session(){try{return JSON.parse(localStorage.getItem('hospicore.session')||'{}')}catch{return{}}}
function token(){return session()?.token||localStorage.getItem('hospicore.token')||''}
function serviceForRole(v:string){const r=v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();if(r.includes('direction')||r.includes('directeur')||r.includes('admin'))return'Direction';if(r.includes('commercial'))return'Commercial';if(r.includes('maintenance')||r.includes('tech'))return'Maintenance';if(r.includes('reception')||r.includes('front')||r.includes('veilleur'))return'Réception';return''}
function currentUser(){const u=session()?.user||{};return{id:String(u.id||''),name:`${u.firstName||'Utilisateur'} ${u.lastName||'HospiCore'}`.trim(),role:String(u.role?.name||u.role||'Collaborateur'),service:serviceForRole(String(u.role?.baseRole||u.role?.name||u.role||''))}}
function stamp(){return new Date().toLocaleString('fr-FR',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit'})}
function clean(items:Task[]){return items.filter(i=>!['Housekeeping','Restaurant','Cuisine'].includes(i.service))}
function normalizeDirectory(body:unknown):Account[]{const raw=Array.isArray(body)?body:(body&&typeof body==='object'&&'users' in body&&Array.isArray((body as {users?:unknown[]}).users)?(body as {users:Account[]}).users:[]);return (raw as Account[]).filter(u=>u&&u.id&&u.status!=='INACTIVE').sort((a,b)=>`${a.lastName} ${a.firstName}`.localeCompare(`${b.lastName} ${b.firstName}`,'fr'))}
async function loadDirectory():Promise<Account[]>{const auth=token();if(!auth)throw new Error('Session utilisateur indisponible. Reconnectez-vous à HospiCore.');const response=await fetch('/api/auth/directory',{cache:'no-store',headers:{Authorization:`Bearer ${auth}`}});const body=await response.json().catch(()=>[]);if(!response.ok){const message=Array.isArray((body as {message?:unknown}).message)?(body as {message:string[]}).message.join(' · '):String((body as {message?:string}).message||`Erreur HTTP ${response.status}`);throw new Error(message)}return normalizeDirectory(body)}
function visibleToUser(task:Task,me:{id:string;service:string}){if(task.assignmentType==='user'||Boolean(task.assigneeId))return Boolean(task.assigneeId)&&task.assigneeId===me.id;return Boolean(task.service)&&task.service===me.service}

export function TasksPage(){
 const store=useOperationalStore<Task[]>('tasks',[]),items=useMemo(()=>clean(store.data),[store.data]),me=currentUser();
 const[open,setOpen]=useState(false),[query,setQuery]=useState(''),[service,setService]=useState('Tous'),[commentTask,setCommentTask]=useState<Task|null>(null),[mineOpen,setMineOpen]=useState(true),[assignmentType,setAssignmentType]=useState<'user'|'service'>('user'),[users,setUsers]=useState<Account[]>([]),[usersLoading,setUsersLoading]=useState(false),[usersError,setUsersError]=useState('');
 async function refreshUsers(){setUsersLoading(true);setUsersError('');try{const directory=await loadDirectory();setUsers(directory);if(!directory.length)setUsersError('Aucun compte utilisateur actif n’est disponible pour l’assignation.')}catch(error){setUsers([]);setUsersError(error instanceof Error?error.message:'Impossible de charger les utilisateurs.')}finally{setUsersLoading(false)}}
 useEffect(()=>{void refreshUsers()},[]);
 function openCreate(){setOpen(true);void refreshUsers()}
 const active=items.filter(t=>t.status!=='Terminée');
 const visibleActive=active.filter(t=>visibleToUser(t,me));
 const myTasks=visibleActive;
 const filtered=visibleActive.filter(t=>(service==='Tous'||t.service===service)&&`${t.reference} ${t.title} ${t.description} ${t.assignee} ${t.linkedTo}`.toLowerCase().includes(query.toLowerCase()));
 async function commit(next:Task[]){return store.save(clean(next))}
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),u=currentUser(),kind=String(f.get('assignmentType')||'user') as 'user'|'service';let targetService='',assignee='',assigneeId='';if(kind==='user'){const x=users.find(v=>v.id===String(f.get('assigneeId')||''));if(!x){setUsersError('Sélectionnez un utilisateur actif avant de créer la tâche.');return}assigneeId=x.id;assignee=`${x.firstName} ${x.lastName}`.trim();targetService=x.service||serviceForRole(x.baseRole||x.role||x.roleLabel||'Réception')||'Réception'}else{targetService=String(f.get('service')||'');assignee=`Service ${targetService}`}const v:Task={id:crypto.randomUUID(),reference:`T-${new Date().getFullYear()}-${String(items.length+1).padStart(6,'0')}`,title:String(f.get('title')||''),description:String(f.get('description')||''),service:targetService,assignee,assigneeId,assignmentType:kind,priority:String(f.get('priority')) as Priority,status:'À faire',dueAt:String(f.get('dueAt')||''),linkedTo:String(f.get('linkedTo')||''),createdAt:new Date().toISOString(),history:[{id:crypto.randomUUID(),action:`Tâche créée et assignée à ${assignee}`,actor:u.name,role:u.role,at:stamp()}]};if(await commit([v,...items]))setOpen(false)}
 async function move(id:string,status:TaskStatus,comment=''){const u=currentUser(),now=new Date().toISOString(),next=items.map(t=>t.id===id?{...t,status,completedAt:status==='Terminée'?now:t.completedAt,history:[...(t.history||[]),{id:crypto.randomUUID(),action:`Statut modifié : ${status}`,actor:u.name,role:u.role,at:stamp(),comment:comment||undefined}]}:t);if(await commit(next))setCommentTask(null)}
 const card=(t:Task)=><article className="task-card" key={t.id}><div className="task-card-top"><span className={`task-priority ${t.priority.toLowerCase()}`}>{t.priority}</span><small>{t.reference}</small></div><h3>{t.title}</h3><p>{t.description}</p><div className="task-meta"><span>{t.assignmentType==='service'?<UsersRound size={14}/>:<UserRound size={14}/>} {t.assignee||t.service}</span><span><Clock3 size={14}/>{t.dueAt.replace('T',' ')}</span><span>{t.service}</span></div><div className="task-actions">{t.status!=='En cours'&&<button onClick={()=>void move(t.id,'En cours')}>Démarrer</button>}{t.status==='En cours'&&<button onClick={()=>void move(t.id,'En attente')}>Mettre en attente</button>}<button onClick={()=>setCommentTask(t)}><CheckCircle2 size={15}/>Terminer</button></div></article>;
 return <div className="tasks-page"><header className="tasks-header"><div><button onClick={()=>location.href='/'}><ArrowLeft size={18}/>Tableau de bord</button><p>HospiCore · Coordination</p><h1>Tâches</h1><span>Une tâche nominative n’est visible que par son destinataire. Les tâches de service sont visibles uniquement par les membres du service concerné.</span></div><div className="tasks-header-actions"><div className={`tasks-sync ${store.rawState}`}><RefreshCw size={17}/><strong>{store.message}</strong></div><button className="tasks-primary" onClick={openCreate}><Plus size={18}/>Nouvelle tâche</button></div></header>
 <section className="my-tasks"><button className="my-tasks-toggle" onClick={()=>setMineOpen(v=>!v)}>{mineOpen?<ChevronDown/>:<ChevronRight/>}<strong>Mes tâches</strong><span>{myTasks.length}</span></button>{mineOpen&&<div className="my-tasks-list">{myTasks.length?myTasks.map(card):<p className="my-tasks-empty">Aucune tâche en cours ne vous est assignée.</p>}</div>}</section>
 <section className="tasks-kpis"><article><Clock3/><span>À faire</span><strong>{visibleActive.filter(t=>t.status==='À faire').length}</strong></article><article><CalendarClock/><span>En cours / attente</span><strong>{visibleActive.filter(t=>t.status!=='À faire').length}</strong></article></section>
 <div className="tasks-toolbar"><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher une tâche…"/></label><select value={service} onChange={e=>setService(e.target.value)}>{services.map(s=><option key={s}>{s}</option>)}</select></div><section className="tasks-board">{(['À faire','En cours','En attente'] as TaskStatus[]).map(col=><div className="task-column" key={col}><header><h2>{col}</h2><span>{filtered.filter(t=>t.status===col).length}</span></header>{filtered.filter(t=>t.status===col).map(card)}</div>)}</section>
 {open&&<div className="tasks-modal"><form onSubmit={e=>void create(e)}><header><div><p>Nouvelle action</p><h2>Créer une tâche</h2></div><button type="button" onClick={()=>setOpen(false)}><X/></button></header><div className="tasks-form"><label className="wide">Titre<input name="title" required/></label><label>Type d’assignation<select name="assignmentType" value={assignmentType} onChange={e=>setAssignmentType(e.target.value as 'user'|'service')}><option value="user">Utilisateur existant</option><option value="service">Service entier</option></select></label>{assignmentType==='user'?<label>Utilisateur<select name="assigneeId" required defaultValue="" disabled={usersLoading||users.length===0}><option value="" disabled>{usersLoading?'Chargement des utilisateurs…':users.length?'Choisir un utilisateur…':'Aucun utilisateur disponible'}</option>{users.map(u=><option value={u.id} key={u.id}>{u.firstName} {u.lastName}{u.roleLabel?` · ${u.roleLabel}`:''}</option>)}</select>{usersError&&<small className="task-user-error">{usersError} <button type="button" onClick={()=>void refreshUsers()}>Réessayer</button></small>}</label>:<label>Service<select name="service">{services.slice(1).map(s=><option key={s}>{s}</option>)}</select></label>}<label>Priorité<select name="priority"><option>Faible</option><option>Normale</option><option>Haute</option><option>Critique</option></select></label><label>Échéance<input type="datetime-local" name="dueAt" required/></label><label className="wide">Lié à<input name="linkedTo"/></label><label className="wide">Description<textarea name="description" required/></label></div><footer><button type="button" onClick={()=>setOpen(false)}>Annuler</button><button className="tasks-primary" type="submit" disabled={assignmentType==='user'&&(usersLoading||users.length===0)}>Créer et notifier</button></footer></form></div>}
 {commentTask&&<div className="tasks-modal"><form onSubmit={e=>{e.preventDefault();void move(commentTask.id,'Terminée',String(new FormData(e.currentTarget).get('comment')||''))}}><header><h2>Terminer la tâche</h2><button type="button" onClick={()=>setCommentTask(null)}><X/></button></header><label className="task-comment"><MessageSquarePlus/>Commentaire de clôture<textarea name="comment" required/></label><footer><button type="button" onClick={()=>setCommentTask(null)}>Annuler</button><button className="tasks-primary" type="submit">Terminer et archiver</button></footer></form></div>}</div>
}
