import { Dispatch, SetStateAction, useCallback, useEffect, useRef, useState } from 'react';
import { loadSharedData, saveSharedData } from './operational-sync';

export type OperationalSyncState = 'loading' | 'synced' | 'saving' | 'error' | 'conflict';
export type OperationalStore<T> = {data:T;setData:Dispatch<SetStateAction<T>>;version:number;updatedAt:string;lastSuccessAt:string;state:OperationalSyncState;rawState:OperationalSyncState;rawMessage:string;message:string;refresh:(silent?:boolean)=>Promise<boolean>;save:(next:T)=>Promise<boolean>};
export type OperationalChangeDetail = {namespace:string;version:number;at:number;source:'local'|'remote'};
const DEFAULT_REFRESH_MS=10_000;
function emitOperationalChange(detail:OperationalChangeDetail){window.dispatchEvent(new CustomEvent<OperationalChangeDetail>('hospicore:operational-change',{detail}));}

export function useOperationalStore<T>(namespace:string,initialValue:T,refreshMs=DEFAULT_REFRESH_MS):OperationalStore<T>{
 const initialValueRef=useRef(initialValue),[data,setData]=useState<T>(()=>initialValueRef.current),[version,setVersion]=useState(0),versionRef=useRef(0),refreshInFlightRef=useRef(false),mountedRef=useRef(true),channelRef=useRef<BroadcastChannel|null>(null),[updatedAt,setUpdatedAt]=useState(''),[lastSuccessAt,setLastSuccessAt]=useState(''),[state,setState]=useState<OperationalSyncState>('loading'),[message,setMessage]=useState('Connexion à PostgreSQL…');
 const markSuccess=useCallback((payload:T,nextVersion:number,successMessage:string)=>{if(!mountedRef.current)return;const successAt=new Date().toISOString();setData(payload);setVersion(nextVersion);versionRef.current=nextVersion;setUpdatedAt(successAt);setLastSuccessAt(successAt);setState('synced');setMessage(successMessage);},[]);
 const refresh=useCallback(async(silent=false):Promise<boolean>=>{if(refreshInFlightRef.current)return false;refreshInFlightRef.current=true;if(!silent&&mountedRef.current){setState('loading');setMessage('Synchronisation en cours…');}try{const previousVersion=versionRef.current,result=await loadSharedData<T>(namespace,initialValueRef.current);if(!mountedRef.current)return false;if(!result.connected){setState('error');setMessage(result.error||'Synchronisation PostgreSQL indisponible.');return false;}markSuccess(result.payload,result.version,'Données partagées à jour');if(silent&&previousVersion>0&&result.version>previousVersion)emitOperationalChange({namespace,version:result.version,at:Date.now(),source:'remote'});return true;}catch(error){if(!mountedRef.current)return false;setState('error');setMessage(error instanceof Error?error.message:'Synchronisation PostgreSQL indisponible.');return false;}finally{refreshInFlightRef.current=false;}},[markSuccess,namespace]);
 const save=useCallback(async(next:T):Promise<boolean>=>{if(mountedRef.current){setState('saving');setMessage('Enregistrement partagé…');}try{const result=await saveSharedData<T>(namespace,next,versionRef.current);if(!mountedRef.current)return false;markSuccess(result.payload,result.version,'Enregistré pour tous les services');const detail:OperationalChangeDetail={namespace,version:result.version,at:Date.now(),source:'local'};emitOperationalChange(detail);channelRef.current?.postMessage(detail);return true;}catch(error){if(!mountedRef.current)return false;const text=error instanceof Error?error.message:'Enregistrement impossible.';const conflict=text.includes('autre personne');setState(conflict?'conflict':'error');setMessage(text);if(conflict)window.setTimeout(()=>void refresh(true),250);return false;}},[markSuccess,namespace,refresh]);
 useEffect(()=>{mountedRef.current=true;void refresh();const timer=window.setInterval(()=>{if(document.visibilityState==='visible'&&navigator.onLine)void refresh(true);},Math.max(5_000,refreshMs));const refreshWhenActive=()=>{if(document.visibilityState==='visible'&&navigator.onLine)void refresh(true);};const refreshOnOperationalChange=(event:Event)=>{const detail=(event as CustomEvent<OperationalChangeDetail>).detail;if(detail?.namespace===namespace&&detail.version>versionRef.current)void refresh(true);};window.addEventListener('focus',refreshWhenActive);window.addEventListener('online',refreshWhenActive);window.addEventListener('hospicore:operational-change',refreshOnOperationalChange as EventListener);document.addEventListener('visibilitychange',refreshWhenActive);if('BroadcastChannel'in window){const channel=new BroadcastChannel(`hospicore-sync-${namespace}`);channelRef.current=channel;channel.onmessage=(event:MessageEvent<OperationalChangeDetail>)=>{if(!event.data?.version||event.data.version>versionRef.current)void refresh(true);};}return()=>{mountedRef.current=false;window.clearInterval(timer);window.removeEventListener('focus',refreshWhenActive);window.removeEventListener('online',refreshWhenActive);window.removeEventListener('hospicore:operational-change',refreshOnOperationalChange as EventListener);document.removeEventListener('visibilitychange',refreshWhenActive);channelRef.current?.close();channelRef.current=null;};},[namespace,refresh,refreshMs]);
 const publicMessage=state==='synced'?(lastSuccessAt?`PostgreSQL à jour · ${new Date(lastSuccessAt).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit',second:'2-digit'})}`:'Données opérationnelles disponibles'):message;
 return{data,setData,version,updatedAt,lastSuccessAt,state,rawState:state,rawMessage:message,message:publicMessage,refresh,save};
}
