import { useEffect, useMemo, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { CheckCircle2, ChevronDown, LogOut, ShieldCheck, UserRound } from 'lucide-react';
import { capabilitiesForRole, roleFromValue, type Capability } from './permissions';

type SessionRole=string|{name?:string;label?:string;baseRole?:string};
type SessionUser={firstName?:string;lastName?:string;email?:string;role?:SessionRole;permissions?:string[]};
type Session={user?:SessionUser};
const labels:Record<Capability,string>={'dashboard.view':'Centre de Commandement','reception.view':'Réception · lecture','reception.operate':'Réception · opérations','cash.view':'Caisse · consulter','cash.edit':'Caisse · saisir et verrouiller','cash.validate':'Caisse · validation Direction','group-control.create':'Contrôles Groupe','group-control.unlock':'Déverrouillage des contrôles','commercial.view':'Commercial · lecture','commercial.edit':'Commercial · modification','commercial.validate-control':'Validation commerciale','maintenance.view':'Maintenance · lecture','maintenance.create':'Créer une intervention','maintenance.manage':'Piloter la maintenance','planning.view':'Planning opérationnel','meeting-rooms.view':'Salles de réunion · lecture','meeting-rooms.edit':'Salles de réunion · modification','tasks.view':'Tâches · lecture','tasks.edit':'Tâches · modification','instructions.view':'Consignes · lecture et accusé de lecture','instructions.edit':'Consignes · publication','operations-center.view':'Centre des opérations · lecture','operations-center.edit':'Centre des opérations · modification','journal.view':'Journal d’exploitation','direction-reports.view':'Rapports Direction','diagnostic.view':'Diagnostic','administration.view':'Administration'};
function readSession():Session{try{return JSON.parse(localStorage.getItem('hospicore.session')||'{}')}catch{return{}}}
function roleLabel(role?:SessionRole){if(typeof role==='object'&&role)return role.label||role.name||'Utilisateur';return String(role||'Utilisateur')}
export function UserAccountMenu(){
 const[open,setOpen]=useState(false),[anchor,setAnchor]=useState<HTMLElement|null>(null);const root=useRef<HTMLDivElement>(null);const session=readSession(),user=session.user||{};
 const name=`${user.firstName||'Utilisateur'} ${user.lastName||''}`.trim(),initials=`${user.firstName?.[0]||'H'}${user.lastName?.[0]||'C'}`.toUpperCase(),baseRole=roleFromValue(user.role);
 const effective=useMemo(()=>{const explicit=Array.isArray(user.permissions)?user.permissions.filter((v):v is Capability=>v in labels):null;return explicit||capabilitiesForRole(baseRole)},[baseRole,user.permissions]);
 const nightExtras=baseRole==='night_auditor'?['Plaintes · consulter, saisir et traiter','Feuille de route veilleur · accès complet']:[];
 useEffect(()=>{const find=()=>setAnchor(document.querySelector<HTMLElement>('.live-v2-user'));find();const observer=new MutationObserver(find);observer.observe(document.body,{childList:true,subtree:true});return()=>observer.disconnect()},[]);
 useEffect(()=>{function close(e:MouseEvent){if(root.current&&!root.current.contains(e.target as Node))setOpen(false)}function key(e:KeyboardEvent){if(e.key==='Escape')setOpen(false)}document.addEventListener('mousedown',close);document.addEventListener('keydown',key);return()=>{document.removeEventListener('mousedown',close);document.removeEventListener('keydown',key)}},[]);
 function logout(){localStorage.removeItem('hospicore.session');localStorage.removeItem('hospicore.token');location.assign('/')}
 if(!anchor)return null;
 return createPortal(<div className="user-account" ref={root}><button className="user-account-trigger" onClick={()=>setOpen(v=>!v)} aria-expanded={open} aria-haspopup="menu" title="Mon compte"><span className="user-account-avatar">{initials}</span><ChevronDown size={15}/></button>{open&&<section className="user-account-menu" role="menu"><header><span className="user-account-large-avatar">{initials}</span><div><strong>{name}</strong><small>{user.email||'Adresse e-mail non renseignée'}</small><b>{roleLabel(user.role)}</b></div></header><div className="user-account-rights-head"><div><ShieldCheck size={17}/><strong>Mes droits</strong></div><span>{effective.length+nightExtras.length}</span></div><p className="user-account-rights-note">Lecture seule · droits effectivement appliqués à ce compte</p><div className="user-account-rights">{effective.length||nightExtras.length?<>{effective.map(cap=><div key={cap}><CheckCircle2 size={14}/><span>{labels[cap]}</span></div>)}{nightExtras.map(item=><div key={item}><CheckCircle2 size={14}/><span>{item}</span></div>)}</>:<div className="empty"><UserRound size={15}/><span>Aucun droit attribué</span></div>}</div><footer><button onClick={logout}><LogOut size={17}/>Déconnexion</button></footer></section>}</div>,anchor);
}
