import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, CalendarDays, CheckCircle2, ChevronLeft, ChevronRight, LockKeyhole, Printer, RefreshCw, ShieldCheck } from 'lucide-react';
import { useOperationalStore } from './useOperationalStore';

type SheetStatus='Préparation'|'Prête à imprimer'|'Diffusée'|'Clôturée';
type LineStatus='À relire'|'Validée';
type MealCell={pax?:number;time?:string;water?:boolean;wine?:boolean};
type MealDay={date:string;breakfast?:MealCell;lunch?:MealCell;packedLunch?:MealCell;dinner?:MealCell;packedDinner?:MealCell;lodging?:MealCell};
type FunctionLine={id:string;groupId:string;commercial:string;groupName:string;nationality:string;stayType:string;groupStatus:string;remarks:string;leaderFirstName:string;leaderLastName:string;leaderPhone:string;leaderEmail:string;arrivalDate:string;arrivalTime:string;arrivalService:string;departureDate:string;departureTime:string;lastService:string;roomingReceived:boolean;luggageArrival:string;luggageDeparture:string;paymentStatus:string;amountDue:number;debtor:string;depositReceived:boolean;breakfastType:string;mealSummary:string;dietary:string;roomService:string;earlyCheckIn:string;lateCheckOut:string;lineStatus:LineStatus;validatedBy:string;validatedAt:string;departureConfirmed:boolean};
type LegacyLine=FunctionLine&{restaurantSummary?:string;cuisineSummary?:string;housekeepingType?:string};
type WeeklySheet={id:string;weekStart:string;weekEnd:string;status:SheetStatus;lines:LegacyLine[];validatedForPrintBy:string;validatedForPrintAt:string;lockedBy:string;lockedAt:string};
type Audit={actor?:string;action?:string};
type Group={id:string;name?:string;commercial?:string;createdBy?:string;validatedBy?:string;nationality?:string;language?:string;arrival?:string;arrivalTime?:string;departure?:string;departureTime?:string;stayType?:string;breakfastType?:string;housekeepingType?:string;dietary?:string;allergies?:string;rooming?:boolean;depositReceived?:boolean;paymentStatus?:string;amountDue?:number;debtor?:string;status?:string;commercialNotes?:string;commercialValidated?:boolean;audit?:Audit[];mealDays?:MealDay[];leaderFirstName?:string;leaderLastName?:string;leaderPhone?:string;leaderEmail?:string;leader?:string;phone?:string;luggageArrival?:string;luggageDeparture?:string};
type SessionUser={name:string;role:string};
const emptySheets:WeeklySheet[]=[],emptyGroups:Group[]=[];
function user():SessionUser{try{const s=JSON.parse(localStorage.getItem('hospicore.session')||'{}'),u=s.user||{};return{name:`${u.firstName||'Utilisateur'} ${u.lastName||'HospiCore'}`.trim(),role:String(u.role?.name||u.role||'Collaborateur')}}catch{return{name:'Utilisateur HospiCore',role:'Collaborateur'}}}
function iso(d:Date){return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function monday(value=new Date()){const d=new Date(value),day=d.getDay()||7;d.setDate(d.getDate()-day+1);d.setHours(0,0,0,0);return d}
function addDays(value:Date,n:number){const d=new Date(value);d.setDate(d.getDate()+n);return d}
function stamp(){return new Date().toLocaleString('fr-FR')}
function flags(role:string){const r=role.toLowerCase();return{commercial:r.includes('commercial')||r.includes('admin')||r.includes('direction'),reception:r.includes('réception')||r.includes('reception')||r.includes('admin')||r.includes('direction'),direction:r.includes('direction')||r.includes('admin')}}
function dateLabel(v:string){return v?new Date(`${v}T12:00:00`).toLocaleDateString('fr-FR',{day:'2-digit',month:'2-digit',year:'numeric'}):'—'}
function shortDate(v:string){return v?new Date(`${v}T12:00:00`).toLocaleDateString('fr-FR',{day:'2-digit',month:'2-digit'}):'—'}
function creatorOf(g:Group){return g.createdBy||g.audit?.find(a=>a.action?.includes('créée'))?.actor||g.audit?.[0]?.actor||g.validatedBy||g.commercial||'Non attribué'}
function leaderOf(g:Group){const legacy=String(g.leader||'').trim().split(/\s+/);return{first:g.leaderFirstName||legacy.shift()||'',last:g.leaderLastName||legacy.join(' '),phone:g.leaderPhone||g.phone||'',email:g.leaderEmail||''}}
function firstService(g:Group){const d=g.mealDays?.[0];if(d?.dinner?.pax)return'Dîner';if(d?.packedDinner?.pax)return'Panier soir';if(d?.lunch?.pax)return'Déjeuner';return'Logement'}
function lastService(g:Group){const d=g.mealDays?.at(-1);if(d?.breakfast?.pax)return'PDJ';if(d?.packedLunch?.pax)return'Panier midi';if(d?.lunch?.pax)return'Déjeuner';if(d?.packedDinner?.pax)return'Panier soir';if(d?.dinner?.pax)return'Dîner';return'Logement'}
function before(time:string,limit:string){return Boolean(time&&time<limit)}function after(time:string,limit:string){return Boolean(time&&time>limit)}
function mealSummary(g:Group){const rows:string[]=[];(g.mealDays||[]).forEach(day=>([['PDJ',day.breakfast],['Déj.',day.lunch],['Dîner',day.dinner],['Panier midi',day.packedLunch],['Panier soir',day.packedDinner]] as Array<[string,MealCell|undefined]>).forEach(([name,meal])=>{if(!meal?.pax)return;const extras=[meal.water?'Eau':'',meal.wine?'Vin':''].filter(Boolean).join('+');rows.push(`${shortDate(day.date)} ${name} ${meal.pax}${meal.time?` à ${meal.time}`:''}${extras?` · ${extras}`:''}`)}));return rows.join(' · ')||'RAS'}
function normalizeLine(line:LegacyLine):FunctionLine{const legacyMeals=[line.restaurantSummary,line.cuisineSummary].filter(v=>v&&v!=='RAS').join(' · ');return{id:line.id,groupId:line.groupId,commercial:line.commercial,groupName:line.groupName,nationality:line.nationality,stayType:line.stayType,groupStatus:line.groupStatus,remarks:line.remarks,leaderFirstName:line.leaderFirstName,leaderLastName:line.leaderLastName,leaderPhone:line.leaderPhone,leaderEmail:line.leaderEmail,arrivalDate:line.arrivalDate,arrivalTime:line.arrivalTime,arrivalService:line.arrivalService,departureDate:line.departureDate,departureTime:line.departureTime,lastService:line.lastService,roomingReceived:Boolean(line.roomingReceived),luggageArrival:line.luggageArrival,luggageDeparture:line.luggageDeparture,paymentStatus:line.paymentStatus,amountDue:Number(line.amountDue||0),debtor:line.debtor,depositReceived:Boolean(line.depositReceived),breakfastType:line.breakfastType||'Standard',mealSummary:line.mealSummary||legacyMeals||'RAS',dietary:line.dietary||'',roomService:line.roomService||line.housekeepingType||'Standard',earlyCheckIn:line.earlyCheckIn||'Non',lateCheckOut:line.lateCheckOut||'Non',lineStatus:line.lineStatus||'À relire',validatedBy:line.validatedBy||'',validatedAt:line.validatedAt||'',departureConfirmed:Boolean(line.departureConfirmed)}}
function chronological(lines:FunctionLine[]){return[...lines].sort((a,b)=>`${a.arrivalDate||'9999-12-31'}T${a.arrivalTime||'23:59'}`.localeCompare(`${b.arrivalDate||'9999-12-31'}T${b.arrivalTime||'23:59'}`)||a.groupName.localeCompare(b.groupName,'fr',{sensitivity:'base'}))}
function groupToLine(g:Group):FunctionLine{const deposit=Boolean(g.depositReceived||g.paymentStatus==='Payé'),leader=leaderOf(g);return{id:crypto.randomUUID(),groupId:g.id,commercial:creatorOf(g),groupName:g.name||'',nationality:g.nationality||g.language||'',stayType:g.stayType||'',groupStatus:deposit?'Confirmé':g.status||'Préparation',remarks:g.commercialNotes||'',leaderFirstName:leader.first,leaderLastName:leader.last,leaderPhone:leader.phone,leaderEmail:leader.email,arrivalDate:g.arrival||'',arrivalTime:g.arrivalTime||'',arrivalService:firstService(g),departureDate:g.departure||'',departureTime:g.departureTime||'',lastService:lastService(g),roomingReceived:Boolean(g.rooming),luggageArrival:g.luggageArrival||'',luggageDeparture:g.luggageDeparture||'',paymentStatus:g.paymentStatus||'',amountDue:Number(g.amountDue||0),debtor:g.debtor||'',depositReceived:deposit,breakfastType:g.breakfastType||'Standard',mealSummary:mealSummary(g),dietary:g.dietary||g.allergies||'',roomService:g.housekeepingType||'Standard',earlyCheckIn:before(g.arrivalTime||'','16:00')?`Oui · ${g.arrivalTime}`:'Non',lateCheckOut:after(g.departureTime||'','09:00')?`Oui · ${g.departureTime}`:'Non',lineStatus:'À relire',validatedBy:'',validatedAt:'',departureConfirmed:false}}

export function WeeklyPlanningPage(){
 const sheetsStore=useOperationalStore<WeeklySheet[]>('function-sheets',emptySheets),groupsStore=useOperationalStore<Group[]>('group-360',emptyGroups);
 const[weekStart,setWeekStart]=useState(monday),currentUser=user(),permissions=flags(currentUser.role),weekStartIso=iso(weekStart),weekEndIso=iso(addDays(weekStart,6));
 const sheet=useMemo(()=>sheetsStore.data.find(s=>s.weekStart===weekStartIso),[sheetsStore.data,weekStartIso]);
 const lines=useMemo(()=>chronological((sheet?.lines||[]).map(normalizeLine)),[sheet?.lines]);
 const eligible=useMemo(()=>groupsStore.data.filter(g=>g.commercialValidated&&String(g.arrival||'')<=weekEndIso&&String(g.departure||'')>=weekStartIso),[groupsStore.data,weekStartIso,weekEndIso]);
 const locked=sheet?.status==='Clôturée',canEdit=permissions.commercial&&!locked,canConfirm=permissions.reception&&!locked;
 async function saveSheet(next:WeeklySheet){const cleanLines=chronological((next.lines||[]).map(normalizeLine));await sheetsStore.save([...sheetsStore.data.filter(s=>s.id!==next.id),{...next,lines:cleanLines}])}
 async function syncConfirmed(groupId:string,deposit:boolean){await groupsStore.save(groupsStore.data.map(g=>g.id===groupId?{...g,status:'Confirmé',depositReceived:g.depositReceived||deposit}:g))}
 async function importGroups(){if(!permissions.commercial)return;const old=new Map(lines.map(l=>[l.groupId,l]));const imported=eligible.map(g=>{const fresh=groupToLine(g),prior=old.get(g.id);return prior?{...fresh,lineStatus:prior.lineStatus,validatedBy:prior.validatedBy,validatedAt:prior.validatedAt,departureConfirmed:prior.departureConfirmed,depositReceived:prior.depositReceived||fresh.depositReceived,groupStatus:prior.depositReceived||fresh.depositReceived?'Confirmé':fresh.groupStatus}:fresh});await saveSheet(sheet?{...sheet,lines:imported}:{id:crypto.randomUUID(),weekStart:weekStartIso,weekEnd:weekEndIso,status:'Préparation',lines:imported,validatedForPrintBy:'',validatedForPrintAt:'',lockedBy:'',lockedAt:''})}
 async function updateLine(id:string,key:keyof FunctionLine,value:string|boolean){if(!sheet||!canEdit)return;const current=lines.find(l=>l.id===id);if(!current)return;const validates=key==='lineStatus'&&value==='Validée',deposit=key==='depositReceived'&&value===true;const next=lines.map(l=>l.id===id?{...l,[key]:value,lineStatus:key==='lineStatus'?value as LineStatus:'À relire',groupStatus:validates||deposit?'Confirmé':l.groupStatus,validatedBy:validates?currentUser.name:'',validatedAt:validates?stamp():''}:l);await saveSheet({...sheet,lines:next});if(validates||deposit)await syncConfirmed(current.groupId,deposit)}
 async function validateForPrint(){if(sheet&&permissions.commercial&&!lines.some(l=>l.lineStatus!=='Validée'))await saveSheet({...sheet,lines,status:'Prête à imprimer',validatedForPrintBy:currentUser.name,validatedForPrintAt:stamp()})}
 async function markDistributed(){if(sheet&&permissions.commercial&&sheet.status==='Prête à imprimer')await saveSheet({...sheet,lines,status:'Diffusée'})}
 async function confirmDeparture(id:string,checked:boolean){if(!sheet||!canConfirm)return;const next=lines.map(l=>l.id===id?{...l,departureConfirmed:checked,groupStatus:checked?'Parti':l.groupStatus}:l),done=next.length>0&&next.every(l=>l.departureConfirmed);await saveSheet({...sheet,lines:next,status:done?'Clôturée':sheet.status,lockedBy:done?currentUser.name:sheet.lockedBy,lockedAt:done?stamp():sheet.lockedAt})}
 useEffect(()=>{if(!sheet&&permissions.commercial&&eligible.length)void importGroups()},[weekStartIso]);
 if(locked&&!permissions.direction)return <div className="weekly-page"><header className="weekly-header"><div><button onClick={()=>location.href='/commercial'}><ArrowLeft size={18}/>Commercial</button><h1><LockKeyhole/>Fiche clôturée</h1><span>Accessible uniquement à la Direction.</span></div></header></div>;
 return <div className="weekly-page"><header className="weekly-header no-print"><div><button onClick={()=>location.href='/commercial'}><ArrowLeft size={18}/>Commercial</button><p>HospiCore · Commercial & opérations</p><h1><CalendarDays size={30}/>Fiche de fonction hebdomadaire</h1><span>Document dérivé des Fiches Groupe 360° validées. La source de vérité reste la fiche Groupe 360°.</span></div><div className="weekly-actions"><button onClick={()=>void sheetsStore.refresh()}><RefreshCw size={17}/>Actualiser</button>{permissions.commercial&&<button onClick={()=>void importGroups()}>Importer les groupes validés</button>}{sheet?.status==='Prête à imprimer'&&<button className="weekly-print" onClick={()=>window.print()}><Printer size={18}/>Imprimer</button>}</div></header>
 <div className={`sync-banner ${sheetsStore.state} no-print`}><span>{sheetsStore.message}</span></div><section className="weekly-controls no-print"><div className="weekly-nav"><button onClick={()=>setWeekStart(addDays(weekStart,-7))}><ChevronLeft/>Semaine précédente</button><strong>{dateLabel(weekStartIso)} — {dateLabel(weekEndIso)}</strong><button onClick={()=>setWeekStart(addDays(weekStart,7))}>Semaine suivante<ChevronRight/></button></div>{sheet&&<div className={`function-sheet-status ${sheet.status.toLowerCase().replaceAll(' ','-')}`}><ShieldCheck size={18}/><strong>{sheet.status}</strong><span>{lines.filter(l=>l.lineStatus==='Validée').length}/{lines.length} lignes validées</span></div>}</section>
 {!sheet?<section className="panel weekly-empty-state"><h2>Aucune fiche créée</h2><p>{eligible.length} groupe(s) validé(s) peuvent être importés.</p>{permissions.commercial&&<button onClick={()=>void importGroups()}>Créer la fiche</button>}</section>:<><section className="print-header"><div><strong>HOSPICORE · HÔTEL PARADIS</strong><h1>FICHE DE FONCTION HEBDOMADAIRE</h1><p>Semaine du {dateLabel(sheet.weekStart)} au {dateLabel(sheet.weekEnd)}</p></div><div><span>Statut : {sheet.status}</span><span>{lines.length} groupe(s)</span><span>Ordre chronologique des arrivées</span></div></section>
 <section className="function-sheet-table-wrap no-print-table"><table className="function-sheet-table"><thead><tr><th>Chargé du dossier</th><th>Groupe / Tour leader</th><th>Réception</th><th>Repas & prestations</th><th>Chambres & horaires</th><th>Statut</th><th>Contrôle</th></tr></thead><tbody>{lines.map(line=><tr key={line.id} className={line.lineStatus==='Validée'?'line-validated':''}><td>{line.commercial}</td><td><strong>{line.groupName}</strong><br/>{line.nationality}<br/><small>{[line.leaderFirstName,line.leaderLastName].filter(Boolean).join(' ')||'Tour leader non renseigné'} · {line.leaderPhone||'—'} · {line.leaderEmail||'—'}</small></td><td>{shortDate(line.arrivalDate)} {line.arrivalTime} → {shortDate(line.departureDate)} {line.departureTime}<br/>Solde : {line.amountDue.toFixed(2)} € · Bag. {line.luggageArrival||'—'} / {line.luggageDeparture||'—'}</td><td>PDJ {line.breakfastType}<br/>{line.mealSummary}<br/>{line.dietary||'RAS'}</td><td>{line.roomService}<br/>Early : {line.earlyCheckIn} · Late : {line.lateCheckOut}</td><td>{line.groupStatus}</td><td><button className={line.lineStatus==='Validée'?'validated':''} disabled={!canEdit} onClick={()=>void updateLine(line.id,'lineStatus',line.lineStatus==='Validée'?'À relire':'Validée')}>{line.lineStatus==='Validée'&&<CheckCircle2/>}{line.lineStatus}</button><label><input disabled={!canConfirm} type="checkbox" checked={line.departureConfirmed} onChange={e=>void confirmDeparture(line.id,e.target.checked)}/> Départ</label></td></tr>)}</tbody></table></section>
 <section className="print-groups">{lines.map(line=><article className="print-group-card" key={line.id}><header><div><strong>{line.groupName}</strong><span>{line.nationality||'—'} · {line.stayType}</span></div><div><b>{line.groupStatus}</b><small>Chargé du dossier : {line.commercial}</small></div></header><div className="print-block-grid"><section className="print-block general"><h2>Infos générales</h2><p><b>Groupe :</b> {line.groupName}</p><p><b>Nationalité :</b> {line.nationality||'—'} · <b>Séjour :</b> {line.stayType||'—'}</p><p><b>Tour leader :</b> {[line.leaderFirstName,line.leaderLastName].filter(Boolean).join(' ')||'Non renseigné'}</p><p><b>Tél. :</b> {line.leaderPhone||'—'} · <b>E-mail :</b> {line.leaderEmail||'—'}</p>{line.remarks&&<p><b>Remarques :</b> {line.remarks}</p>}</section><section className="print-block reception"><h2>Réception</h2><p><b>Arrivée :</b> {shortDate(line.arrivalDate)} · {line.arrivalTime||'—'} · {line.arrivalService}</p><p><b>Départ :</b> {shortDate(line.departureDate)} · {line.departureTime||'—'} · {line.lastService}</p><p><b>Rooming :</b> {line.roomingReceived?'Reçue':'Manquante'}</p><p><b>Bagagerie :</b> arrivée {line.luggageArrival||'Aucune'} · départ {line.luggageDeparture||'Aucune'}</p></section><section className="print-block meals"><h2>Repas & prestations</h2><p><b>Type de PDJ :</b> {line.breakfastType}</p><p><b>Planning :</b> {line.mealSummary||'RAS'}</p><p><b>Allergies / régimes :</b> {line.dietary||'RAS'}</p></section><section className="print-block rooms"><h2>Chambres & horaires</h2><p><b>Prestation :</b> {line.roomService}</p><p><b>Early check-in :</b> {line.earlyCheckIn}</p><p><b>Late check-out :</b> {line.lateCheckOut}</p></section><section className="print-block accounting"><h2>Comptabilité</h2><p><b>Acompte :</b> {line.depositReceived?'Reçu':'Non reçu'}</p><p><b>Paiement :</b> {line.paymentStatus||'—'}</p>{line.amountDue>0&&<p><b>Reste :</b> {line.amountDue.toFixed(2)} € · <b>Débiteur :</b> {line.debtor||'—'}</p>}</section></div></article>)}</section>
 <section className="print-footer"><span>Document opérationnel issu des Fiches Groupe 360°.</span><span>Validation : {sheet.validatedForPrintBy||'—'} {sheet.validatedForPrintAt&&`· ${sheet.validatedForPrintAt}`}</span></section><section className="function-sheet-footer no-print"><div><strong>Workflow</strong><span>Import des fiches verrouillées → relecture → validation → impression → diffusion → clôture.</span></div>{permissions.commercial&&sheet.status==='Préparation'&&<button disabled={lines.some(l=>l.lineStatus!=='Validée')} onClick={()=>void validateForPrint()}>Valider pour impression</button>}{permissions.commercial&&sheet.status==='Prête à imprimer'&&<button onClick={()=>void markDistributed()}>Confirmer la diffusion</button>}</section></>}</div>;
}
