import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, CalendarDays, CheckCircle2, ChevronLeft, ChevronRight, LockKeyhole, Printer, RefreshCw, ShieldCheck } from 'lucide-react';
import { useOperationalStore } from './useOperationalStore';

type SheetStatus='Préparation'|'Prête à imprimer'|'Diffusée'|'Clôturée';
type LineStatus='À relire'|'Validée';
type MealCell={pax?:number;time?:string;water?:boolean;wine?:boolean};
type MealDay={date:string;breakfast?:MealCell;lunch?:MealCell;packedLunch?:MealCell;dinner?:MealCell;packedDinner?:MealCell;lodging?:MealCell};
type FunctionLine={id:string;groupId:string;commercial:string;groupName:string;nationality:string;arrivalDate:string;arrivalTime:string;arrivalService:string;departureDate:string;departureTime:string;lastService:string;stayType:string;housekeepingType:string;dietary:string;roomingReceived:boolean;depositReceived:boolean;paymentStatus?:string;amountDue?:number;debtor?:string;groupStatus:string;remarks:string;restaurantSummary?:string;cuisineSummary?:string;lineStatus:LineStatus;validatedBy:string;validatedAt:string;departureConfirmed:boolean};
type WeeklySheet={id:string;weekStart:string;weekEnd:string;status:SheetStatus;lines:FunctionLine[];validatedForPrintBy:string;validatedForPrintAt:string;lockedBy:string;lockedAt:string};
type Audit={actor?:string;action?:string};
type Group={id:string;name?:string;agency?:string;commercial?:string;createdBy?:string;validatedBy?:string;nationality?:string;language?:string;arrival?:string;arrivalTime?:string;departure?:string;departureTime?:string;stayType?:string;housekeepingType?:string;dietary?:string;allergies?:string;rooming?:boolean;depositReceived?:boolean;paymentStatus?:string;amountDue?:number;debtor?:string;status?:string;commercialNotes?:string;commercialValidated?:boolean;audit?:Audit[];mealDays?:MealDay[]};
type SessionUser={name:string;role:string};

const emptySheets:WeeklySheet[]=[]; const emptyGroups:Group[]=[];
function user():SessionUser{try{const s=JSON.parse(localStorage.getItem('hospicore.session')||'{}');const u=s.user||{};return{name:`${u.firstName||'Utilisateur'} ${u.lastName||'HospiCore'}`.trim(),role:String(u.role?.name||u.role||'Collaborateur')}}catch{return{name:'Utilisateur HospiCore',role:'Collaborateur'}}}
function iso(d:Date){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function monday(value=new Date()){const d=new Date(value);const day=d.getDay()||7;d.setDate(d.getDate()-day+1);d.setHours(0,0,0,0);return d}
function addDays(value:Date,n:number){const d=new Date(value);d.setDate(d.getDate()+n);return d}
function stamp(){return new Date().toLocaleString('fr-FR')}
function flags(role:string){const r=role.toLowerCase();return{commercial:r.includes('commercial')||r.includes('admin')||r.includes('direction'),reception:r.includes('réception')||r.includes('reception')||r.includes('admin')||r.includes('direction'),direction:r.includes('direction')||r.includes('admin')}}
function dateLabel(v:string){return v?new Date(`${v}T12:00:00`).toLocaleDateString('fr-FR',{day:'2-digit',month:'2-digit',year:'numeric'}):'—'}
function shortDate(v:string){return v?new Date(`${v}T12:00:00`).toLocaleDateString('fr-FR',{day:'2-digit',month:'2-digit'}):'—'}
function creatorOf(g:Group){return g.createdBy||g.audit?.find(a=>a.action?.includes('créée'))?.actor||g.audit?.[0]?.actor||g.validatedBy||g.commercial||'Non attribué'}
function firstService(g:Group){const d=g.mealDays?.[0];if(d?.dinner?.pax)return'Dîner';if(d?.packedDinner?.pax)return'Panier soir';if(d?.lunch?.pax)return'Déjeuner';return'Logement'}
function lastService(g:Group){const d=g.mealDays?.at(-1);if(d?.breakfast?.pax)return'PDJ';if(d?.packedLunch?.pax)return'Panier midi';if(d?.lunch?.pax)return'Déjeuner';if(d?.packedDinner?.pax)return'Panier soir';if(d?.dinner?.pax)return'Dîner';return'Logement'}
function summaries(g:Group){
 const restaurant:string[]=[];const cuisine:string[]=[];
 (g.mealDays||[]).forEach(day=>{
  ([['PDJ',day.breakfast],['Déj.',day.lunch],['Dîner',day.dinner]] as Array<[string,MealCell|undefined]>).forEach(([name,meal])=>{
   if(!meal?.pax||(!meal.water&&!meal.wine))return;
   const supplements=[meal.water?'Eau':'',meal.wine?'Vin':''].filter(Boolean).join('+');
   restaurant.push(`${shortDate(day.date)} ${name} ${meal.pax} : ${supplements}`);
  });
  if(day.packedLunch?.pax)cuisine.push(`${shortDate(day.date)} panier midi : ${day.packedLunch.pax}`);
  if(day.packedDinner?.pax)cuisine.push(`${shortDate(day.date)} panier soir : ${day.packedDinner.pax}`);
 });
 return{restaurant:restaurant.join(' · ')||'RAS',cuisine:cuisine.join(' · ')||'RAS'};
}
function groupToLine(g:Group):FunctionLine{const deposit=Boolean(g.depositReceived||g.paymentStatus==='Payé');const s=summaries(g);return{id:crypto.randomUUID(),groupId:g.id,commercial:creatorOf(g),groupName:g.name||'',nationality:g.nationality||g.language||'',arrivalDate:g.arrival||'',arrivalTime:g.arrivalTime||'',arrivalService:firstService(g),departureDate:g.departure||'',departureTime:g.departureTime||'',lastService:lastService(g),stayType:g.stayType||'',housekeepingType:g.housekeepingType||'Standard',dietary:g.dietary||g.allergies||'',roomingReceived:Boolean(g.rooming),depositReceived:deposit,paymentStatus:g.paymentStatus||'',amountDue:Number(g.amountDue||0),debtor:g.debtor||'',groupStatus:deposit?'Confirmé':g.status||'Préparation',remarks:g.commercialNotes||'',restaurantSummary:s.restaurant,cuisineSummary:s.cuisine,lineStatus:'À relire',validatedBy:'',validatedAt:'',departureConfirmed:false}}

export function WeeklyPlanningPage(){
 const sheetsStore=useOperationalStore<WeeklySheet[]>('function-sheets',emptySheets); const groupsStore=useOperationalStore<Group[]>('group-360',emptyGroups);
 const [weekStart,setWeekStart]=useState(monday); const currentUser=user(); const permissions=flags(currentUser.role); const weekStartIso=iso(weekStart),weekEndIso=iso(addDays(weekStart,6));
 const sheet=useMemo(()=>sheetsStore.data.find(s=>s.weekStart===weekStartIso),[sheetsStore.data,weekStartIso]);
 const eligible=useMemo(()=>groupsStore.data.filter(g=>g.commercialValidated&&String(g.arrival||'')<=weekEndIso&&String(g.departure||'')>=weekStartIso),[groupsStore.data,weekStartIso,weekEndIso]);
 const locked=sheet?.status==='Clôturée',canEdit=permissions.commercial&&!locked,canConfirm=permissions.reception&&!locked;
 async function saveSheet(next:WeeklySheet){await sheetsStore.save([...sheetsStore.data.filter(s=>s.id!==next.id),next])}
 async function syncConfirmed(groupId:string,deposit:boolean){await groupsStore.save(groupsStore.data.map(g=>g.id===groupId?{...g,status:'Confirmé',depositReceived:g.depositReceived||deposit}:g))}
 async function importGroups(){if(!permissions.commercial)return;const old=new Map((sheet?.lines||[]).map(l=>[l.groupId,l]));const lines=eligible.map(g=>{const fresh=groupToLine(g),prior=old.get(g.id);return prior?{...fresh,...prior,commercial:creatorOf(g),restaurantSummary:fresh.restaurantSummary,cuisineSummary:fresh.cuisineSummary,paymentStatus:fresh.paymentStatus,amountDue:fresh.amountDue,debtor:fresh.debtor,depositReceived:prior.depositReceived||fresh.depositReceived,groupStatus:prior.depositReceived||fresh.depositReceived?'Confirmé':prior.groupStatus}:fresh});await saveSheet(sheet?{...sheet,lines}:{id:crypto.randomUUID(),weekStart:weekStartIso,weekEnd:weekEndIso,status:'Préparation',lines,validatedForPrintBy:'',validatedForPrintAt:'',lockedBy:'',lockedAt:''})}
 async function updateLine(id:string,key:keyof FunctionLine,value:string|boolean){if(!sheet||!canEdit)return;const current=sheet.lines.find(l=>l.id===id);if(!current)return;const validates=key==='lineStatus'&&value==='Validée',deposit=key==='depositReceived'&&value===true;const lines=sheet.lines.map(l=>l.id===id?{...l,[key]:value,lineStatus:key==='lineStatus'?value as LineStatus:'À relire',groupStatus:validates||deposit?'Confirmé':l.groupStatus,validatedBy:validates?currentUser.name:'',validatedAt:validates?stamp():''}:l);await saveSheet({...sheet,lines});if(validates||deposit)await syncConfirmed(current.groupId,deposit)}
 async function validateForPrint(){if(sheet&&permissions.commercial&&!sheet.lines.some(l=>l.lineStatus!=='Validée'))await saveSheet({...sheet,status:'Prête à imprimer',validatedForPrintBy:currentUser.name,validatedForPrintAt:stamp()})}
 async function markDistributed(){if(sheet&&permissions.commercial&&sheet.status==='Prête à imprimer')await saveSheet({...sheet,status:'Diffusée'})}
 async function confirmDeparture(id:string,checked:boolean){if(!sheet||!canConfirm)return;const lines=sheet.lines.map(l=>l.id===id?{...l,departureConfirmed:checked,groupStatus:checked?'Parti':l.groupStatus}:l);const done=lines.length>0&&lines.every(l=>l.departureConfirmed);await saveSheet({...sheet,lines,status:done?'Clôturée':sheet.status,lockedBy:done?currentUser.name:sheet.lockedBy,lockedAt:done?stamp():sheet.lockedAt})}
 useEffect(()=>{if(!sheet&&permissions.commercial&&eligible.length)void importGroups()},[weekStartIso]);
 if(locked&&!permissions.direction)return <div className="weekly-page"><header className="weekly-header"><div><button onClick={()=>location.href='/commercial'}><ArrowLeft size={18}/>Commercial</button><h1><LockKeyhole/>Fiche clôturée</h1><span>Accessible uniquement à la Direction.</span></div></header></div>;
 return <div className="weekly-page">
  <header className="weekly-header no-print"><div><button onClick={()=>location.href='/commercial'}><ArrowLeft size={18}/>Commercial</button><p>HospiCore · Commercial & opérations</p><h1><CalendarDays size={30}/>Fiche de fonction hebdomadaire</h1><span>Importée depuis les Fiches Groupe 360° validées.</span></div><div className="weekly-actions"><button onClick={()=>void sheetsStore.refresh()}><RefreshCw size={17}/>Actualiser</button>{permissions.commercial&&<button onClick={()=>void importGroups()}>Importer les groupes validés</button>}{sheet?.status==='Prête à imprimer'&&<button className="weekly-print" onClick={()=>window.print()}><Printer size={18}/>Imprimer</button>}</div></header>
  <div className={`sync-banner ${sheetsStore.state} no-print`}><span>{sheetsStore.message}</span></div>
  <section className="weekly-controls no-print"><div className="weekly-nav"><button onClick={()=>setWeekStart(addDays(weekStart,-7))}><ChevronLeft/>Semaine précédente</button><strong>{dateLabel(weekStartIso)} — {dateLabel(weekEndIso)}</strong><button onClick={()=>setWeekStart(addDays(weekStart,7))}>Semaine suivante<ChevronRight/></button></div>{sheet&&<div className={`function-sheet-status ${sheet.status.toLowerCase().replaceAll(' ','-')}`}><ShieldCheck size={18}/><strong>{sheet.status}</strong><span>{sheet.lines.filter(l=>l.lineStatus==='Validée').length}/{sheet.lines.length} lignes validées</span></div>}</section>
  {!sheet?<section className="panel weekly-empty-state"><h2>Aucune fiche créée</h2><p>{eligible.length} groupe(s) peuvent être importés.</p>{permissions.commercial&&<button onClick={()=>void importGroups()}>Créer la fiche</button>}</section>:<>
   <section className="print-header"><div><strong>HOSPICORE · HÔTEL PARADIS</strong><h1>FICHE DE FONCTION HEBDOMADAIRE</h1><p>Semaine du {dateLabel(sheet.weekStart)} au {dateLabel(sheet.weekEnd)}</p></div><div><span>Statut : {sheet.status}</span><span>{sheet.lines.length} groupe(s)</span><span>Éditée le {new Date().toLocaleDateString('fr-FR')}</span></div></section>
   <section className="function-sheet-table-wrap no-print-table"><table className="function-sheet-table"><thead><tr><th>Commercial</th><th>Groupe</th><th>Nationalité</th><th>Arrivée</th><th>Départ</th><th>Séjour</th><th>Housekeeping</th><th>Restaurant</th><th>Cuisine</th><th>Compta</th><th>Statut</th><th>Contrôle</th></tr></thead><tbody>{sheet.lines.map(line=><tr key={line.id} className={line.lineStatus==='Validée'?'line-validated':''}><td>{line.commercial}</td><td><strong>{line.groupName}</strong></td><td><input disabled={!canEdit} value={line.nationality} onChange={e=>void updateLine(line.id,'nationality',e.target.value)}/></td><td>{shortDate(line.arrivalDate)}<br/><input disabled={!canEdit} type="time" value={line.arrivalTime} onChange={e=>void updateLine(line.id,'arrivalTime',e.target.value)}/><br/>{line.arrivalService}</td><td>{shortDate(line.departureDate)}<br/><input disabled={!canEdit} type="time" value={line.departureTime} onChange={e=>void updateLine(line.id,'departureTime',e.target.value)}/><br/>{line.lastService}</td><td>{line.stayType}</td><td>{line.housekeepingType}</td><td>{line.restaurantSummary}</td><td>{line.cuisineSummary}</td><td><label><input disabled={!canEdit} type="checkbox" checked={line.depositReceived} onChange={e=>void updateLine(line.id,'depositReceived',e.target.checked)}/> Acompte</label><br/>{line.paymentStatus}{line.amountDue?` · ${line.amountDue.toFixed(2)} €`:''}<br/>{line.debtor}</td><td>{line.groupStatus}</td><td><button className={line.lineStatus==='Validée'?'validated':''} disabled={!canEdit} onClick={()=>void updateLine(line.id,'lineStatus',line.lineStatus==='Validée'?'À relire':'Validée')}>{line.lineStatus==='Validée'&&<CheckCircle2/>}{line.lineStatus}</button><label><input disabled={!canConfirm} type="checkbox" checked={line.departureConfirmed} onChange={e=>void confirmDeparture(line.id,e.target.checked)}/> Départ</label></td></tr>)}</tbody></table></section>
   <section className="print-groups">{sheet.lines.map(line=><article className="print-group-card" key={line.id}><header><div><strong>{line.groupName}</strong><span>{line.nationality||'—'} · {line.stayType}</span></div><div><b>{line.groupStatus}</b><small>{line.commercial}</small></div></header><div className="print-block-grid"><section className="print-block general"><h2>Infos générales</h2><p><b>Nationalité :</b> {line.nationality||'—'}</p><p><b>Séjour :</b> {line.stayType}</p>{line.remarks&&<p><b>Remarques :</b> {line.remarks}</p>}</section><section className="print-block reception"><h2>Réception</h2><p><b>Arr. :</b> {shortDate(line.arrivalDate)} · {line.arrivalTime||'—'} · {line.arrivalService}</p><p><b>Dép. :</b> {shortDate(line.departureDate)} · {line.departureTime||'—'} · {line.lastService}</p><p><b>Rooming :</b> {line.roomingReceived?'Oui':'Non'}</p></section><section className="print-block restaurant"><h2>Restaurant</h2><p><b>Suppléments :</b> {line.restaurantSummary||'RAS'}</p>{line.dietary&&<p><b>Régimes :</b> {line.dietary}</p>}</section><section className="print-block cuisine"><h2>Cuisine</h2><p><b>Paniers :</b> {line.cuisineSummary||'RAS'}</p>{line.dietary&&<p><b>Régimes :</b> {line.dietary}</p>}</section><section className="print-block housekeeping"><h2>Housekeeping</h2><p><b>Prestation :</b> {line.housekeepingType}</p></section><section className="print-block accounting"><h2>Compta</h2><p><b>Acompte :</b> {line.depositReceived?'Oui':'Non'} · <b>Paiement :</b> {line.paymentStatus||'—'}</p>{Number(line.amountDue||0)>0&&<p><b>Reste :</b> {Number(line.amountDue).toFixed(2)} € · <b>Débiteur :</b> {line.debtor||'—'}</p>}</section></div></article>)}</section>
   <section className="print-footer"><span>Document diffusé aux services en lecture seule.</span><span>Validation : {sheet.validatedForPrintBy||'—'} {sheet.validatedForPrintAt&&`· ${sheet.validatedForPrintAt}`}</span></section>
   <section className="function-sheet-footer no-print"><div><strong>Workflow</strong><span>Relecture → validation → impression → diffusion → clôture.</span></div>{permissions.commercial&&sheet.status==='Préparation'&&<button disabled={sheet.lines.some(l=>l.lineStatus!=='Validée')} onClick={()=>void validateForPrint()}>Valider pour impression</button>}{permissions.commercial&&sheet.status==='Prête à imprimer'&&<button onClick={()=>void markDistributed()}>Confirmer la diffusion</button>}</section>
  </>}
 </div>
}
